// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as OpencodeEventDecoder from "./OpencodeEventDecoder.mjs";

function sessionIdFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let sessionId = value.sessionID;
    let exit = 0;
    if (typeof sessionId === "string") {
      return sessionId;
    }
    exit = 1;
    if (exit === 1) {
      let sessionId$1 = value.sessionId;
      let exit$1 = 0;
      if (typeof sessionId$1 === "string") {
        return sessionId$1;
      }
      exit$1 = 2;
      if (exit$1 === 2) {
        let info = value.info;
        if (info !== undefined) {
          _value = info;
          continue;
        }
        let session = value.session;
        if (session === undefined) {
          return;
        }
        _value = session;
        continue;
      }
    }
  };
}

function sessionIdFromSessionInfo(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let match = value.info;
  if (typeof match !== "object" || match === null || Array.isArray(match)) {
    return;
  }
  let sessionId = match.id;
  if (typeof sessionId === "string") {
    return sessionId;
  }
}

function sessionIdFromProperties(properties) {
  if (properties !== undefined) {
    return sessionIdFromPayload(properties);
  }
}

function messageIdFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let messageId = value.messageID;
    let exit = 0;
    if (typeof messageId === "string") {
      return messageId;
    }
    exit = 1;
    if (exit === 1) {
      let messageId$1 = value.messageId;
      let exit$1 = 0;
      if (typeof messageId$1 === "string") {
        return messageId$1;
      }
      exit$1 = 2;
      if (exit$1 === 2) {
        let messageId$2 = value.id;
        let exit$2 = 0;
        if (typeof messageId$2 === "string") {
          return messageId$2;
        }
        exit$2 = 3;
        if (exit$2 === 3) {
          let info = value.info;
          if (info !== undefined) {
            _value = info;
            continue;
          }
          let part = value.part;
          if (part === undefined) {
            return;
          }
          _value = part;
          continue;
        }
      }
    }
  };
}

function requestIdFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let requestId = value.requestID;
    let exit = 0;
    if (typeof requestId === "string") {
      return requestId;
    }
    exit = 1;
    if (exit === 1) {
      let requestId$1 = value.requestId;
      let exit$1 = 0;
      if (typeof requestId$1 === "string") {
        return requestId$1;
      }
      exit$1 = 2;
      if (exit$1 === 2) {
        let requestId$2 = value.id;
        let exit$2 = 0;
        if (typeof requestId$2 === "string") {
          return requestId$2;
        }
        exit$2 = 3;
        if (exit$2 === 3) {
          let info = value.info;
          if (info !== undefined) {
            _value = info;
            continue;
          }
          let request = value.request;
          if (request === undefined) {
            return;
          }
          _value = request;
          continue;
        }
      }
    }
  };
}

function partIdFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let partId = value.partID;
    let exit = 0;
    if (typeof partId === "string") {
      return partId;
    }
    exit = 1;
    if (exit === 1) {
      let partId$1 = value.partId;
      let exit$1 = 0;
      if (typeof partId$1 === "string") {
        return partId$1;
      }
      exit$1 = 2;
      if (exit$1 === 2) {
        let partId$2 = value.id;
        let exit$2 = 0;
        if (typeof partId$2 === "string") {
          return partId$2;
        }
        exit$2 = 3;
        if (exit$2 === 3) {
          let part = value.part;
          if (part === undefined) {
            return;
          }
          _value = part;
          continue;
        }
      }
    }
  };
}

function decodeMessageRoleString(value) {
  switch (value) {
    case "assistant" :
      return "AssistantRole";
    case "system" :
      return "SystemRole";
    case "tool" :
      return "ToolRole";
    case "user" :
      return "UserRole";
    default:
      return {
        TAG: "UnknownMessageRole",
        _0: value
      };
  }
}

function decodePartKindString(value) {
  switch (value) {
    case "file" :
      return "FilePart";
    case "text" :
      return "TextPart";
    case "reasoning" :
    case "thinking" :
      return "ReasoningPart";
    case "tool" :
      return "ToolPart";
    default:
      return {
        TAG: "UnknownPartKind",
        _0: value
      };
  }
}

function decodeTodoStatus(value) {
  switch (value) {
    case "cancelled" :
      return "TodoCancelled";
    case "completed" :
      return "TodoCompleted";
    case "in-progress" :
    case "in_progress" :
      return "TodoInProgress";
    case "open" :
      return "TodoOpen";
    default:
      return {
        TAG: "UnknownTodoStatus",
        _0: value
      };
  }
}

function decodeTodoPriority(value) {
  switch (value) {
    case "high" :
      return "PriorityHigh";
    case "low" :
      return "PriorityLow";
    case "medium" :
      return "PriorityMedium";
    default:
      return {
        TAG: "UnknownTodoPriority",
        _0: value
      };
  }
}

function decodeMessageSnapshot(value) {
  let snapshot = OpencodeEventDecoder.decodeMessageSnapshot(value);
  if (snapshot !== undefined) {
    return {
      id: snapshot.id,
      sessionId: snapshot.sessionId,
      role: Stdlib_Option.map(snapshot.role, decodeMessageRoleString)
    };
  }
}

function decodePartSnapshot(value) {
  let snapshot = OpencodeEventDecoder.decodePartSnapshot(value);
  if (snapshot !== undefined) {
    return {
      id: snapshot.id,
      sessionId: snapshot.sessionId,
      messageId: snapshot.messageId,
      partType: Stdlib_Option.map(snapshot.partType, decodePartKindString)
    };
  }
}

function parseSessionStatusKind(value) {
  switch (typeof value) {
    case "string" :
      switch (value) {
        case "busy" :
          return "Busy";
        case "error" :
          return "ErrorStatus";
        case "idle" :
          return "Idle";
        case "interrupted" :
          return "Interrupted";
        case "retry" :
          return "Retry";
        default:
          return {
            TAG: "UnknownStatus",
            _0: value
          };
      }
    case "object" :
      let match = value.type;
      let exit = 0;
      if (typeof match === "string") {
        if (match === "idle") {
          return "Idle";
        }
        exit = 1;
      } else {
        exit = 1;
      }
      if (exit === 1) {
        let match$1 = value.type;
        let exit$1 = 0;
        if (typeof match$1 === "string") {
          if (match$1 === "busy") {
            return "Busy";
          }
          exit$1 = 2;
        } else {
          exit$1 = 2;
        }
        if (exit$1 === 2) {
          let match$2 = value.type;
          let exit$2 = 0;
          if (typeof match$2 === "string") {
            if (match$2 === "retry") {
              return "Retry";
            }
            exit$2 = 3;
          } else {
            exit$2 = 3;
          }
          if (exit$2 === 3) {
            let match$3 = value.type;
            let exit$3 = 0;
            if (typeof match$3 === "string") {
              if (match$3 === "interrupted") {
                return "Interrupted";
              }
              exit$3 = 4;
            } else {
              exit$3 = 4;
            }
            if (exit$3 === 4) {
              let match$4 = value.type;
              let exit$4 = 0;
              if (typeof match$4 === "string") {
                if (match$4 === "error") {
                  return "ErrorStatus";
                }
                exit$4 = 5;
              } else {
                exit$4 = 5;
              }
              if (exit$4 === 5) {
                let value$1 = value.type;
                if (typeof value$1 === "string") {
                  return {
                    TAG: "UnknownStatus",
                    _0: value$1
                  };
                } else {
                  return {
                    TAG: "UnknownStatus",
                    _0: "unknown"
                  };
                }
              }
            }
          }
        }
      }
      break;
    default:
      return {
        TAG: "UnknownStatus",
        _0: "unknown"
      };
  }
}

function sessionStatusKindToString(status) {
  if (typeof status === "object") {
    return status._0;
  }
  switch (status) {
    case "Idle" :
      return "idle";
    case "Busy" :
      return "busy";
    case "Retry" :
      return "retry";
    case "Interrupted" :
      return "interrupted";
    case "ErrorStatus" :
      return "error";
  }
}

function decodeSessionStatusEvent(properties) {
  if (typeof properties !== "object" || properties === null || Array.isArray(properties)) {
    return;
  }
  let sessionId = properties.sessionID;
  if (typeof sessionId === "string") {
    let status = properties.status;
    if (status !== undefined) {
      return {
        sessionId: sessionId,
        status: parseSessionStatusKind(status),
        properties: properties
      };
    }
  }
  let sessionId$1 = properties.sessionId;
  if (typeof sessionId$1 !== "string") {
    return;
  }
  let status$1 = properties.status;
  if (status$1 !== undefined) {
    return {
      sessionId: sessionId$1,
      status: parseSessionStatusKind(status$1),
      properties: properties
    };
  }
}

function decodeSessionDeletedEvent(properties) {
  if (typeof properties === "object" && properties !== null && !Array.isArray(properties)) {
    let match = properties.info;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      let sessionId = match.id;
      if (typeof sessionId === "string") {
        return {
          sessionId: sessionId,
          properties: properties
        };
      }
    }
  }
  let sessionId$1 = sessionIdFromPayload(properties);
  if (sessionId$1 !== undefined) {
    return {
      sessionId: sessionId$1,
      properties: properties
    };
  }
}

function decodeSessionScopedKind(type_) {
  switch (type_) {
    case "message.part.delta" :
      return "MessagePartDelta";
    case "message.part.removed" :
      return "MessagePartRemoved";
    case "message.part.updated" :
      return "MessagePartUpdated";
    case "message.removed" :
      return "MessageRemoved";
    case "message.updated" :
      return "MessageUpdated";
    case "permission.asked" :
      return "PermissionAsked";
    case "permission.replied" :
      return "PermissionReplied";
    case "question.asked" :
      return "QuestionAsked";
    case "question.rejected" :
      return "QuestionRejected";
    case "question.replied" :
      return "QuestionReplied";
    case "session.diff" :
      return "SessionDiff";
    case "todo.updated" :
      return "TodoUpdated";
    default:
      return;
  }
}

function decodeUnknownOrScoped(type_, properties) {
  let kind = decodeSessionScopedKind(type_);
  if (kind !== undefined) {
    return {
      TAG: "SessionScoped",
      _0: {
        kind: kind,
        sessionId: sessionIdFromProperties(properties),
        properties: properties
      }
    };
  } else {
    return {
      TAG: "Unknown",
      _0: {
        type_: type_,
        properties: properties
      }
    };
  }
}

function decode(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return "InvalidPayload";
  }
  let match = value.type;
  let exit = 0;
  if (typeof match === "string") {
    if (match === "global.disposed") {
      return "GlobalDisposed";
    }
    exit = 1;
  } else {
    exit = 1;
  }
  if (exit === 1) {
    let match$1 = value.type;
    let exit$1 = 0;
    if (typeof match$1 === "string") {
      if (match$1 === "server.connected") {
        return "ServerConnected";
      }
      exit$1 = 2;
    } else {
      exit$1 = 2;
    }
    if (exit$1 === 2) {
      let match$2 = value.type;
      let exit$2 = 0;
      if (typeof match$2 === "string") {
        if (match$2 === "server.disconnected") {
          return "ServerDisconnected";
        }
        exit$2 = 3;
      } else {
        exit$2 = 3;
      }
      if (exit$2 === 3) {
        let match$3 = value.type;
        let exit$3 = 0;
        if (typeof match$3 === "string") {
          if (match$3 === "server.instance.disposed") {
            return "ServerInstanceDisposed";
          }
          exit$3 = 4;
        } else {
          exit$3 = 4;
        }
        if (exit$3 === 4) {
          let match$4 = value.type;
          let exit$4 = 0;
          if (match$4 === "project.updated") {
            let properties = value.properties;
            if (properties !== undefined) {
              return {
                TAG: "ProjectUpdated",
                _0: {
                  properties: properties
                }
              };
            }
            exit$4 = 5;
          } else {
            exit$4 = 5;
          }
          if (exit$4 === 5) {
            let match$5 = value.type;
            let exit$5 = 0;
            if (match$5 === "session.created") {
              let properties$1 = value.properties;
              if (properties$1 !== undefined) {
                return {
                  TAG: "SessionCreated",
                  _0: {
                    sessionId: sessionIdFromSessionInfo(properties$1),
                    properties: properties$1
                  }
                };
              }
              exit$5 = 6;
            } else {
              exit$5 = 6;
            }
            if (exit$5 === 6) {
              let match$6 = value.type;
              let exit$6 = 0;
              if (match$6 === "session.updated") {
                let properties$2 = value.properties;
                if (properties$2 !== undefined) {
                  return {
                    TAG: "SessionUpdated",
                    _0: {
                      sessionId: sessionIdFromSessionInfo(properties$2),
                      properties: properties$2
                    }
                  };
                }
                exit$6 = 7;
              } else {
                exit$6 = 7;
              }
              if (exit$6 === 7) {
                let match$7 = value.type;
                let exit$7 = 0;
                if (match$7 === "session.ended") {
                  let properties$3 = value.properties;
                  if (properties$3 !== undefined) {
                    return {
                      TAG: "SessionEnded",
                      _0: {
                        sessionId: sessionIdFromSessionInfo(properties$3),
                        properties: properties$3
                      }
                    };
                  }
                  exit$7 = 8;
                } else {
                  exit$7 = 8;
                }
                if (exit$7 === 8) {
                  let match$8 = value.type;
                  let exit$8 = 0;
                  if (match$8 === "session.deleted") {
                    let properties$4 = value.properties;
                    if (properties$4 !== undefined) {
                      let payload = decodeSessionDeletedEvent(properties$4);
                      if (payload !== undefined) {
                        return {
                          TAG: "SessionDeleted",
                          _0: payload
                        };
                      } else {
                        return {
                          TAG: "Unknown",
                          _0: {
                            type_: "session.deleted",
                            properties: properties$4
                          }
                        };
                      }
                    }
                    exit$8 = 9;
                  } else {
                    exit$8 = 9;
                  }
                  if (exit$8 === 9) {
                    let match$9 = value.type;
                    let exit$9 = 0;
                    if (match$9 === "session.status") {
                      let properties$5 = value.properties;
                      if (properties$5 !== undefined) {
                        let payload$1 = decodeSessionStatusEvent(properties$5);
                        if (payload$1 !== undefined) {
                          return {
                            TAG: "SessionStatusChanged",
                            _0: payload$1
                          };
                        } else {
                          return {
                            TAG: "Unknown",
                            _0: {
                              type_: "session.status",
                              properties: properties$5
                            }
                          };
                        }
                      }
                      exit$9 = 10;
                    } else {
                      exit$9 = 10;
                    }
                    if (exit$9 === 10) {
                      let type_ = value.type;
                      let exit$10 = 0;
                      if (typeof type_ === "string") {
                        return decodeUnknownOrScoped(type_, value.properties);
                      }
                      exit$10 = 11;
                      if (exit$10 === 11) {
                        let type_$1 = value.type;
                        if (typeof type_$1 === "string") {
                          return decodeUnknownOrScoped(type_$1, undefined);
                        } else {
                          return "InvalidPayload";
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

function kindTag(event) {
  if (typeof event !== "object") {
    switch (event) {
      case "GlobalDisposed" :
        return "GlobalDisposedKind";
      case "ServerConnected" :
        return "ServerConnectedKind";
      case "ServerDisconnected" :
        return "ServerDisconnectedKind";
      case "ServerInstanceDisposed" :
        return "ServerInstanceDisposedKind";
      case "InvalidPayload" :
        return "InvalidPayloadKind";
    }
  } else {
    switch (event.TAG) {
      case "ProjectUpdated" :
        return "ProjectUpdatedKind";
      case "SessionCreated" :
        return "SessionCreatedKind";
      case "SessionUpdated" :
        return "SessionUpdatedKind";
      case "SessionEnded" :
        return "SessionEndedKind";
      case "SessionDeleted" :
        return "SessionDeletedKind";
      case "SessionStatusChanged" :
        return "SessionStatusChangedKind";
      case "SessionScoped" :
        return {
          TAG: "SessionScopedKind",
          _0: event._0.kind
        };
      case "Unknown" :
        return {
          TAG: "UnknownKind",
          _0: event._0.type_
        };
    }
  }
}

function kindTagToString(kindTag) {
  if (typeof kindTag === "object") {
    if (kindTag.TAG === "SessionScopedKind") {
      let kind = kindTag._0;
      switch (kind) {
        case "SessionDiff" :
          return "session.diff";
        case "TodoUpdated" :
          return "todo.updated";
        case "MessageUpdated" :
          return "message.updated";
        case "MessageRemoved" :
          return "message.removed";
        case "MessagePartUpdated" :
          return "message.part.updated";
        case "MessagePartRemoved" :
          return "message.part.removed";
        case "MessagePartDelta" :
          return "message.part.delta";
        case "PermissionAsked" :
          return "permission.asked";
        case "PermissionReplied" :
          return "permission.replied";
        case "QuestionAsked" :
          return "question.asked";
        case "QuestionReplied" :
          return "question.replied";
        case "QuestionRejected" :
          return "question.rejected";
      }
    } else {
      return kindTag._0;
    }
  }
  switch (kindTag) {
    case "GlobalDisposedKind" :
      return "global.disposed";
    case "ServerConnectedKind" :
      return "server.connected";
    case "ServerDisconnectedKind" :
      return "server.disconnected";
    case "ServerInstanceDisposedKind" :
      return "server.instance.disposed";
    case "ProjectUpdatedKind" :
      return "project.updated";
    case "SessionCreatedKind" :
      return "session.created";
    case "SessionUpdatedKind" :
      return "session.updated";
    case "SessionEndedKind" :
      return "session.ended";
    case "SessionDeletedKind" :
      return "session.deleted";
    case "SessionStatusChangedKind" :
      return "session.status";
    case "InvalidPayloadKind" :
      return "invalid";
  }
}

function kind(event) {
  return kindTagToString(kindTag(event));
}

function shouldRefresh(event) {
  if (typeof event !== "object") {
    return event !== "InvalidPayload";
  } else {
    return event.TAG !== "Unknown";
  }
}

function refreshPath(event) {
  if (typeof event !== "object") {
    switch (event) {
      case "GlobalDisposed" :
      case "ServerConnected" :
      case "ServerDisconnected" :
      case "ServerInstanceDisposed" :
        return "all";
      case "InvalidPayload" :
        return "none";
    }
  } else {
    switch (event.TAG) {
      case "ProjectUpdated" :
        return "projects";
      case "SessionStatusChanged" :
        return "sessionStatuses";
      case "SessionScoped" :
        return "activeSession";
      case "Unknown" :
        return "none";
      default:
        return "sessions";
    }
  }
}

function refreshPathToString(path) {
  if (path === "activeSession") {
    return "active-session";
  } else if (path === "all") {
    return "all";
  } else if (path === "sessions") {
    return "sessions";
  } else if (path === "projects") {
    return "projects";
  } else if (path === "sessionStatuses") {
    return "session-statuses";
  } else {
    return "none";
  }
}

function sessionId(event) {
  if (typeof event !== "object") {
    return;
  }
  switch (event.TAG) {
    case "SessionCreated" :
    case "SessionUpdated" :
    case "SessionEnded" :
      return event._0.sessionId;
    case "SessionDeleted" :
    case "SessionStatusChanged" :
      return event._0.sessionId;
    case "SessionScoped" :
      return event._0.sessionId;
    case "Unknown" :
      return sessionIdFromProperties(event._0.properties);
    default:
      return;
  }
}

function sessionStatus(event) {
  if (typeof event !== "object" || event.TAG !== "SessionStatusChanged") {
    return;
  } else {
    return event._0;
  }
}

function queueDeltaFromScoped(event) {
  let match = event.kind;
  let match$1 = event.sessionId;
  switch (match) {
    case "PermissionAsked" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          queue: "permission",
          delta: 1
        };
      } else {
        return;
      }
    case "PermissionReplied" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          queue: "permission",
          delta: -1
        };
      } else {
        return;
      }
    case "QuestionAsked" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          queue: "question",
          delta: 1
        };
      } else {
        return;
      }
    case "QuestionReplied" :
    case "QuestionRejected" :
      break;
    default:
      return;
  }
  if (match$1 !== undefined) {
    return {
      sessionId: match$1,
      queue: "question",
      delta: -1
    };
  }
}

function queueDelta(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return queueDeltaFromScoped(event._0);
  }
}

function queueRequestPayloadFromScoped(event, queue) {
  let properties = event.properties;
  if (properties === undefined) {
    return;
  }
  let decodedIds = OpencodeEventDecoder.decodeQueueRequestIds(properties);
  let sessionId = event.sessionId;
  let decodedSessionId = sessionId !== undefined ? sessionId : decodedIds.sessionId;
  let sessionId$1 = decodedSessionId !== undefined ? decodedSessionId : sessionIdFromPayload(properties);
  let requestId = decodedIds.requestId;
  let requestId$1 = requestId !== undefined ? requestId : requestIdFromPayload(properties);
  if (sessionId$1 !== undefined && requestId$1 !== undefined) {
    return {
      queue: queue,
      sessionId: sessionId$1,
      requestId: requestId$1
    };
  }
}

function queueRequestMutationFromScoped(event) {
  let match = event.kind;
  switch (match) {
    case "PermissionAsked" :
      let payload = queueRequestPayloadFromScoped(event, "permission");
      if (payload !== undefined) {
        return {
          TAG: "UpsertQueueRequest",
          _0: payload
        };
      } else {
        return;
      }
    case "PermissionReplied" :
      let payload$1 = queueRequestPayloadFromScoped(event, "permission");
      if (payload$1 !== undefined) {
        return {
          TAG: "RemoveQueueRequest",
          _0: payload$1
        };
      } else {
        return;
      }
    case "QuestionAsked" :
      let payload$2 = queueRequestPayloadFromScoped(event, "question");
      if (payload$2 !== undefined) {
        return {
          TAG: "UpsertQueueRequest",
          _0: payload$2
        };
      } else {
        return;
      }
    case "QuestionReplied" :
    case "QuestionRejected" :
      break;
    default:
      return;
  }
  let payload$3 = queueRequestPayloadFromScoped(event, "question");
  if (payload$3 !== undefined) {
    return {
      TAG: "RemoveQueueRequest",
      _0: payload$3
    };
  }
}

function queueRequestMutation(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return queueRequestMutationFromScoped(event._0);
  }
}

function sessionDiffFromScoped(event) {
  let match = event.kind;
  let match$1 = event.properties;
  if (match === "SessionDiff" && match$1 !== undefined) {
    let payload = OpencodeEventDecoder.decodeSessionDiffEvent(match$1);
    if (payload !== undefined) {
      return {
        sessionId: payload.sessionId,
        diff: payload.diff.map(item => ({
          file: item.file,
          additions: item.additions,
          deletions: item.deletions
        }))
      };
    } else {
      return;
    }
  }
}

function todoUpdatedFromScoped(event) {
  let match = event.kind;
  let match$1 = event.properties;
  if (match === "TodoUpdated" && match$1 !== undefined) {
    let payload = OpencodeEventDecoder.decodeTodoUpdatedEvent(match$1);
    if (payload !== undefined) {
      return {
        sessionId: payload.sessionId,
        todos: payload.todos.map(item => ({
          id: item.id,
          content: item.content,
          status: decodeTodoStatus(item.status),
          priority: decodeTodoPriority(item.priority)
        }))
      };
    } else {
      return;
    }
  }
}

function sessionDiff(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return sessionDiffFromScoped(event._0);
  }
}

function todoUpdated(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return todoUpdatedFromScoped(event._0);
  }
}

function deltaLengthFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let text = value.delta;
    if (typeof text === "string") {
      return text.length;
    }
    let delta = value.delta;
    if (delta !== undefined) {
      _value = delta;
      continue;
    }
    let part = value.part;
    if (part !== undefined) {
      _value = part;
      continue;
    }
    let text$1 = value.text;
    if (typeof text$1 === "string") {
      return text$1.length;
    } else {
      return;
    }
  };
}

function deltaTextFromPayload(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let text = value.delta;
    if (typeof text === "string") {
      if (text === "") {
        return;
      } else {
        return text;
      }
    }
    let delta = value.delta;
    if (delta !== undefined) {
      _value = delta;
      continue;
    }
    let part = value.part;
    if (part !== undefined) {
      _value = part;
      continue;
    }
    let text$1 = value.text;
    if (typeof text$1 === "string" && text$1 !== "") {
      return text$1;
    } else {
      return;
    }
  };
}

function activityDeltaFromScoped(event) {
  let match = event.kind;
  let match$1 = event.sessionId;
  switch (match) {
    case "MessageUpdated" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          metric: "messages",
          delta: 1
        };
      } else {
        return;
      }
    case "MessageRemoved" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          metric: "messages",
          delta: -1
        };
      } else {
        return;
      }
    case "MessagePartUpdated" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          metric: "parts",
          delta: 1
        };
      } else {
        return;
      }
    case "MessagePartRemoved" :
      if (match$1 !== undefined) {
        return {
          sessionId: match$1,
          metric: "parts",
          delta: -1
        };
      } else {
        return;
      }
    case "MessagePartDelta" :
      if (match$1 === undefined) {
        return;
      }
      let properties = event.properties;
      let delta = properties !== undefined ? Stdlib_Option.getOr(deltaLengthFromPayload(properties), 0) : 0;
      if (delta > 0) {
        return {
          sessionId: match$1,
          metric: "deltaChars",
          delta: delta
        };
      } else {
        return;
      }
    default:
      return;
  }
}

function activityDelta(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return activityDeltaFromScoped(event._0);
  }
}

function messageMutationFromScoped(event) {
  let match = event.kind;
  switch (match) {
    case "MessageUpdated" :
      let properties = event.properties;
      if (properties === undefined) {
        return;
      }
      if (typeof properties === "object" && properties !== null && !Array.isArray(properties)) {
        let info = properties.info;
        if (info !== undefined) {
          let message = decodeMessageSnapshot(info);
          if (message !== undefined) {
            return {
              TAG: "UpsertMessage",
              _0: {
                message: message
              }
            };
          } else {
            return;
          }
        }
      }
      let message$1 = decodeMessageSnapshot(properties);
      if (message$1 !== undefined) {
        return {
          TAG: "UpsertMessage",
          _0: {
            message: message$1
          }
        };
      } else {
        return;
      }
      break;
    case "MessageRemoved" :
      let properties$1 = event.properties;
      if (properties$1 === undefined) {
        return;
      }
      let payload = OpencodeEventDecoder.decodeMessageRemovedPayload(properties$1);
      if (payload !== undefined) {
        return {
          TAG: "RemoveMessage",
          _0: {
            sessionId: payload.sessionId,
            messageId: payload.messageId
          }
        };
      }
      let match$1 = event.sessionId;
      let match$2 = messageIdFromPayload(properties$1);
      if (match$1 !== undefined && match$2 !== undefined) {
        return {
          TAG: "RemoveMessage",
          _0: {
            sessionId: match$1,
            messageId: match$2
          }
        };
      } else {
        return;
      }
    case "MessagePartUpdated" :
      let properties$2 = event.properties;
      if (properties$2 === undefined) {
        return;
      }
      if (typeof properties$2 === "object" && properties$2 !== null && !Array.isArray(properties$2)) {
        let part = properties$2.part;
        if (part !== undefined) {
          let part$1 = decodePartSnapshot(part);
          if (part$1 !== undefined) {
            return {
              TAG: "UpsertPart",
              _0: {
                part: part$1
              }
            };
          } else {
            return;
          }
        }
      }
      let part$2 = decodePartSnapshot(properties$2);
      if (part$2 !== undefined) {
        return {
          TAG: "UpsertPart",
          _0: {
            part: part$2
          }
        };
      }
      let match$3 = event.sessionId;
      let match$4 = messageIdFromPayload(properties$2);
      let match$5 = partIdFromPayload(properties$2);
      if (match$3 !== undefined && match$4 !== undefined && match$5 !== undefined) {
        return {
          TAG: "UpsertPart",
          _0: {
            part: {
              id: match$5,
              sessionId: match$3,
              messageId: match$4,
              partType: undefined
            }
          }
        };
      } else {
        return;
      }
      break;
    case "MessagePartRemoved" :
      let properties$3 = event.properties;
      if (properties$3 === undefined) {
        return;
      }
      let payload$1 = OpencodeEventDecoder.decodePartRemovedPayload(properties$3);
      if (payload$1 !== undefined) {
        return {
          TAG: "RemovePart",
          _0: {
            sessionId: event.sessionId,
            messageId: payload$1.messageId,
            partId: payload$1.partId
          }
        };
      }
      let match$6 = messageIdFromPayload(properties$3);
      let match$7 = partIdFromPayload(properties$3);
      if (match$6 !== undefined && match$7 !== undefined) {
        return {
          TAG: "RemovePart",
          _0: {
            sessionId: event.sessionId,
            messageId: match$6,
            partId: match$7
          }
        };
      } else {
        return;
      }
    case "MessagePartDelta" :
      let properties$4 = event.properties;
      if (properties$4 === undefined) {
        return;
      }
      let deltaChars = Stdlib_Option.getOr(deltaLengthFromPayload(properties$4), 0);
      let deltaText = deltaTextFromPayload(properties$4);
      if (deltaChars <= 0 && Stdlib_Option.isNone(deltaText)) {
        return;
      }
      let payload$2 = OpencodeEventDecoder.decodePartDeltaPayload(properties$4);
      if (payload$2 !== undefined) {
        return {
          TAG: "AppendPartDelta",
          _0: {
            sessionId: event.sessionId,
            messageId: payload$2.messageId,
            partId: payload$2.partId,
            field: payload$2.field,
            deltaChars: deltaChars,
            deltaText: deltaText
          }
        };
      }
      let match$8 = messageIdFromPayload(properties$4);
      let match$9 = partIdFromPayload(properties$4);
      if (match$8 !== undefined && match$9 !== undefined) {
        return {
          TAG: "AppendPartDelta",
          _0: {
            sessionId: event.sessionId,
            messageId: match$8,
            partId: match$9,
            field: undefined,
            deltaChars: deltaChars,
            deltaText: deltaText
          }
        };
      } else {
        return;
      }
    default:
      return;
  }
}

function messageMutation(event) {
  if (typeof event !== "object" || event.TAG !== "SessionScoped") {
    return;
  } else {
    return messageMutationFromScoped(event._0);
  }
}

function sessionDeleted(event) {
  if (typeof event !== "object" || event.TAG !== "SessionDeleted") {
    return;
  } else {
    return event._0;
  }
}

function properties(event) {
  if (typeof event !== "object") {
    return;
  }
  switch (event.TAG) {
    case "ProjectUpdated" :
      return event._0.properties;
    case "SessionCreated" :
    case "SessionUpdated" :
    case "SessionEnded" :
    case "SessionDeleted" :
      return event._0.properties;
    case "SessionStatusChanged" :
      return event._0.properties;
    case "SessionScoped" :
      return event._0.properties;
    case "Unknown" :
      return event._0.properties;
  }
}

function decodeKind(value) {
  let event = decode(value);
  return kindTagToString(kindTag(event));
}

function decodeKindTag(value) {
  return kindTag(decode(value));
}

function decodeShouldRefresh(value) {
  return shouldRefresh(decode(value));
}

function decodeRefreshPath(value) {
  return refreshPathToString(refreshPath(decode(value)));
}

function decodeSessionId(value) {
  return sessionId(decode(value));
}

function decodeSessionStatusKind(value) {
  let match = sessionStatus(decode(value));
  if (match !== undefined) {
    return sessionStatusKindToString(match.status);
  }
}

function decodeQueueDelta(value) {
  return queueDelta(decode(value));
}

function decodeActivityDelta(value) {
  return activityDelta(decode(value));
}

function decodeMessageMutation(value) {
  return messageMutation(decode(value));
}

function decodeQueueRequestMutation(value) {
  return queueRequestMutation(decode(value));
}

function decodeSessionDiffFileCount(value) {
  let match = sessionDiff(decode(value));
  if (match !== undefined) {
    return match.diff.length;
  }
}

function decodeTodoCount(value) {
  let match = todoUpdated(decode(value));
  if (match !== undefined) {
    return match.todos.length;
  }
}

export {
  decode,
  kindTag,
  kindTagToString,
  kind,
  shouldRefresh,
  refreshPath,
  refreshPathToString,
  sessionId,
  sessionStatus,
  queueDeltaFromScoped,
  queueDelta,
  queueRequestPayloadFromScoped,
  queueRequestMutationFromScoped,
  queueRequestMutation,
  sessionDiffFromScoped,
  todoUpdatedFromScoped,
  sessionDiff,
  todoUpdated,
  activityDeltaFromScoped,
  activityDelta,
  messageMutationFromScoped,
  messageMutation,
  sessionDeleted,
  properties,
  decodeKindTag,
  decodeKind,
  decodeShouldRefresh,
  decodeRefreshPath,
  decodeSessionId,
  decodeSessionStatusKind,
  decodeQueueDelta,
  decodeActivityDelta,
  decodeMessageMutation,
  decodeQueueRequestMutation,
  decodeSessionDiffFileCount,
  decodeTodoCount,
}
/* OpencodeEventDecoder Not a pure module */
