// Generated by ReScript, PLEASE EDIT WITH CARE


function make(serverUrl, authToken, defaultHeadersOpt, param) {
  let defaultHeaders = defaultHeadersOpt !== undefined ? defaultHeadersOpt : [];
  return {
    serverUrl: serverUrl,
    authToken: authToken,
    defaultHeaders: defaultHeaders
  };
}

function withServerUrl(config, serverUrl) {
  return {
    serverUrl: serverUrl,
    authToken: config.authToken,
    defaultHeaders: config.defaultHeaders
  };
}

function withAuthToken(config, authToken) {
  return {
    serverUrl: config.serverUrl,
    authToken: authToken,
    defaultHeaders: config.defaultHeaders
  };
}

function clearAuthToken(config) {
  return {
    serverUrl: config.serverUrl,
    authToken: undefined,
    defaultHeaders: config.defaultHeaders
  };
}

function withDefaultHeaders(config, defaultHeaders) {
  return {
    serverUrl: config.serverUrl,
    authToken: config.authToken,
    defaultHeaders: defaultHeaders
  };
}

function resolveUrl(config, path) {
  return config.serverUrl + path;
}

export {
  make,
  withServerUrl,
  withAuthToken,
  clearAuthToken,
  withDefaultHeaders,
  resolveUrl,
}
/* No side effect */
