// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpencodeHttp from "./OpencodeHttp.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as OpencodeEvent from "./OpencodeEvent.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as OpencodeConfig from "./OpencodeConfig.mjs";

function decodeMaybeString(value) {
  if (typeof value === "string") {
    return value;
  }
}

function decodeHealth(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let status = value.status;
  if (typeof status === "string") {
    return {
      status: status,
      version: decodeMaybeString(value.version)
    };
  }
  let status$1 = value.status;
  if (typeof status$1 === "string") {
    return {
      status: status$1,
      version: undefined
    };
  }
}

function decodeProject(_value) {
  while (true) {
    let value = _value;
    if (typeof value !== "object" || value === null || Array.isArray(value)) {
      return;
    }
    let projectPayload = value.project;
    if (projectPayload === undefined) {
      return {
        id: decodeMaybeString(value.id),
        name: decodeMaybeString(value.name),
        path: decodeMaybeString(value.path)
      };
    }
    _value = projectPayload;
    continue;
  };
}

function decodeProjectArray(value) {
  let source;
  if (Array.isArray(value)) {
    source = value;
  } else {
    switch (typeof value) {
      case "object" :
        let items = value.projects;
        let exit = 0;
        if (Array.isArray(items)) {
          source = items;
        } else {
          exit = 1;
        }
        if (exit === 1) {
          let items$1 = value.data;
          source = Array.isArray(items$1) ? items$1 : [];
        }
        break;
      default:
        source = [];
    }
  }
  return Stdlib_Array.reduce(source, [], (acc, item) => {
    let project = decodeProject(item);
    if (project !== undefined) {
      return acc.concat([project]);
    } else {
      return acc;
    }
  });
}

function decodeSession(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let id = value.id;
  let exit = 0;
  if (typeof id === "string") {
    let match = value.time;
    if (typeof match === "object" && match !== null && !Array.isArray(match)) {
      let updated = match.updated;
      if (typeof updated === "number") {
        return {
          id: id,
          title: decodeMaybeString(value.title),
          updatedAt: updated.toString()
        };
      }
      exit = 1;
    } else {
      exit = 1;
    }
  } else {
    exit = 1;
  }
  if (exit === 1) {
    let id$1 = value.id;
    let exit$1 = 0;
    if (typeof id$1 === "string") {
      return {
        id: id$1,
        title: decodeMaybeString(value.title),
        updatedAt: decodeMaybeString(value.updated)
      };
    }
    exit$1 = 2;
    if (exit$1 === 2) {
      let id$2 = value.id;
      let exit$2 = 0;
      if (typeof id$2 === "string") {
        return {
          id: id$2,
          title: decodeMaybeString(value.title),
          updatedAt: decodeMaybeString(value.updatedAt)
        };
      }
      exit$2 = 3;
      if (exit$2 === 3) {
        let id$3 = value.id;
        if (typeof id$3 === "string") {
          return {
            id: id$3,
            title: undefined,
            updatedAt: undefined
          };
        } else {
          return;
        }
      }
    }
  }
}

function decodeMessageRole(value) {
  if (typeof value !== "string") {
    return;
  }
  switch (value) {
    case "assistant" :
      return "AssistantRole";
    case "system" :
      return "SystemRole";
    case "tool" :
      return "ToolRole";
    case "user" :
      return "UserRole";
    default:
      return {
        TAG: "UnknownMessageRole",
        _0: value
      };
  }
}

function decodePartKind(value) {
  if (typeof value !== "string") {
    return;
  }
  switch (value) {
    case "file" :
      return "FilePart";
    case "text" :
      return "TextPart";
    case "reasoning" :
    case "thinking" :
      return "ReasoningPart";
    case "tool" :
      return "ToolPart";
    default:
      return {
        TAG: "UnknownPartKind",
        _0: value
      };
  }
}

function decodeStringWithFallback(primary, fallback) {
  let value = decodeMaybeString(primary);
  if (value !== undefined) {
    return value;
  } else {
    return decodeMaybeString(fallback);
  }
}

function decodeSessionMessagePart(value, fallbackSessionId, fallbackMessageId) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let id = value.id;
  if (typeof id !== "string") {
    return;
  }
  let partType = value.type;
  let resolvedSessionId = Stdlib_Option.getOr(decodeStringWithFallback(value.sessionID, value.sessionId), fallbackSessionId);
  let resolvedMessageId = Stdlib_Option.getOr(decodeStringWithFallback(value.messageID, value.messageId), fallbackMessageId);
  let resolvedText = Stdlib_Option.getOr(decodeMaybeString(value.text), "");
  let resolvedPartType = partType !== undefined ? decodePartKind(partType) : undefined;
  return {
    id: id,
    sessionId: resolvedSessionId,
    messageId: resolvedMessageId,
    partType: resolvedPartType,
    text: resolvedText
  };
}

function decodeSessionMessage(value, fallbackSessionId) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let info = value.info;
  if (typeof info !== "object" || info === null || Array.isArray(info)) {
    return;
  }
  let partsRaw = value.parts;
  if (!Array.isArray(partsRaw)) {
    return;
  }
  let match = info["id"];
  let match$1 = decodeStringWithFallback(info["sessionID"], info["sessionId"]);
  if (match === undefined) {
    return;
  }
  if (typeof match !== "string") {
    return;
  }
  if (match$1 === undefined) {
    return {
      id: match,
      sessionId: fallbackSessionId,
      role: undefined,
      parts: []
    };
  }
  let rawRole = info["role"];
  let role = rawRole !== undefined ? decodeMessageRole(rawRole) : undefined;
  let parts = Stdlib_Array.reduce(partsRaw, [], (acc, rawPart) => {
    let part = decodeSessionMessagePart(rawPart, match$1, match);
    if (part !== undefined) {
      return acc.concat([part]);
    } else {
      return acc;
    }
  });
  return {
    id: match,
    sessionId: match$1,
    role: role,
    parts: parts
  };
}

function decodeSessionMessageArray(value, fallbackSessionId) {
  let source;
  if (Array.isArray(value)) {
    source = value;
  } else {
    switch (typeof value) {
      case "object" :
        let items = value.messages;
        let exit = 0;
        if (Array.isArray(items)) {
          source = items;
        } else {
          exit = 1;
        }
        if (exit === 1) {
          let items$1 = value.data;
          source = Array.isArray(items$1) ? items$1 : [];
        }
        break;
      default:
        source = [];
    }
  }
  return Stdlib_Array.reduce(source, [], (acc, item) => {
    let message = decodeSessionMessage(item, fallbackSessionId);
    if (message !== undefined) {
      return acc.concat([message]);
    } else {
      return acc;
    }
  });
}

function decodeSessionEnvelope(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return decodeSession(value);
  }
  let sessionPayload = value.session;
  if (sessionPayload !== undefined) {
    return decodeSession(sessionPayload);
  } else {
    return decodeSession(value);
  }
}

function decodeSessionArray(value) {
  let source;
  if (Array.isArray(value)) {
    source = value;
  } else {
    switch (typeof value) {
      case "object" :
        let items = value.sessions;
        let exit = 0;
        if (Array.isArray(items)) {
          source = items;
        } else {
          exit = 1;
        }
        if (exit === 1) {
          let items$1 = value.data;
          source = Array.isArray(items$1) ? items$1 : [];
        }
        break;
      default:
        source = [];
    }
  }
  return Stdlib_Array.reduce(source, [], (acc, item) => {
    let session = decodeSession(item);
    if (session !== undefined) {
      return acc.concat([session]);
    } else {
      return acc;
    }
  });
}

function decodeSessionStatus(value) {
  if (typeof value !== "string") {
    return;
  }
  switch (value) {
    case "idle" :
      return "idle";
    case "running" :
      return "running";
    default:
      return;
  }
}

function decodeSessionStatusArray(value) {
  if (typeof value === "object" && value !== null && !Array.isArray(value)) {
    return Stdlib_Array.reduce(Object.entries(value), [], (acc, item) => {
      let status = decodeSessionStatus(item[1]);
      if (status !== undefined) {
        return acc.concat([{
            id: item[0],
            status: status
          }]);
      } else {
        return acc;
      }
    });
  } else {
    return [];
  }
}

function normalizedQueryValue(value) {
  if (value === undefined) {
    return;
  }
  let trimmed = value.trim();
  if (trimmed === "") {
    return;
  } else {
    return trimmed;
  }
}

function queryPairs(query) {
  let directory = normalizedQueryValue(query.directory);
  let directoryPairs = directory !== undefined ? [[
        "directory",
        directory
      ]] : [];
  let search = normalizedQueryValue(query.search);
  let searchPairs = search !== undefined ? [[
        "search",
        search
      ]] : [];
  let limit = query.limit;
  let limitPairs = limit !== undefined ? (
      limit > 0 ? [[
            "limit",
            limit.toString()
          ]] : []
    ) : [];
  return directoryPairs.concat(searchPairs).concat(limitPairs);
}

function withQuery(path, pairs) {
  let queryString = Stdlib_Array.reduce(pairs, "", (acc, pair) => {
    let item = encodeURIComponent(pair[0]) + `=` + encodeURIComponent(pair[1]);
    if (acc === "") {
      return item;
    } else {
      return acc + `&` + item;
    }
  });
  if (queryString === "") {
    return path;
  } else {
    return path + `?` + queryString;
  }
}

function withStatusQuery(path, query) {
  let directory = normalizedQueryValue(query.directory);
  if (directory !== undefined) {
    return withQuery(path, [[
        "directory",
        directory
      ]]);
  } else {
    return path;
  }
}

function make(serverUrl, authToken, defaultHeadersOpt, param) {
  let defaultHeaders = defaultHeadersOpt !== undefined ? defaultHeadersOpt : [];
  let config = OpencodeConfig.make(serverUrl, authToken, defaultHeaders, undefined);
  return {
    http: OpencodeHttp.make(config),
    config: config
  };
}

function subscribeGlobalEvents(client, onEvent, onOpenOpt, onErrorOpt, param) {
  let onOpen = onOpenOpt !== undefined ? onOpenOpt : () => {};
  let onError = onErrorOpt !== undefined ? onErrorOpt : param => {};
  let source = new (window.EventSource)(OpencodeConfig.resolveUrl(client.config, "/global/event"));
  source.onopen = () => onOpen();
  source.onmessage = event => {
    let payloadString = event.data;
    try {
      let payload = JSON.parse(payloadString);
      let eventPayload;
      if (typeof payload === "object" && payload !== null && !Array.isArray(payload)) {
        let nestedPayload = payload.payload;
        eventPayload = nestedPayload !== undefined ? nestedPayload : payload;
      } else {
        eventPayload = payload;
      }
      return onEvent(OpencodeEvent.decode(eventPayload));
    } catch (exn) {
      return onError(`Invalid event payload: ` + payloadString);
    }
  };
  source.onerror = () => onError("Global event stream error");
  return {
    close: () => {
      source.close();
    }
  };
}

function closeSubscription(subscription) {
  subscription.close();
}

function errorToString(error) {
  switch (error.TAG) {
    case "NetworkError" :
      return error._0;
    case "HttpError" :
      return `HTTP ` + error.status.toString() + ` ` + error.bodyText;
    case "InvalidJson" :
      return `Invalid JSON: ` + error._0;
  }
}

async function health(client) {
  let error = await OpencodeHttp.getJson(client.http, "/global/health", undefined, undefined);
  if (error.TAG !== "Ok") {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
  let parsed = decodeHealth(error._0);
  if (parsed !== undefined) {
    return {
      TAG: "Ok",
      _0: parsed
    };
  } else {
    return {
      TAG: "Error",
      _0: {
        TAG: "InvalidJson",
        _0: "Expected /global/health JSON object"
      }
    };
  }
}

async function projectCurrent(client) {
  let error = await OpencodeHttp.getJson(client.http, "/project/current", undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeProject(error._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function sessions(client, query, param) {
  let path = query !== undefined ? withQuery("/session", queryPairs(query)) : "/session";
  let error = await OpencodeHttp.getJson(client.http, path, undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeSessionArray(error._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function projects(client) {
  let error = await OpencodeHttp.getJson(client.http, "/project", undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeProjectArray(error._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function sessionById(client, sessionId) {
  let error = await OpencodeHttp.getJson(client.http, `/session/` + sessionId, undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeSessionEnvelope(error._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function sessionStatuses(client, query, param) {
  let path = query !== undefined ? withStatusQuery("/session/status", query) : "/session/status";
  let error = await OpencodeHttp.getJson(client.http, path, undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeSessionStatusArray(error._0)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function sessionMessages(client, sessionId) {
  let error = await OpencodeHttp.getJson(client.http, `/session/` + sessionId + `/message`, undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: decodeSessionMessageArray(error._0, sessionId)
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

async function sendSessionTextMessage(client, sessionId, text, model) {
  let trimmed = text.trim();
  let normalizedModel = Stdlib_Option.flatMap(model, value => {
    let trimmedModel = value.trim();
    if (trimmedModel === "") {
      return;
    } else {
      return trimmedModel;
    }
  });
  if (trimmed === "") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  }
  let part = Object.fromEntries([
    [
      "type",
      "text"
    ],
    [
      "text",
      trimmed
    ]
  ]);
  let bodyPairs = normalizedModel !== undefined ? [
      [
        "parts",
        [part]
      ],
      [
        "model",
        normalizedModel
      ]
    ] : [[
        "parts",
        [part]
      ]];
  let body = Object.fromEntries(bodyPairs);
  let error = await OpencodeHttp.postJsonAck(client.http, `/session/` + sessionId + `/message`, body, undefined, undefined);
  if (error.TAG === "Ok") {
    return {
      TAG: "Ok",
      _0: undefined
    };
  } else {
    return {
      TAG: "Error",
      _0: error._0
    };
  }
}

export {
  make,
  subscribeGlobalEvents,
  closeSubscription,
  errorToString,
  health,
  projectCurrent,
  sessions,
  projects,
  sessionById,
  sessionMessages,
  sessionStatuses,
  sendSessionTextMessage,
}
/* OpencodeEvent Not a pure module */
