// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as OpencodeConfig from "./OpencodeConfig.mjs";

function make(config) {
  return {
    config: config
  };
}

function methodToString(method_) {
  if (method_ === "POST") {
    return "POST";
  } else {
    return "GET";
  }
}

function authHeaders(config) {
  let token = config.authToken;
  if (token !== undefined) {
    return [[
        "Authorization",
        "Bearer " + token
      ]];
  } else {
    return [];
  }
}

function requestHeaders(client, headers, withJsonBody) {
  let baseHeaders = client.config.defaultHeaders.concat(authHeaders(client.config)).concat(headers);
  return Object.fromEntries(withJsonBody ? baseHeaders.concat([[
        "Content-Type",
        "application/json"
      ]]) : baseHeaders);
}

async function requestJson(client, method_, path, headersOpt, body, param) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  try {
    let url = OpencodeConfig.resolveUrl(client.config, path);
    let requestBody = Stdlib_Option.map(body, prim => JSON.stringify(prim));
    let headerObject = requestHeaders(client, headers, Stdlib_Option.isSome(requestBody));
    let init = requestBody !== undefined ? ({
        method: methodToString(method_),
        headers: headerObject,
        body: requestBody
      }) : ({
        method: methodToString(method_),
        headers: headerObject
      });
    let response = await fetch(url, init);
    if (response.ok) {
      let payload = await response.json();
      return {
        TAG: "Ok",
        _0: payload
      };
    }
    let status = response.status;
    let bodyText = await response.text();
    return {
      TAG: "Error",
      _0: {
        TAG: "HttpError",
        status: status,
        bodyText: bodyText
      }
    };
  } catch (exn) {
    return {
      TAG: "Error",
      _0: {
        TAG: "NetworkError",
        _0: "Network request failed"
      }
    };
  }
}

function getJson(client, path, headersOpt, param) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return requestJson(client, "GET", path, headers, undefined, undefined);
}

function postJson(client, path, body, headersOpt, param) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  return requestJson(client, "POST", path, headers, body, undefined);
}

async function postJsonAck(client, path, body, headersOpt, param) {
  let headers = headersOpt !== undefined ? headersOpt : [];
  try {
    let url = OpencodeConfig.resolveUrl(client.config, path);
    let payload = JSON.stringify(body);
    let headerObject = requestHeaders(client, headers, true);
    let init = {
      method: "POST",
      headers: headerObject,
      body: payload
    };
    let response = await fetch(url, init);
    if (response.ok) {
      return {
        TAG: "Ok",
        _0: undefined
      };
    }
    let status = response.status;
    let bodyText = await response.text();
    return {
      TAG: "Error",
      _0: {
        TAG: "HttpError",
        status: status,
        bodyText: bodyText
      }
    };
  } catch (exn) {
    return {
      TAG: "Error",
      _0: {
        TAG: "NetworkError",
        _0: "Network request failed"
      }
    };
  }
}

export {
  make,
  requestJson,
  getJson,
  postJson,
  postJsonAck,
}
/* No side effect */
