// Generated by ReScript, PLEASE EDIT WITH CARE

import * as S from "sury/src/S.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as Primitive_exceptions from "@rescript/runtime/lib/es6/Primitive_exceptions.mjs";

S.enableJson();

function parse(value, schema) {
  try {
    return Primitive_option.some(S.parseOrThrow(value, schema));
  } catch (raw_exn) {
    Primitive_exceptions.internalToException(raw_exn);
    return;
  }
}

function fromEitherSessionId(sessionId, sessionID) {
  if (sessionId !== undefined) {
    return sessionId;
  } else {
    return sessionID;
  }
}

function fromEitherMessageId(messageId, messageID) {
  if (messageId !== undefined) {
    return messageId;
  } else {
    return messageID;
  }
}

function fromEitherPartId(partId, partID) {
  if (partId !== undefined) {
    return partId;
  } else {
    return partID;
  }
}

function fromEitherRequestId(requestId, requestID, id) {
  if (requestId !== undefined) {
    return requestId;
  } else if (requestID !== undefined) {
    return requestID;
  } else {
    return id;
  }
}

function decodeFileDiff(value) {
  if (typeof value !== "object" || value === null || Array.isArray(value)) {
    return;
  }
  let file = value.file;
  if (typeof file !== "string") {
    return;
  }
  let deletions = value.deletions;
  let additions = value.additions;
  let additions$1 = typeof additions === "number" ? additions : undefined;
  let deletions$1 = typeof deletions === "number" ? deletions : undefined;
  return {
    file: file,
    additions: additions$1,
    deletions: deletions$1
  };
}

let sessionDiffRawSchema = S.object(s => ({
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string)),
  diff: s.f("diff", S.array(S.json))
}));

function decodeSessionDiffEvent(value) {
  let payload = parse(value, sessionDiffRawSchema);
  if (payload === undefined) {
    return;
  }
  let sessionId = fromEitherSessionId(payload.sessionId, payload.sessionID);
  if (sessionId !== undefined) {
    return {
      sessionId: sessionId,
      diff: Stdlib_Array.filterMap(payload.diff, decodeFileDiff)
    };
  }
}

let todoItemSchema = S.object(s => ({
  id: s.f("id", S.string),
  content: s.f("content", S.string),
  status: s.f("status", S.string),
  priority: s.f("priority", S.string)
}));

let todoUpdatedRawSchema = S.object(s => ({
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string)),
  todos: s.f("todos", S.array(S.json))
}));

function decodeTodoUpdatedEvent(value) {
  let payload = parse(value, todoUpdatedRawSchema);
  if (payload === undefined) {
    return;
  }
  let sessionId = fromEitherSessionId(payload.sessionId, payload.sessionID);
  if (sessionId !== undefined) {
    return {
      sessionId: sessionId,
      todos: Stdlib_Array.filterMap(payload.todos, item => parse(item, todoItemSchema))
    };
  }
}

let messageSnapshotRawSchema = S.object(s => ({
  id: s.f("id", S.string),
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string)),
  role: s.f("role", S.option(S.string))
}));

function decodeMessageSnapshot(value) {
  let payload = parse(value, messageSnapshotRawSchema);
  if (payload === undefined) {
    return;
  }
  let sessionId = fromEitherSessionId(payload.sessionId, payload.sessionID);
  if (sessionId !== undefined) {
    return {
      id: payload.id,
      sessionId: sessionId,
      role: payload.role
    };
  }
}

let partSnapshotRawSchema = S.object(s => ({
  id: s.f("id", S.string),
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string)),
  messageId: s.f("messageId", S.option(S.string)),
  messageID: s.f("messageID", S.option(S.string)),
  partType: s.f("type", S.option(S.string))
}));

function decodePartSnapshot(value) {
  let payload = parse(value, partSnapshotRawSchema);
  if (payload === undefined) {
    return;
  }
  let match = fromEitherSessionId(payload.sessionId, payload.sessionID);
  let match$1 = fromEitherMessageId(payload.messageId, payload.messageID);
  if (match !== undefined && match$1 !== undefined) {
    return {
      id: payload.id,
      sessionId: match,
      messageId: match$1,
      partType: payload.partType
    };
  }
}

let sessionScopedIdsSchema = S.object(s => ({
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string))
}));

let messageScopedIdsSchema = S.object(s => ({
  messageId: s.f("messageId", S.option(S.string)),
  messageID: s.f("messageID", S.option(S.string))
}));

let partScopedIdsSchema = S.object(s => ({
  partId: s.f("partId", S.option(S.string)),
  partID: s.f("partID", S.option(S.string))
}));

function decodeMessageRemovedPayload(value) {
  let match = parse(value, sessionScopedIdsSchema);
  let match$1 = parse(value, messageScopedIdsSchema);
  if (match === undefined) {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = fromEitherSessionId(match.sessionId, match.sessionID);
  let match$3 = fromEitherMessageId(match$1.messageId, match$1.messageID);
  if (match$2 !== undefined && match$3 !== undefined) {
    return {
      sessionId: match$2,
      messageId: match$3
    };
  }
}

function decodePartRemovedPayload(value) {
  let match = parse(value, messageScopedIdsSchema);
  let match$1 = parse(value, partScopedIdsSchema);
  if (match === undefined) {
    return;
  }
  if (match$1 === undefined) {
    return;
  }
  let match$2 = fromEitherMessageId(match.messageId, match.messageID);
  let match$3 = fromEitherPartId(match$1.partId, match$1.partID);
  if (match$2 !== undefined && match$3 !== undefined) {
    return {
      messageId: match$2,
      partId: match$3
    };
  }
}

let partDeltaRawSchema = S.object(s => ({
  messageId: s.f("messageId", S.option(S.string)),
  messageID: s.f("messageID", S.option(S.string)),
  partId: s.f("partId", S.option(S.string)),
  partID: s.f("partID", S.option(S.string)),
  field: s.f("field", S.option(S.string))
}));

function decodePartDeltaPayload(value) {
  let payload = parse(value, partDeltaRawSchema);
  if (payload === undefined) {
    return;
  }
  let match = fromEitherMessageId(payload.messageId, payload.messageID);
  let match$1 = fromEitherPartId(payload.partId, payload.partID);
  if (match !== undefined && match$1 !== undefined) {
    return {
      messageId: match,
      partId: match$1,
      field: payload.field
    };
  }
}

let queueRequestRawSchema = S.object(s => ({
  sessionId: s.f("sessionId", S.option(S.string)),
  sessionID: s.f("sessionID", S.option(S.string)),
  requestId: s.f("requestId", S.option(S.string)),
  requestID: s.f("requestID", S.option(S.string)),
  id: s.f("id", S.option(S.string)),
  info: s.f("info", S.option(S.json)),
  request: s.f("request", S.option(S.json)),
  session: s.f("session", S.option(S.json))
}));

function mergeQueueRequestIds(primary, fallback) {
  let sessionId = primary.sessionId;
  let requestId = primary.requestId;
  return {
    sessionId: sessionId !== undefined ? sessionId : fallback.sessionId,
    requestId: requestId !== undefined ? requestId : fallback.requestId
  };
}

function decodeQueueRequestIds(value) {
  let payload = parse(value, queueRequestRawSchema);
  if (payload === undefined) {
    return {
      sessionId: undefined,
      requestId: undefined
    };
  }
  let direct_sessionId = fromEitherSessionId(payload.sessionId, payload.sessionID);
  let direct_requestId = fromEitherRequestId(payload.requestId, payload.requestID, payload.id);
  let direct = {
    sessionId: direct_sessionId,
    requestId: direct_requestId
  };
  let info = payload.info;
  let fromInfo = info !== undefined ? decodeQueueRequestIds(info) : ({
      sessionId: undefined,
      requestId: undefined
    });
  let request = payload.request;
  let fromRequest = request !== undefined ? decodeQueueRequestIds(request) : ({
      sessionId: undefined,
      requestId: undefined
    });
  let session = payload.session;
  let fromSession = session !== undefined ? decodeQueueRequestIds(session) : ({
      sessionId: undefined,
      requestId: undefined
    });
  return mergeQueueRequestIds(mergeQueueRequestIds(mergeQueueRequestIds(direct, fromInfo), fromRequest), fromSession);
}

export {
  parse,
  fromEitherSessionId,
  fromEitherMessageId,
  fromEitherPartId,
  fromEitherRequestId,
  decodeFileDiff,
  sessionDiffRawSchema,
  decodeSessionDiffEvent,
  todoItemSchema,
  todoUpdatedRawSchema,
  decodeTodoUpdatedEvent,
  messageSnapshotRawSchema,
  decodeMessageSnapshot,
  partSnapshotRawSchema,
  decodePartSnapshot,
  sessionScopedIdsSchema,
  messageScopedIdsSchema,
  partScopedIdsSchema,
  decodeMessageRemovedPayload,
  decodePartRemovedPayload,
  partDeltaRawSchema,
  decodePartDeltaPayload,
  queueRequestRawSchema,
  mergeQueueRequestIds,
  decodeQueueRequestIds,
}
/*  Not a pure module */
