// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Solid from "rescript-solid/src/Solid.res.mjs";
import * as Counter from "./Counter.mjs";
import * as Features from "./Features.mjs";
import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function App(props) {
  let match = SolidJs.createSignal(true);
  let setShowCounter = match[1];
  let showCounter = match[0];
  let match$1 = SolidJs.createSignal([
    "Apple",
    "Banana",
    "Orange"
  ]);
  SolidJs.createEffect(() => {
    console.log("Counter visibility changed: " + (
      showCounter() ? "visible" : "hidden"
    ));
  });
  return <div>
    <h1>
      {"ReScript + Solid.js Example"}
    </h1>
    <div>
      <button
        onClick={param => setShowCounter(prev => !prev)}
      >
        {showCounter() ? "Hide Counter" : "Show Counter"}
      </button>
    </div>
    <SolidJs.Show
      when={showCounter()}
      fallback={"Counter is hidden"}
    >
      {param => <Counter.make
        initialCount={10}
      />}
    </SolidJs.Show>
    <hr />
    <h2>
      {"List Example"}
    </h2>
    <SolidJs.For
      each={match$1[0]()}
      fallback={null}
    >
      {(item, _i) => <div>
        {item}
      </div>}
    </SolidJs.For>
    <hr />
    <h2>
      {"Reactive Count"}
    </h2>
    <p>
      {"This demonstrates Solid's fine-grained reactivity"}
    </p>
    <hr />
    <Features.make />
    <Solid.jsxFragment>
      {<h>
        {"Should break"}
      </h>}
    </Solid.jsxFragment>
  </div>;
}

let Show;

let For;

let make = App;

export {
  Show,
  For,
  make,
}
/* Counter Not a pure module */
