// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Solid from "rescript-solid/src/Solid.mjs";
import * as SolidJs from "solid-js";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function countryCode(country) {
  if (country === "US") {
    return "US";
  } else {
    return "UK";
  }
}

function countryFromCode(code) {
  if (code === "UK") {
    return "UK";
  } else {
    return "US";
  }
}

function delay(ms) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve(), ms);
  });
}

function money(value) {
  return "$" + value.toFixed(2);
}

let userCountry = {
  contents: "US"
};

function offlineGuess(country) {
  if (country === "US") {
    return {
      courier: "FEDEX_PRIORITY",
      tax: "UK_VAT_FINAL"
    };
  } else {
    return {
      courier: "DHL_EXPRESS",
      tax: "VAT_GUESSED_WRONG"
    };
  }
}

async function fetchUserCountry() {
  await delay(300);
  return userCountry.contents;
}

async function updateUserCountry(country) {
  await delay(1000);
  userCountry.contents = country;
  return country;
}

async function fetchRegionalConfig(country) {
  await delay(3000);
  if (country === "US") {
    return {
      preferredCourierId: "FEDEX_PRIORITY",
      taxSchemeId: "US_SALES_TAX_V2"
    };
  } else {
    return {
      preferredCourierId: "DHL_EXPRESS",
      taxSchemeId: "UK_VAT_FINAL"
    };
  }
}

async function fetchShippingQuote(courierId) {
  await delay(1000);
  if (courierId === "FEDEX_PRIORITY") {
    return 15.0;
  } else {
    return 25.0;
  }
}

async function fetchTaxRate(taxSchemeId) {
  await delay(700);
  switch (taxSchemeId) {
    case "UK_VAT_FINAL" :
    case "VAT_GUESSED_WRONG" :
      return 0.2;
    default:
      return 0.08;
  }
}

function CheckoutOptimistic(props) {
  let match = SolidJs.createSignal(() => fetchUserCountry(), "US");
  let userCountry = match[0];
  let match$1 = SolidJs.createSignal(false);
  let setIsChangingCountry = match$1[1];
  let match$2 = SolidJs.createOptimistic(() => userCountry(), "US");
  let setOptimisticCountry = match$2[1];
  let optimisticCountry = match$2[0];
  let match$3 = SolidJs.createSignal(() => fetchRegionalConfig(optimisticCountry()), {
    preferredCourierId: "FEDEX_PRIORITY",
    taxSchemeId: "US_SALES_TAX_V2"
  });
  let regionalConfig = match$3[0];
  let match$4 = SolidJs.createOptimistic(() => regionalConfig().preferredCourierId, "FEDEX_PRIORITY");
  let setOptimisticCourier = match$4[1];
  let optimisticCourier = match$4[0];
  let match$5 = SolidJs.createOptimistic(() => regionalConfig().taxSchemeId, "US_SALES_TAX_V2");
  let setOptimisticTaxScheme = match$5[1];
  let optimisticTaxScheme = match$5[0];
  let match$6 = SolidJs.createSignal(async () => {
    let provider = optimisticCourier();
    let price = await fetchShippingQuote(provider);
    return {
      provider: provider,
      price: price
    };
  }, {
    provider: "FEDEX_PRIORITY",
    price: 15.0
  });
  let shippingInfo = match$6[0];
  let match$7 = SolidJs.createSignal(async () => {
    let scheme = optimisticTaxScheme();
    let rate = await fetchTaxRate(scheme);
    return {
      scheme: scheme,
      rate: rate
    };
  }, {
    scheme: "US_SALES_TAX_V2",
    rate: 0.08
  });
  let taxInfo = match$7[0];
  let orderTotal = SolidJs.createMemo(() => 100.0 + 100.0 * taxInfo().rate + shippingInfo().price);
  let shippingClass = () => "checkout-breakdown-col " + (
    SolidJs.isPending(() => shippingInfo()) ? "checkout-faded" : ""
  );
  let taxClass = () => "checkout-breakdown-col checkout-breakdown-tax " + (
    SolidJs.isPending(() => taxInfo()) ? "checkout-faded" : ""
  );
  SolidJs.createTrackedEffect(() => {
    if (!SolidJs.isPending(() => userCountry())) {
      return setIsChangingCountry(param => false);
    }
  });
  let handleCountryChange = Solid.action(newCountry => {
    let guess = offlineGuess(newCountry);
    setOptimisticCountry(param => newCountry);
    setOptimisticCourier(param => guess.courier);
    setOptimisticTaxScheme(param => guess.tax);
    return Solid.awaitStep(updateUserCountry(newCountry), param => {
      SolidJs.refresh(userCountry);
      return Solid.doneStep();
    });
  });
  return <section
    className={"checkout-shell"}
  >
    <h1
      className={"checkout-heading"}
    >
      {"Order Checkout"}
    </h1>
    <div
      className={"checkout-country-row"}
    >
      <label
        className={"checkout-country-label"}
      >
        {"Shipping To:"}
      </label>
      <select
        className={"checkout-country-select"}
        disabled={match$1[0]() || SolidJs.isPending(() => userCountry())}
        value={countryCode(optimisticCountry())}
        onChange={event => {
          let next = countryFromCode(event.target.value);
          setIsChangingCountry(param => true);
          handleCountryChange(next);
        }}
      >
        <option
          value={"US"}
        >
          {"USA"}
        </option>
        <option
          value={"UK"}
        >
          {"UK"}
        </option>
      </select>
    </div>
    <p
      className={"checkout-item-price"}
    >
      {"Item Price: " + money(100.0)}
    </p>
    <div
      className={"checkout-breakdown"}
    >
      <div
        className={shippingClass()}
      >
        <p
          className={"checkout-breakdown-title"}
        >
          {"Shipping"}
        </p>
        <p
          className={"checkout-breakdown-line"}
        >
          {"Provider: "}
          <b>
            {shippingInfo().provider}
          </b>
        </p>
        <p
          className={"checkout-breakdown-line"}
        >
          {"Price: " + money(shippingInfo().price)}
        </p>
      </div>
      <div
        className={taxClass()}
      >
        <p
          className={"checkout-breakdown-title"}
        >
          {"Tax"}
        </p>
        <p
          className={"checkout-breakdown-line"}
        >
          {"Tax ID: "}
          <b>
            {taxInfo().scheme}
          </b>
        </p>
        <p
          className={"checkout-breakdown-line"}
        >
          {"Tax Rate: " + money(100.0 * taxInfo().rate) + " (" + (taxInfo().rate * 100.0).toFixed(0) + "%)"}
        </p>
      </div>
    </div>
    <p
      className={"checkout-total"}
    >
      {"Total: " + money(orderTotal())}
    </p>
    <button
      className={"checkout-pay-button"}
      disabled={SolidJs.isPending(optimisticCountry)}
    >
      {SolidJs.isPending(optimisticCountry) ? "Updating Calculations..." : "Pay Now"}
    </button>
  </section>;
}

let make = CheckoutOptimistic;

export {
  make,
}
/* Solid Not a pure module */
