// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.mjs";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function Features$Thrower(props) {
  if (props.shouldThrow) {
    Stdlib_JsError.throwWithMessage("Boom!");
  }
  return <div>
    {"All good"}
  </div>;
}

let Thrower = {
  make: Features$Thrower
};

function Features(props) {
  let fetchGreeting = () => new Promise((resolve, _reject) => {
    setTimeout(() => resolve("Hello from network"), 600);
  });
  let greeting = SolidJs.createMemo(fetchGreeting);
  let match = SolidJs.createSignal(1);
  let setN = match[1];
  let n = match[0];
  let doubled = SolidJs.createMemo(() => (n() << 1));
  let match$1 = SolidJs.createSignal(false);
  let setShouldThrow = match$1[1];
  return <div>
    <h3>
      {"Loading + isPending"}
    </h3>
    <button
      onClick={param => {
        SolidJs.refresh(greeting);
      }}
    >
      {"Refresh Greeting"}
    </button>
    <SolidJs.Show
      when={SolidJs.isPending(() => greeting())}
      fallback={null}
    >
      {param => <div>
        {"Refreshing..."}
      </div>}
    </SolidJs.Show>
    <SolidJs.Loading
      fallback={"Loading..."}
    >
      <div>
        {greeting()}
      </div>
    </SolidJs.Loading>
    <hr />
    <h3>
      {"Memo + Effect"}
    </h3>
    {SolidJs.createTrackedEffect(() => {
      console.log("n=" + n().toString() + ", doubled=" + doubled().toString());
    }), <div>
      <button
        onClick={param => setN(prev => prev + 1 | 0)}
      >
        {"Inc"}
      </button>
      <div>
        {"n="}
        {n()}
        {", doubled="}
        {doubled()}
      </div>
    </div>}
    <hr />
    <h3>
      {"ErrorBoundary"}
    </h3>
    <div>
      <button
        onClick={param => setShouldThrow(prev => !prev)}
      >
        {"Toggle Error"}
      </button>
      <SolidJs.Errored
        fallback={(e, _reset) => <div>
          {"Error: " + e.message}
        </div>}
      >
        <Thrower.make
          shouldThrow={match$1[0]()}
        />
      </SolidJs.Errored>
    </div>
  </div>;
}

let Show;

let Loading;

let ErrorBoundary;

let make = Features;

export {
  Show,
  Loading,
  ErrorBoundary,
  Thrower,
  make,
}
/* solid-js Not a pure module */
