// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as Document from "./Document.mjs";
import * as H from "solid-js/h";
import * as Web from "solid-js/web";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

let root = Document.getElementById("app");

if (root !== undefined) {
  Web.render(() => <App.make />, Primitive_option.valFromOption(root));
} else {
  console.error("Could not find root element");
}

/* root Not a pure module */
