// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";

let match = SolidJs.createSignal(1);

let count = match[0];

SolidJs.createSignal(() => count() + 1 | 0);

SolidJs.createSignal(() => count() + 2 | 0, 0);

SolidJs.createSignal(() => Promise.resolve(count() + 3 | 0));

SolidJs.createOptimistic(0);

SolidJs.createOptimistic(() => count());

SolidJs.createOptimistic(() => count() + 1 | 0, 0);

SolidJs.storePath([
  "todos",
  "0"
]);

SolidJs.createOptimisticStore([
  "a",
  "b"
]);

SolidJs.createOptimisticStore(() => [
  "x",
  "y"
], ["seed"]);

SolidJs.createStore(() => [
  1,
  2,
  3
], [0]);

let _signalSmoke;

let _storeSmoke;

export {
  _signalSmoke,
  _storeSmoke,
}
/* match Not a pure module */
