// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Trigger = {};

let Value = {};

let Icon = {};

let Portal = {};

let Content = {};

let Listbox = {};

let Item = {};

let ItemLabel = {};

let ItemIndicator = {};

export {
  Root,
  Trigger,
  Value,
  Icon,
  Portal,
  Content,
  Listbox,
  Item,
  ItemLabel,
  ItemIndicator,
}
/* No side effect */
