// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Trigger = {};

let Anchor = {};

let Portal = {};

let Content = {};

let Arrow = {};

let Title = {};

let Description = {};

let CloseButton = {};

export {
  Root,
  Trigger,
  Anchor,
  Portal,
  Content,
  Arrow,
  Title,
  Description,
  CloseButton,
}
/* No side effect */
