// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Input = {};

let Control = {};

let Label = {};

let Thumb = {};

let Description = {};

let ErrorMessage = {};

export {
  Root,
  Input,
  Control,
  Label,
  Thumb,
  Description,
  ErrorMessage,
}
/* No side effect */
