// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let List = {};

let Trigger = {};

let Content = {};

let Indicator = {};

export {
  Root,
  List,
  Trigger,
  Content,
  Indicator,
}
/* No side effect */
