// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Trigger = {};

let Portal = {};

let Overlay = {};

let Content = {};

let Title = {};

let Description = {};

let CloseButton = {};

export {
  Root,
  Trigger,
  Portal,
  Overlay,
  Content,
  Title,
  Description,
  CloseButton,
}
/* No side effect */
