// Generated by ReScript, PLEASE EDIT WITH CARE


let Root = {};

let Item = {};

let Header = {};

let Trigger = {};

let Content = {};

export {
  Root,
  Item,
  Header,
  Trigger,
  Content,
}
/* No side effect */
