// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";

let Show = {};

let For = {};

let Index = {};

let Switch = {};

let Match = {};

let ErrorBoundary = {};

let Suspense = {};

let SuspenseList = {};

let Portal = {};

let Dynamic = {};

function SolidJSX$Scope(props) {
  let children = props.children;
  return SolidJs.createRoot(_dispose => children());
}

let Scope = {
  make: SolidJSX$Scope
};

let NoHydration = {};

export {
  Show,
  For,
  Index,
  Switch,
  Match,
  ErrorBoundary,
  Suspense,
  SuspenseList,
  Portal,
  Dynamic,
  Scope,
  NoHydration,
}
/* solid-js Not a pure module */
