// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as SolidActionBridgeMjs from "./SolidActionBridge.mjs";

function jsxFragment(props) {
  return Stdlib_Option.getOr(props.children, null);
}

let Elements = {};

function doneStep(prim) {
  return SolidActionBridgeMjs.done(prim);
}

function awaitStep(prim0, prim1) {
  return SolidActionBridgeMjs.awaitPromise(prim0, prim1);
}

function action0(prim) {
  return SolidActionBridgeMjs.actionFromStepper(prim);
}

function action(prim) {
  return SolidActionBridgeMjs.actionFromStepper(prim);
}

export {
  jsxFragment,
  Elements,
  doneStep,
  awaitStep,
  action0,
  action,
}
/* ./SolidActionBridge.mjs Not a pure module */
