// Generated by ReScript, PLEASE EDIT WITH CARE


function cases(entries) {
  return Object.fromEntries(entries);
}

let MatchValue = {
  cases: cases
};

function cases$1(entries) {
  return Object.fromEntries(entries);
}

let MatchTag = {
  cases: cases$1
};

export {
  MatchValue,
  MatchTag,
}
/* No side effect */
