// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

let Show = {};

function SolidJSX$ShowOption(props) {
  let children = props.children;
  return <SolidJs.Show
    when={props.when_}
    fallback={Stdlib_Option.getOr(props.fallback, null)}
  >
    {opt => {
      if (opt !== undefined) {
        return children(Primitive_option.valFromOption(opt));
      } else {
        return null;
      }
    }}
  </SolidJs.Show>;
}

let ShowOption = {
  make: SolidJSX$ShowOption
};

function ppxDefer(children) {
  let memo = SolidJs.createMemo(children);
  return memo();
}

let For = {};

let Index = {};

let Switch = {};

let Match = {};

let ErrorBoundary = {};

let Suspense = {};

let SuspenseList = {};

let Portal = {};

let Dynamic = {};

function SolidJSX$Scope(props) {
  let children = props.children;
  return SolidJs.createRoot(_dispose => children());
}

let Scope = {
  make: SolidJSX$Scope
};

let NoHydration = {};

export {
  Show,
  ShowOption,
  ppxDefer,
  For,
  Index,
  Switch,
  Match,
  ErrorBoundary,
  Suspense,
  SuspenseList,
  Portal,
  Dynamic,
  Scope,
  NoHydration,
}
/* solid-js Not a pure module */
