// Generated by ReScript, PLEASE EDIT WITH CARE


function handlers(entries) {
  return Object.fromEntries(entries);
}

let WindowEventListener = {};

let DocumentEventListener = {};

export {
  handlers,
  WindowEventListener,
  DocumentEventListener,
}
/* No side effect */
