// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";

let Setter = {};

function make(initialValue) {
  return SolidJs.createStore(initialValue);
}

let StoreUtils = {
  make: make
};

export {
  Setter,
  StoreUtils,
}
/* solid-js Not a pure module */
