// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Home from "./Home.mjs";
import * as User from "./User.mjs";
import * as H from "solid-js/h";
import * as Router from "@solidjs/router";

function App(props) {
  return <Router.Router>
    <Router.Routes>
      <Router.Route
        path={"/"}
        element={<Home.make />}
      />
      <Router.Route
        path={"/user/:name"}
        element={<User.make />}
      />
    </Router.Routes>
  </Router.Router>;
}

let R;

let Home$1;

let User$1;

let make = App;

export {
  R,
  Home$1 as Home,
  User$1 as User,
  make,
}
/* Home Not a pure module */
