// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Foo from "./Foo.mjs";
import * as Home from "./Home.mjs";
import * as User from "./User.mjs";
import * as Stories from "./Stories.mjs";
import * as NotFound from "./NotFound.mjs";
import * as BindingsAudit from "./BindingsAudit.mjs";
import * as Router from "@solidjs/router";
import * as ComplexReactivity from "./ComplexReactivity.mjs";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function rootLayout(props) {
  let isRouting = Router.useIsRouting();
  return <div
    classList={Object.fromEntries([[
        "grey-out",
        isRouting()
      ]])}
  >
    <h1>
      {"Demo: Router"}
    </h1>
    <nav>
      <Router.A
        href={"/"}
      >
        {"Home"}
      </Router.A>
      <Router.A
        href={"/user/alice"}
      >
        {"Alice"}
      </Router.A>
      <Router.A
        href={"/stories"}
      >
        {"Stories (no id)"}
      </Router.A>
      <Router.A
        href={"/stories/123"}
      >
        {"Stories 123"}
      </Router.A>
      <Router.A
        href={"/complex"}
      >
        {"Complex Reactivity"}
      </Router.A>
      <Router.A
        href={"/bindings"}
      >
        {"Bindings Audit"}
      </Router.A>
      <Router.A
        href={"/foo/a/b"}
      >
        {"Foo */*"}
      </Router.A>
      <Router.A
        href={"/missing"}
      >
        {"404"}
      </Router.A>
    </nav>
    {props.children}
  </div>;
}

function App(props) {
  return <Router.Router
    root={rootLayout}
  >
    <Router.Route
      path={"/"}
      component={Home.make}
    />
    <Router.Route
      path={"/user/:name"}
      component={User.make}
    />
    <Router.Route
      path={"/stories/:id?"}
      component={Stories.make}
    />
    <Router.Route
      path={"/complex"}
      component={ComplexReactivity.make}
    />
    <Router.Route
      path={"/bindings"}
      component={BindingsAudit.make}
    />
    <Router.Route
      path={"foo/*any"}
      component={Foo.make}
    />
    <Router.Route
      path={"*404"}
      component={NotFound.make}
    />
  </Router.Router>;
}

let R;

let Home$1;

let User$1;

let ComplexReactivity$1;

let BindingsAudit$1;

let make = App;

export {
  R,
  Home$1 as Home,
  User$1 as User,
  ComplexReactivity$1 as ComplexReactivity,
  BindingsAudit$1 as BindingsAudit,
  rootLayout,
  make,
}
/* Foo Not a pure module */
