// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJSX from "rescript-solid/src/SolidJSX.mjs";
import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Resizable from "@corvu/resizable";
import * as Tabs from "@kobalte/core/tabs";
import * as Dialog from "@kobalte/core/dialog";
import * as Select from "@kobalte/core/select";
import * as Switch from "@kobalte/core/switch";
import * as SolidPrimitivesMatch from "rescript-solid/src/SolidPrimitivesMatch.mjs";
import * as Popover from "@kobalte/core/popover";
import * as $$Map from "@solid-primitives/map";
import * as $$Set from "@solid-primitives/set";
import * as Accordion from "@kobalte/core/accordion";
import * as Match from "@solid-primitives/match";
import * as Media from "@solid-primitives/media";
import * as Trigger from "@solid-primitives/trigger";
import * as Keyboard from "@solid-primitives/keyboard";
import * as SolidPrimitivesEventListener from "rescript-solid/src/SolidPrimitivesEventListener.mjs";
import * as EventListener from "@solid-primitives/event-listener";
import * as ResizeObserver from "@solid-primitives/resize-observer";

function maybeParityMessage(count) {
  if (count % 2 === 0) {
    return "Parity: even";
  }
}

function BindingsAudit(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let match$1 = SolidJs.createSignal(false);
  let setDialogOpen = match$1[1];
  let match$2 = SolidJs.createSignal(false);
  let setPopoverOpen = match$2[1];
  let match$3 = SolidJs.createSignal("item-a");
  let setAccordionValue = match$3[1];
  let match$4 = SolidJs.createSignal("apple");
  let setSelectValue = match$4[1];
  let match$5 = SolidJs.createSignal("first");
  let setTabValue = match$5[1];
  let match$6 = SolidJs.createSignal(0);
  let setWindowClicks = match$6[1];
  let windowClicks = match$6[0];
  let setStore = new $$Set.ReactiveSet([
    "alpha",
    "beta"
  ]);
  let mapStore = new $$Map.ReactiveMap([
    [
      "alpha",
      1
    ],
    [
      "beta",
      2
    ]
  ]);
  let prefersDark = Media.usePrefersDark();
  let isNarrow = Media.createMediaQuery("(max-width: 900px)", undefined);
  let windowSize = ResizeObserver.useWindowSize();
  let windowSizeSnapshot = ResizeObserver.getWindowSize();
  let maybeElementSize = ResizeObserver.getElementSize(undefined);
  let width = maybeElementSize.width;
  let maybeElementWidthText = (width == null) ? "none" : width.toString();
  let match$7 = Trigger.createTrigger();
  let markDirty = match$7[1];
  let trackTrigger = match$7[0];
  EventListener.createEventListener(window, "click", param => setWindowClicks(prev => prev + 1 | 0), undefined);
  EventListener.createEventListenerMap(window, SolidPrimitivesEventListener.handlers([[
      "dblclick",
      param => setCount(prev => prev + 2 | 0)
    ]]), undefined);
  let isShiftHeld = Keyboard.createKeyHold("Shift", undefined);
  let keysDown = Keyboard.useKeyDownList();
  Keyboard.createShortcut([
    "Shift",
    "K"
  ], _event => setCount(prev => prev + 1 | 0), undefined);
  let triggerSummary = () => {
    trackTrigger();
    return "Tracked clicks: " + windowClicks().toString();
  };
  let status = () => {
    if (count() === 0) {
      return "zero";
    } else if (count() < 3) {
      return "low";
    } else {
      return "high";
    }
  };
  let cases = SolidPrimitivesMatch.MatchValue.cases([
    [
      "zero",
      () => <p>
        {"status: zero"}
      </p>
    ],
    [
      "low",
      () => <p>
        {"status: low"}
      </p>
    ],
    [
      "high",
      () => <p>
        {"status: high"}
      </p>
    ]
  ]);
  let message = maybeParityMessage(count());
  return <section>
    <h3>
      {"Binding Audit"}
    </h3>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p>
      {"Count: " + count().toString()}
    </p>
    <p>
      {"Window clicks: " + windowClicks().toString()}
    </p>
    <p>
      {"Window width: " + windowSize.width.toString()}
    </p>
    <p>
      {"Window width snapshot: " + windowSizeSnapshot.width.toString()}
    </p>
    <p>
      {"Element width snapshot: " + maybeElementWidthText}
    </p>
    <p>
      {"Prefers dark: " + (
        prefersDark() ? "true" : "false"
      )}
    </p>
    <p>
      {"Narrow viewport: " + (
        isNarrow() ? "true" : "false"
      )}
    </p>
    <p>
      {"Shift held: " + (
        isShiftHeld() ? "true" : "false"
      )}
    </p>
    <p>
      {"Keys down: " + keysDown().length.toString()}
    </p>
    <p>
      {triggerSummary()}
    </p>
    <button
      onClick={param => markDirty()}
    >
      {"Dirty trigger"}
    </button>
    <EventListener.WindowEventListener
      onMousemove={param => markDirty()}
    />
    <EventListener.DocumentEventListener
      onSelectionchange={param => markDirty()}
    />
    <button
      onClick={param => {
        let name = "item-" + count().toString();
        setStore.add(name);
      }}
    >
      {"Add reactive set item"}
    </button>
    <p>
      {"Reactive set size: " + setStore.size.toString()}
    </p>
    <button
      onClick={param => {
        let next = windowClicks();
        mapStore.set("clicks", next);
      }}
    >
      {"Update reactive map"}
    </button>
    <p>
      {"Reactive map size: " + mapStore.size.toString()}
    </p>
    <Switch.Root
      checked={count() % 2 === 0}
      className={"k-switch"}
    >
      <Switch.Input
        className={"k-switch-input"}
      />
      <Switch.Label>
        {"Even count"}
      </Switch.Label>
      <Switch.Control
        className={"k-switch-control"}
      >
        {<Switch.Thumb
          className={"k-switch-thumb"}
        />}
      </Switch.Control>
      <Switch.Description>
        {"Toggles with count parity"}
      </Switch.Description>
    </Switch.Root>
    <Match.MatchValue
      on={status()}
      case={cases}
      fallback={() => <p>
        {"status: fallback"}
      </p>}
    />
    <Resizable.Root
      orientation={"horizontal"}
      sizes={[
        0.5,
        0.5
      ]}
      className={"resizable"}
    >
      <Resizable.Panel
        initialSize={0.5}
        minSize={0.2}
        className={"resizable-panel"}
      >
        <p>
          {"Left panel"}
        </p>
      </Resizable.Panel>
      <Resizable.Handle
        aria-label={"Resize panels"}
        className={"resizable-handle"}
      />
      <Resizable.Panel
        initialSize={0.5}
        minSize={0.2}
        className={"resizable-panel"}
      >
        <p>
          {"Right panel"}
        </p>
      </Resizable.Panel>
    </Resizable.Root>
    <Tabs.Root
      value={match$5[0]()}
      onChange={next => setTabValue(param => next)}
      className={"k-tabs"}
    >
      <Tabs.List
        className={"k-tabs-list"}
      >
        <Tabs.Trigger
          value={"first"}
        >
          {"First"}
        </Tabs.Trigger>
        <Tabs.Trigger
          value={"second"}
        >
          {"Second"}
        </Tabs.Trigger>
        <Tabs.Indicator
          className={"k-tabs-indicator"}
        />
      </Tabs.List>
      <Tabs.Content
        value={"first"}
      >
        {"First tab content"}
      </Tabs.Content>
      <Tabs.Content
        value={"second"}
      >
        {"Second tab content"}
      </Tabs.Content>
    </Tabs.Root>
    <Dialog.Root
      open={match$1[0]()}
      onOpenChange={next => setDialogOpen(param => next)}
    >
      <Dialog.Trigger
        className={"k-dialog-trigger"}
      >
        {"Open dialog"}
      </Dialog.Trigger>
      <Dialog.Portal>
        <Dialog.Overlay
          className={"k-dialog-overlay"}
        />
        <Dialog.Content
          className={"k-dialog-content"}
        >
          <Dialog.Title>
            {"Kobalte Dialog"}
          </Dialog.Title>
          <Dialog.Description>
            {"Dialog state follows reactive signal"}
          </Dialog.Description>
          <Dialog.CloseButton
            className={"k-dialog-close"}
          >
            {"Close"}
          </Dialog.CloseButton>
        </Dialog.Content>
      </Dialog.Portal>
    </Dialog.Root>
    <Popover.Root
      open={match$2[0]()}
      onOpenChange={next => setPopoverOpen(param => next)}
      modal={false}
      forceMount={true}
      gutter={8}
      flip={true}
      shift={true}
      detachedPadding={6}
      arrowPadding={4}
    >
      <Popover.Anchor
        className={"k-popover-anchor"}
      >
        {<Popover.Trigger
          className={"k-popover-trigger"}
        >
          {"Toggle popover"}
        </Popover.Trigger>}
      </Popover.Anchor>
      <Popover.Portal>
        <Popover.Content
          className={"k-popover-content"}
        >
          <Popover.Arrow
            className={"k-popover-arrow"}
          />
          <Popover.Title>
            {"Kobalte Popover"}
          </Popover.Title>
          <Popover.Description>
            {"Popover follows reactive open state"}
          </Popover.Description>
          <Popover.CloseButton
            className={"k-popover-close"}
          >
            {"Close"}
          </Popover.CloseButton>
        </Popover.Content>
      </Popover.Portal>
    </Popover.Root>
    <Accordion.Root
      value={match$3[0]()}
      onChange={next => setAccordionValue(param => next)}
      collapsible={true}
      className={"k-accordion"}
    >
      <Accordion.Item
        value={"item-a"}
        className={"k-accordion-item"}
      >
        <Accordion.Header
          className={"k-accordion-header"}
        >
          <Accordion.Trigger
            className={"k-accordion-trigger"}
          >
            {"Section A"}
          </Accordion.Trigger>
        </Accordion.Header>
        <Accordion.Content
          className={"k-accordion-content"}
        >
          {"Accordion content A"}
        </Accordion.Content>
      </Accordion.Item>
      <Accordion.Item
        value={"item-b"}
        className={"k-accordion-item"}
      >
        <Accordion.Header
          className={"k-accordion-header"}
        >
          <Accordion.Trigger
            className={"k-accordion-trigger"}
          >
            {"Section B"}
          </Accordion.Trigger>
        </Accordion.Header>
        <Accordion.Content
          className={"k-accordion-content"}
        >
          {"Accordion content B"}
        </Accordion.Content>
      </Accordion.Item>
    </Accordion.Root>
    <Select.Root
      value={match$4[0]()}
      onChange={next => setSelectValue(param => next)}
      className={"k-select"}
    >
      <Select.Trigger
        className={"k-select-trigger"}
      >
        <Select.Value
          className={"k-select-value"}
        />
        <Select.Icon
          className={"k-select-icon"}
        >
          {"v"}
        </Select.Icon>
      </Select.Trigger>
      <Select.Portal>
        <Select.Content
          className={"k-select-content"}
        >
          <Select.Listbox
            className={"k-select-listbox"}
          >
            <Select.Item
              item={"apple"}
              className={"k-select-item"}
            >
              <Select.ItemLabel>
                {"Apple"}
              </Select.ItemLabel>
              <Select.ItemIndicator>
                {"*"}
              </Select.ItemIndicator>
            </Select.Item>
            <Select.Item
              item={"orange"}
              className={"k-select-item"}
            >
              <Select.ItemLabel>
                {"Orange"}
              </Select.ItemLabel>
              <Select.ItemIndicator>
                {"*"}
              </Select.ItemIndicator>
            </Select.Item>
          </Select.Listbox>
        </Select.Content>
      </Select.Portal>
    </Select.Root>
    {SolidJSX.ppxDefer(() => <p>
      {"Deferred count: " + count().toString()}
    </p>)}
    {message !== undefined ? <p>
        {message}
      </p> : <p>
        {"No parity message"}
      </p>}
  </section>;
}

let make = BindingsAudit;

export {
  make,
}
/* SolidJSX Not a pure module */
