// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJSX from "rescript-solid/src/SolidJSX.res.mjs";
import * as SolidJs from "solid-js";
import * as Router from "@solidjs/router";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function loader(_prev) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve("Loaded from createAsync"), 400);
  });
}

function ComplexReactivity(props) {
  let data = Router.createAsync(loader);
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let match$1 = SolidJs.createSignal(1);
  let setStep = match$1[1];
  let step = match$1[0];
  let match$2 = SolidJs.createSignal(true);
  let setShowDetails = match$2[1];
  let showDetails = match$2[0];
  let match$3 = SolidJs.createSignal([
    "Alpha",
    "Beta",
    "Gamma"
  ]);
  let setItems = match$3[1];
  let items = match$3[0];
  let match$4 = SolidJs.createSignal(1);
  let setNextId = match$4[1];
  let nextId = match$4[0];
  let location = Router.useLocation();
  let isEven = () => count() % 2 === 0;
  let parityLabel = () => {
    if (isEven()) {
      return "even";
    } else {
      return "odd";
    }
  };
  let maybeMessage = () => {
    if (count() % 3 === 0) {
      return "Multiple of 3";
    }
  };
  let status = () => {
    if (count() === 0) {
      return "zero";
    } else if (count() <= 5) {
      return "low";
    } else {
      return "high";
    }
  };
  let loadState = () => {
    if (isEven()) {
      return {
        TAG: "Loaded",
        _0: "Even count ready"
      };
    } else {
      return "Loading";
    }
  };
  let addItem = param => {
    let id = nextId();
    setNextId(param => id + 1 | 0);
    setItems(prev => prev.concat(["Item " + id.toString()]));
  };
  let clearItems = param => setItems(param => []);
  let scoped = () => <p>
    {"Scoped count: "}
    {count().toString()}
  </p>;
  let match$5 = status();
  let tmp;
  switch (match$5) {
    case "low" :
      tmp = <p>
        {"Counting"}
      </p>;
      break;
    case "zero" :
      tmp = <p>
        {"Start state"}
      </p>;
      break;
    default:
      tmp = <p>
        {"High count"}
      </p>;
  }
  let message = loadState();
  let tmp$1;
  tmp$1 = typeof message !== "object" ? <p>
      {"Waiting for even count"}
    </p> : <p>
      {message._0}
    </p>;
  let msg = maybeMessage();
  return <div>
    <h2>
      {"Complex Reactivity"}
    </h2>
    <p>
      {"Path: "}
      {location.pathname}
    </p>
    <section>
      <h3>
        {"Async"}
      </h3>
      <SolidJSX.ShowOption.make
        when_={data()}
        fallback={<p>
          {"Loading..."}
        </p>}
      >
        {text => <p>
          {text}
        </p>}
      </SolidJSX.ShowOption.make>
    </section>
    <section>
      <h3>
        {"Counters"}
      </h3>
      <p>
        {"Count: "}
        {count().toString()}
      </p>
      <p>
        {"Step: "}
        {step().toString()}
      </p>
      <button
        onClick={param => setCount(prev => prev + step() | 0)}
      >
        {"Increment"}
      </button>
      <button
        onClick={param => setCount(prev => prev - step() | 0)}
      >
        {"Decrement"}
      </button>
      <button
        onClick={param => setCount(param => 0)}
      >
        {"Reset"}
      </button>
      <button
        onClick={param => setStep(prev => prev + 1 | 0)}
      >
        {"Step +1"}
      </button>
      <button
        onClick={param => setStep(prev => {
          if (prev > 1) {
            return prev - 1 | 0;
          } else {
            return prev;
          }
        })}
      >
        {"Step -1"}
      </button>
    </section>
    <section>
      <h3>
        {"Derived"}
      </h3>
      <p>
        {"Doubled: "}
        {(count() << 1).toString()}
      </p>
      <p>
        {"Parity: "}
        {parityLabel()}
      </p>
      <p>
        {"Status: "}
        {status()}
      </p>
      {tmp}
      {tmp$1}
      {msg !== undefined ? <p>
          {msg}
        </p> : <p>
          {"No multiple of 3 yet"}
        </p>}
    </section>
    <section>
      <h3>
        {"List"}
      </h3>
      <p>
        {"Items: "}
        {items().length.toString()}
      </p>
      <button
        onClick={addItem}
      >
        {"Add item"}
      </button>
      <button
        onClick={clearItems}
      >
        {"Clear"}
      </button>
      <ul>
        <SolidJs.For
          each={items()}
        >
          {(item, index) => <li>
            {index().toString()}
            {": "}
            {item}
          </li>}
        </SolidJs.For>
      </ul>
    </section>
    <section>
      <h3>
        {"Scoped"}
      </h3>
      <button
        onClick={param => setShowDetails(prev => !prev)}
      >
        {showDetails() ? "Hide details" : "Show details"}
      </button>
      <SolidJs.Show
        when={showDetails()}
      >
        {param => <div>
          <p>
            {"Details visible"}
          </p>
          {scoped()}
        </div>}
      </SolidJs.Show>
    </section>
  </div>;
}

let make = ComplexReactivity;

export {
  make,
}
/* SolidJSX Not a pure module */
