// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function DeferNativeProbe(props) {
  let match = SolidJs.createSignal(0);
  return <div>
    <p>
      {"Probe"}
    </p>
    <p>
      {"Deferred count: " + match[0]().toString()}
    </p>
  </div>;
}

let make = DeferNativeProbe;

export {
  make,
}
/* solid-js Not a pure module */
