// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidRouter from "rescript-solid-router/src/SolidRouter.mjs";
import * as Router from "@solidjs/router";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

let P = {};

let Params = SolidRouter.MakeParams(P);

function Foo(props) {
  let p = Router.useParams();
  return <div>
    <h2>
      {"Foo wildcard"}
    </h2>
    <p>
      {p.any}
    </p>
  </div>;
}

let R;

let make = Foo;

export {
  R,
  P,
  Params,
  make,
}
/* Params Not a pure module */
