// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H from "solid-js/h";
import * as Router from "@solidjs/router";

function Home(props) {
  let loader = _prev => new Promise((resolve, _reject) => {
    setTimeout(() => resolve("Loaded from createAsync"), 400);
  });
  let data = Router.createAsync(loader);
  let navigate = Router.useNavigate();
  let text = data();
  return <div>
    <h2>
      {"Home"}
    </h2>
    <p>
      {text !== undefined ? text : "Loading..."}
    </p>
    <Router.A
      href={"/user/alice"}
    >
      {"Go to Alice"}
    </Router.A>
    <button
      onClick={param => navigate("/user/bob")}
    >
      {"Go to Bob (navigate)"}
    </button>
  </div>;
}

let R;

let make = Home;

export {
  R,
  make,
}
/* solid-js/h Not a pure module */
