// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H from "solid-js/h";

function Home(props) {
  return <div>
    {""}
  </div>;
}

let make = Home;

export {
  make,
}
/* solid-js/h Not a pure module */
