// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Router from "@solidjs/router";

function loader(_prev) {
  return new Promise((resolve, _reject) => {
    setTimeout(() => resolve("Loaded from createAsync"), 400);
  });
}

function Home(props) {
  let data = Router.createAsync(loader);
  let navigate = Router.useNavigate();
  return <div>
    <h2>
      {"Home"}
    </h2>
    <p>
      <SolidJs.Show
        when={data()}
        fallback={"Loading..."}
      >
        {text => {
          if (text !== undefined) {
            return text;
          } else {
            return "Loading...";
          }
        }}
      </SolidJs.Show>
    </p>
    <Router.A
      href={"/user/alice"}
    >
      {"Go to Alice"}
    </Router.A>
    <button
      onClick={param => {
        navigate.call("/user/bob", undefined);
      }}
    >
      {"Go to Bob (navigate)"}
    </button>
  </div>;
}

let R;

let make = Home;

export {
  R,
  loader,
  make,
}
/* solid-js Not a pure module */
