// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Solid from "rescript-solid/src/Solid.res.mjs";
import * as H from "solid-js/h";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Router from "@solidjs/router";

function NestedExample$UsersLayout(props) {
  return <div>
    <h2>
      {"Users Section"}
    </h2>
    <nav>
      <Router.A
        href={"/users"}
      >
        {"All Users"}
      </Router.A>
      {" | "}
      <Router.A
        href={"/users/123"}
      >
        {"User 123"}
      </Router.A>
      {" | "}
      <Router.A
        href={"/users/456"}
      >
        {"User 456"}
      </Router.A>
    </nav>
    <div>
      {props.children}
    </div>
  </div>;
}

let UsersLayout = {
  make: NestedExample$UsersLayout
};

function NestedExample$UsersList(props) {
  return <div>
    <h3>
      {"Users List"}
    </h3>
    <ul>
      <li>
        {"User 1"}
      </li>
      <li>
        {"User 2"}
      </li>
      <li>
        {"User 3"}
      </li>
    </ul>
  </div>;
}

let UsersList = {
  make: NestedExample$UsersList
};

function NestedExample$UserDetail(props) {
  let params = Router.useParams();
  let userId = Stdlib_Option.getOr(params["id"], "unknown");
  return <div>
    <h3>
      {"User Detail"}
    </h3>
    <p>
      {"User ID: " + userId}
    </p>
  </div>;
}

let UserDetail = {
  make: NestedExample$UserDetail
};

function NestedExample$NotFound404(props) {
  return <div>
    <h2>
      {"404 - Not Found"}
    </h2>
    <Router.A
      href={"/users"}
    >
      {"Go to Users"}
    </Router.A>
  </div>;
}

let NotFound404 = {
  make: NestedExample$NotFound404
};

function NestedExample$NestedRoutesExample(props) {
  return <Router.Router>
    <Router.Route
      path={"/users"}
    >
      <Router.Route
        path={"/"}
        component={NestedExample$UsersList}
      />
      <Router.Route
        path={"/:id"}
        component={NestedExample$UserDetail}
      />
    </Router.Route>
    <Router.Route
      path={"*404"}
      component={NestedExample$NotFound404}
    />
  </Router.Router>;
}

let NestedRoutesExample = {
  make: NestedExample$NestedRoutesExample
};

function NestedExample$LoginRegister(props) {
  let location = Router.useLocation();
  let isLogin = location.pathname === "/login";
  return <div>
    <h2>
      {isLogin ? "Login" : "Register"}
    </h2>
    <form>
      <input
        placeholder={"Username"}
        type={"text"}
      />
      <input
        placeholder={"Password"}
        type={"password"}
      />
      {isLogin ? <Solid.jsxFragment /> : <input
          placeholder={"Confirm Password"}
          type={"password"}
        />}
      <button
        type={"submit"}
      >
        {isLogin ? "Login" : "Register"}
      </button>
    </form>
    <p>
      {isLogin ? <Solid.jsxFragment>
          {"Don't have an account? "}
          <Router.A
            href={"/register"}
          >
            {"Register"}
          </Router.A>
        </Solid.jsxFragment> : <Solid.jsxFragment>
          {"Already have an account? "}
          <Router.A
            href={"/login"}
          >
            {"Login"}
          </Router.A>
        </Solid.jsxFragment>}
    </p>
  </div>;
}

let LoginRegister = {
  make: NestedExample$LoginRegister
};

function NestedExample$HomeWithLinks(props) {
  return <div>
    <h2>
      {"Home"}
    </h2>
    <Router.A
      href={"/login"}
    >
      {"Login"}
    </Router.A>
    {" | "}
    <Router.A
      href={"/register"}
    >
      {"Register"}
    </Router.A>
  </div>;
}

let HomeWithLinks = {
  make: NestedExample$HomeWithLinks
};

function NestedExample$MultiPathExample(props) {
  return <Router.Router>
    <Router.Route
      path={[
        "login",
        "register"
      ]}
      component={NestedExample$LoginRegister}
    />
    <Router.Route
      path={"/"}
      component={NestedExample$HomeWithLinks}
    />
  </Router.Router>;
}

let MultiPathExample = {
  make: NestedExample$MultiPathExample
};

let R;

export {
  R,
  UsersLayout,
  UsersList,
  UserDetail,
  NotFound404,
  NestedRoutesExample,
  LoginRegister,
  HomeWithLinks,
  MultiPathExample,
}
/* solid-js/h Not a pure module */
