// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H from "solid-js/h";

function NotFound(props) {
  return <div>
    {"404 Not Found"}
  </div>;
}

let make = NotFound;

export {
  make,
}
/* solid-js/h Not a pure module */
