// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function NotFound(props) {
  return <div>
    {"404 Not Found"}
  </div>;
}

let make = NotFound;

export {
  make,
}
/* @solidjs/h/jsx-runtime Not a pure module */
