// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidRouter from "rescript-solid-router/src/SolidRouter.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as Router from "@solidjs/router";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

let P = {};

let Params = SolidRouter.MakeParams(P);

function Stories(props) {
  let p = Router.useParams();
  return <div>
    <h2>
      {"Stories"}
    </h2>
    <p>
      {"id="}
      {Stdlib_Option.getOr(p.id, "none")}
    </p>
  </div>;
}

let R;

let make = Stories;

export {
  R,
  P,
  Params,
  make,
}
/* Params Not a pure module */
