// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as Router from "@solidjs/router";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

let Window = {};

function TypedHooks$TypedHooksDemo(props) {
  let location = Router.useLocation();
  let isRouting = Router.useIsRouting();
  let params = Router.useParams();
  let match = Router.useSearchParams();
  let setSearchParams = match[1];
  let navigate = Router.useNavigate();
  let getCurrentMatches = Router.useCurrentMatches();
  let matchHome = Router.useMatch(() => "/", undefined);
  let matchUser = Router.useMatch(() => "/user/:id", Object.fromEntries([[
      "id",
      {
        TAG: "Regex",
        _0: /^\d+$/
      }
    ]]));
  return <div>
    <h2>
      {"Router Hooks Demo"}
    </h2>
    <section>
      <h3>
        {"Location"}
      </h3>
      <ul>
        <li>
          {"Pathname: " + location.pathname}
        </li>
        <li>
          {"Search: " + location.search}
        </li>
        <li>
          {"Hash: " + location.hash}
        </li>
        <li>
          {"Key: " + location.key}
        </li>
      </ul>
    </section>
    <section>
      <h3>
        {"Routing Status"}
      </h3>
      <p>
        {"Is routing: " + (
          isRouting() ? "Yes" : "No"
        )}
      </p>
    </section>
    <section>
      <h3>
        {"Params"}
      </h3>
      <ul>
        {Object.entries(params).map(param => {
          let key = param[0];
          return <li
            key={key} >
            {key + ": " + param[1]}
          </li>;
        })}
      </ul>
    </section>
    <section>
      <h3>
        {"Search Params"}
      </h3>
      <ul>
        {Object.entries(match[0]).map(param => {
          let key = param[0];
          return <li
            key={key} >
            {key + ": " + param[1]}
          </li>;
        })}
      </ul>
      <button
        onClick={param => setSearchParams(Object.fromEntries([[
            "test",
            "value"
          ]]))}
      >
        {"Set Test Param"}
      </button>
    </section>
    <section>
      <h3>
        {"Navigation"}
      </h3>
      <button
        onClick={param => {
          navigate.call("/", {
            replace: true
          });
        }}
      >
        {"Go Home (replace)"}
      </button>
      <button
        onClick={param => {
          navigate.call(-1);
        }}
      >
        {"Go Back"}
      </button>
    </section>
    <section>
      <h3>
        {"Route Matches"}
      </h3>
      <p>
        {"Home match: " + (
          matchHome() !== undefined ? "Yes" : "No"
        )}
      </p>
      <p>
        {"User match: " + (
          matchUser() !== undefined ? "Yes" : "No"
        )}
      </p>
      <h4>
        {"Current Matches:"}
      </h4>
      <ul>
        {getCurrentMatches().map(match => <li
          key={match.route.originalPath} >
          {"Path: " + match.path + ", Pattern: " + match.route.pattern}
        </li>)}
      </ul>
    </section>
  </div>;
}

let TypedHooksDemo = {
  make: TypedHooks$TypedHooksDemo
};

function TypedHooks$NavigationGuard(props) {
  let match = SolidJs.createSignal(false);
  let setIsDirty = match[1];
  let isDirty = match[0];
  Router.useBeforeLeave(e => {
    if (isDirty() && !window.confirm("You have unsaved changes. Are you sure you want to leave?")) {
      return e.preventDefault();
    }
  });
  return <div>
    <h3>
      {"Navigation Guard Example"}
    </h3>
    <label>
      <input
        checked={isDirty()}
        type={"checkbox"}
        onChange={param => setIsDirty(prev => !prev)}
      />
      {" Simulate unsaved changes"}
    </label>
    <p>
      {isDirty() ? "Try navigating away - you'll be prompted!" : "Navigation is unrestricted"}
    </p>
  </div>;
}

let NavigationGuard = {
  make: TypedHooks$NavigationGuard
};

let R;

export {
  R,
  Window,
  TypedHooksDemo,
  NavigationGuard,
}
/* solid-js Not a pure module */
