// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as SolidRouter from "rescript-solid-router/src/SolidRouter.mjs";
import * as Router from "@solidjs/router";

let P = {};

let TypedParams = SolidRouter.MakeParams(P);

function User(props) {
  let params = Router.useParams();
  let name = SolidJs.createMemo(() => params.name);
  return <div>
    <h2>
      {"User: "}
      {name()}
    </h2>
  </div>;
}

let R;

let make = User;

export {
  R,
  P,
  TypedParams,
  make,
}
/* TypedParams Not a pure module */
