// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.mjs";
import * as H from "solid-js/h";
import * as AppProviders from "./AppProviders.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as OpencodeEvent from "opencode-example-sdk/src/OpencodeEvent.mjs";
import * as ServerContext from "./ServerContext.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as OpencodeClient from "opencode-example-sdk/src/OpencodeClient.mjs";
import * as Router from "@solidjs/router";
import * as PlatformContext from "./PlatformContext.mjs";
import * as GlobalSDKContext from "./GlobalSDKContext.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as GlobalSyncContext from "./GlobalSyncContext.mjs";
import * as GlobalEventReducer from "./GlobalEventReducer.mjs";

function renderProjectLabel(project) {
  let name = Stdlib_Option.getOr(project.name, "unnamed");
  let path = Stdlib_Option.getOr(project.path, "unknown-path");
  return name + ` - ` + path;
}

function renderSessionSubtitle(session) {
  let title = Stdlib_Option.getOr(session.title, "(untitled)");
  let updatedAt = Stdlib_Option.getOr(session.updatedAt, "unknown-updated-time");
  return title + ` - ` + updatedAt;
}

function renderSessionStatus(status) {
  if (status !== undefined) {
    if (status === "running") {
      return "running";
    } else {
      return "idle";
    }
  } else {
    return "unknown";
  }
}

function renderMessageRole(role) {
  if (role === undefined) {
    return "Message";
  }
  if (typeof role === "object") {
    return role._0;
  }
  switch (role) {
    case "UserRole" :
      return "User";
    case "AssistantRole" :
      return "Assistant";
    case "ToolRole" :
      return "Tool";
    case "SystemRole" :
      return "System";
  }
}

function messageRoleClass(role) {
  if (role === undefined) {
    return "chatUnknown";
  }
  if (typeof role === "object") {
    return "chatUnknown";
  }
  switch (role) {
    case "UserRole" :
      return "chatUser";
    case "AssistantRole" :
      return "chatAssistant";
    case "ToolRole" :
      return "chatTool";
    case "SystemRole" :
      return "chatSystem";
  }
}

function renderTrackedPartFragment(part) {
  let match = part.text.trim();
  if (match === "") {
    if (part.streamedChars > 0) {
      return `[streaming ` + part.streamedChars.toString() + ` chars]`;
    } else {
      return "";
    }
  } else {
    return part.text;
  }
}

function combineTrackedPartText(parts) {
  return Stdlib_Array.reduce(parts, "", (combined, part) => {
    let fragment = renderTrackedPartFragment(part);
    if (fragment === "") {
      return combined;
    } else if (combined === "") {
      return fragment;
    } else {
      return combined + `\n` + fragment;
    }
  });
}

function reverseItems(items) {
  return Stdlib_Array.reduce(items, [], (acc, item) => [item].concat(acc));
}

function countRunningSessions(items) {
  return Stdlib_Array.reduce(items, 0, (count, item) => {
    let match = item.status;
    if (match === "running") {
      return count + 1 | 0;
    } else {
      return count;
    }
  });
}

function findSessionStatus(items, sessionId) {
  return Stdlib_Array.reduce(items, undefined, (found, item) => {
    if (found !== undefined) {
      return found;
    } else if (item.id === sessionId) {
      return item.status;
    } else {
      return;
    }
  });
}

function countTrackedQueueRequests(items, sessionId, queue) {
  return Stdlib_Array.reduce(items, 0, (count, item) => {
    if (item.queue === queue && item.sessionId === sessionId) {
      return count + 1 | 0;
    } else {
      return count;
    }
  });
}

function trackedTodoCountForSession(items, sessionId) {
  return Stdlib_Option.getOr(Stdlib_Array.findMap(items, item => {
    if (item.sessionId === sessionId) {
      return item.todos.length;
    }
  }), 0);
}

function trackedDiffFileCountForSession(items, sessionId) {
  return Stdlib_Option.getOr(Stdlib_Array.findMap(items, item => {
    if (item.sessionId === sessionId) {
      return item.diff.length;
    }
  }), 0);
}

function upsertTrackedMessage(items, message) {
  let exists = items.some(item => {
    if (item.sessionId === message.sessionId) {
      return item.message.id === message.id;
    } else {
      return false;
    }
  });
  if (exists) {
    return items.map(item => {
      if (item.sessionId === message.sessionId && item.message.id === message.id) {
        return {
          sessionId: message.sessionId,
          message: message
        };
      } else {
        return item;
      }
    });
  } else {
    return Belt_Array.concatMany([
      [{
          sessionId: message.sessionId,
          message: message
        }],
      items
    ]);
  }
}

function upsertTrackedPart(items, part) {
  let exists = items.some(item => {
    if (item.sessionId === part.sessionId && item.messageId === part.messageId) {
      return item.part.id === part.id;
    } else {
      return false;
    }
  });
  if (exists) {
    return items.map(item => {
      if (item.sessionId === part.sessionId && item.messageId === part.messageId && item.part.id === part.id) {
        return {
          sessionId: item.sessionId,
          messageId: item.messageId,
          part: part,
          streamedChars: item.streamedChars,
          text: item.text
        };
      } else {
        return item;
      }
    });
  } else {
    return Belt_Array.concatMany([
      [{
          sessionId: part.sessionId,
          messageId: part.messageId,
          part: part,
          streamedChars: 0,
          text: ""
        }],
      items
    ]);
  }
}

function sessionStatusFromEventKind(status) {
  if (typeof status !== "object" && status === "Idle") {
    return "idle";
  } else {
    return "running";
  }
}

function normalizeQueryText(value) {
  let trimmed = value.trim();
  if (trimmed === "") {
    return;
  } else {
    return trimmed;
  }
}

function normalizeQueryLimit(value) {
  let limit = Stdlib_Int.fromString(value.trim());
  if (limit !== undefined && limit > 0) {
    return limit;
  }
}

function buildSessionQuery(directoryText, searchText, limitText) {
  let directory = normalizeQueryText(directoryText);
  let search = normalizeQueryText(searchText);
  let limit = normalizeQueryLimit(limitText);
  if (directory === undefined && search === undefined && limit === undefined) {
    return;
  } else {
    return {
      directory: directory,
      search: search,
      limit: limit
    };
  }
}

function renderSessionQuery(query) {
  if (query === undefined) {
    return "No filters";
  }
  let limit = query.limit;
  let directoryText = Stdlib_Option.getOr(query.directory, "any-dir");
  let searchText = Stdlib_Option.getOr(query.search, "any-text");
  let limitText = limit !== undefined ? limit.toString() : "default";
  return `dir=` + directoryText + `, search=` + searchText + `, limit=` + limitText;
}

function routeDirectoryForSessions(query) {
  if (query === undefined) {
    return "workspace";
  }
  let directory = query.directory;
  if (directory !== undefined) {
    return directory;
  } else {
    return "workspace";
  }
}

let composerModelStorageKey = "opencode.settings.dat:composerModelOverride";

let customModelSentinel = "__custom__";

let modelPresetOptions = [
  [
    "anthropic/claude-sonnet-4-5",
    "Claude Sonnet 4.5"
  ],
  [
    "anthropic/claude-opus-4-1",
    "Claude Opus 4.1"
  ],
  [
    "openai/gpt-5",
    "GPT-5"
  ],
  [
    "openai/gpt-5-mini",
    "GPT-5 Mini"
  ],
  [
    "openai/gpt-5.3-codex",
    "GPT-5.3 Codex"
  ]
];

function isKnownModelPreset(value) {
  return modelPresetOptions.some(param => param[0] === value);
}

function getStoredComposerModel() {
  try {
    let storage = window.localStorage;
    if (storage !== undefined) {
      return Stdlib_Option.flatMap(Primitive_option.fromNullable(Primitive_option.valFromOption(storage).getItem(composerModelStorageKey)), normalizeQueryText);
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function rememberFirstError(firstError, message) {
  if (Stdlib_Option.isNone(firstError.contents)) {
    firstError.contents = message;
    return;
  }
}

function syncRequestState(setState, firstError) {
  if (firstError !== undefined) {
    return setState(param => ({
      TAG: "Failed",
      _0: firstError
    }));
  } else {
    return setState(param => "Ready");
  }
}

function renderObservedEvent(event) {
  let sessionId = event.sessionId;
  let sessionSuffix = sessionId !== undefined ? ` [` + sessionId + `]` : "";
  return OpencodeEvent.kindTagToString(event.kind) + sessionSuffix + ` -> ` + OpencodeEvent.refreshPathToString(event.refreshPath);
}

function App(props) {
  let platformValue = PlatformContext.web(undefined, undefined);
  let value = platformValue.getDefaultServerUrl();
  let fallbackServer;
  if (value !== undefined) {
    let trimmed = value.trim();
    fallbackServer = trimmed === "" ? "http://localhost:4096" : trimmed;
  } else {
    fallbackServer = "http://localhost:4096";
  }
  let value$1 = props.defaultServer.trim();
  let initialServer = value$1 === "" ? fallbackServer : value$1;
  let match = SolidJs.createSignal(initialServer);
  let setActiveServer = match[1];
  let activeServer = match[0];
  let match$1 = SolidJs.createSignal(initialServer);
  let setServerDraft = match$1[1];
  let serverDraft = match$1[0];
  let match$2 = SolidJs.createSignal("Loading /global/health ...");
  let setHealthText = match$2[1];
  let healthText = match$2[0];
  let match$3 = SolidJs.createSignal("Loading /project/current ...");
  let setProjectText = match$3[1];
  let projectText = match$3[0];
  let match$4 = SolidJs.createSignal([]);
  let setProjects = match$4[1];
  let projects = match$4[0];
  let match$5 = SolidJs.createSignal([]);
  let setSessions = match$5[1];
  let sessions = match$5[0];
  let match$6 = SolidJs.createSignal([]);
  let setSessionStatuses = match$6[1];
  let sessionStatuses = match$6[0];
  let match$7 = SolidJs.createSignal("");
  let setSessionDirectoryDraft = match$7[1];
  let sessionDirectoryDraft = match$7[0];
  let match$8 = SolidJs.createSignal("");
  let setSessionSearchDraft = match$8[1];
  let sessionSearchDraft = match$8[0];
  let match$9 = SolidJs.createSignal("");
  let setSessionLimitDraft = match$9[1];
  let sessionLimitDraft = match$9[0];
  let match$10 = SolidJs.createSignal(undefined);
  let setSessionQuery = match$10[1];
  let sessionQuery = match$10[0];
  let match$11 = SolidJs.createSignal(undefined);
  let setFocusedSessionId = match$11[1];
  let focusedSessionId = match$11[0];
  let match$12 = SolidJs.createSignal(undefined);
  let setFocusedSession = match$12[1];
  let focusedSession = match$12[0];
  let match$13 = SolidJs.createSignal(undefined);
  let setFocusedSessionError = match$13[1];
  let focusedSessionError = match$13[0];
  let match$14 = SolidJs.createSignal([]);
  let setTrackedQueueRequests = match$14[1];
  let trackedQueueRequests = match$14[0];
  let match$15 = SolidJs.createSignal([]);
  let setTrackedTodos = match$15[1];
  let trackedTodos = match$15[0];
  let match$16 = SolidJs.createSignal([]);
  let setTrackedDiffs = match$16[1];
  let trackedDiffs = match$16[0];
  let match$17 = SolidJs.createSignal([]);
  let setTrackedMessages = match$17[1];
  let trackedMessages = match$17[0];
  let match$18 = SolidJs.createSignal([]);
  let setTrackedParts = match$18[1];
  let trackedParts = match$18[0];
  let match$19 = SolidJs.createSignal([]);
  let setRecentEvents = match$19[1];
  let recentEvents = match$19[0];
  let match$20 = SolidJs.createSignal("");
  let setComposerDraft = match$20[1];
  let composerDraft = match$20[0];
  let initialComposerModel = Stdlib_Option.getOr(getStoredComposerModel(), "");
  let match$21 = SolidJs.createSignal(initialComposerModel);
  let setComposerModelDraft = match$21[1];
  let composerModelDraft = match$21[0];
  let value$2 = normalizeQueryText(initialComposerModel);
  let match$22 = SolidJs.createSignal(value$2 !== undefined ? !isKnownModelPreset(value$2) : false);
  let setComposerCustomModelEnabled = match$22[1];
  let composerCustomModelEnabled = match$22[0];
  let match$23 = SolidJs.createSignal(undefined);
  let setComposerError = match$23[1];
  let composerError = match$23[0];
  let match$24 = SolidJs.createSignal(false);
  let setIsComposerSending = match$24[1];
  let isComposerSending = match$24[0];
  let match$25 = SolidJs.createSignal("disconnected");
  let setStreamStatus = match$25[1];
  let streamStatus = match$25[0];
  let match$26 = SolidJs.createSignal(undefined);
  let setStreamError = match$26[1];
  let streamError = match$26[0];
  let match$27 = SolidJs.createSignal(0);
  let setStreamEventCount = match$27[1];
  let streamEventCount = match$27[0];
  let match$28 = SolidJs.createSignal(undefined);
  let setStreamLastEventKind = match$28[1];
  let streamLastEventKind = match$28[0];
  let match$29 = SolidJs.createSignal("Loading");
  let setState = match$29[1];
  let state = match$29[0];
  let client = SolidJs.createMemo(() => OpencodeClient.make(activeServer(), undefined, undefined, undefined));
  let loadHealthData = async firstError => {
    let sdk = client();
    let health = await OpencodeClient.health(sdk);
    if (health.TAG === "Ok") {
      let health$1 = health._0;
      let version = health$1.version;
      let versionSuffix = version !== undefined ? ` (version ` + version + `)` : "";
      return setHealthText(param => health$1.status + versionSuffix);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(health._0));
    return setHealthText(param => "Unavailable");
  };
  let loadProjectData = async firstError => {
    let sdk = client();
    let project = await OpencodeClient.projectCurrent(sdk);
    if (project.TAG === "Ok") {
      let project$1 = project._0;
      setProjectText(param => {
        if (project$1 === undefined) {
          return "No active project returned by /project/current";
        }
        let id = Stdlib_Option.getOr(project$1.id, "unknown-id");
        let name = Stdlib_Option.getOr(project$1.name, "unnamed");
        let path = Stdlib_Option.getOr(project$1.path, "unknown-path");
        return name + ` (` + id + `) at ` + path;
      });
    } else {
      rememberFirstError(firstError, OpencodeClient.errorToString(project._0));
      setProjectText(param => "Unavailable");
    }
    let items = await OpencodeClient.projects(sdk);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setProjects(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setProjects(param => []);
  };
  let loadSessionListData = async (query, firstError) => {
    let sdk = client();
    let items = await OpencodeClient.sessions(sdk, query, undefined);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setSessions(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setSessions(param => []);
  };
  let loadSessionStatusData = async (query, firstError) => {
    let sdk = client();
    let items = await OpencodeClient.sessionStatuses(sdk, query, undefined);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setSessionStatuses(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setSessionStatuses(param => []);
  };
  let loadSessionData = async (query, firstError) => {
    await loadSessionListData(query, firstError);
    return await loadSessionStatusData(query, firstError);
  };
  SolidJs.createEffect(() => {
    let value = composerModelDraft();
    try {
      let storage = window.localStorage;
      if (storage === undefined) {
        return;
      }
      let storage$1 = Primitive_option.valFromOption(storage);
      let trimmed = normalizeQueryText(value);
      if (trimmed !== undefined) {
        storage$1.setItem(composerModelStorageKey, trimmed);
      } else {
        storage$1.removeItem(composerModelStorageKey);
      }
      return;
    } catch (exn) {
      return;
    }
  });
  let hydrateSessionConversationById = async sessionId => {
    let sdk = client();
    let messages = await OpencodeClient.sessionMessages(sdk, sessionId);
    if (messages.TAG !== "Ok") {
      return;
    }
    let messages$1 = messages._0;
    let hydratedMessages = messages$1.map(message => {
      let snapshot_id = message.id;
      let snapshot_sessionId = message.sessionId;
      let snapshot_role = message.role;
      let snapshot = {
        id: snapshot_id,
        sessionId: snapshot_sessionId,
        role: snapshot_role
      };
      return {
        sessionId: message.sessionId,
        message: snapshot
      };
    });
    let hydratedParts = Stdlib_Array.reduce(messages$1, [], (partsAcc, message) => Stdlib_Array.reduce(message.parts, partsAcc, (innerAcc, part) => {
      let snapshot_id = part.id;
      let snapshot_sessionId = part.sessionId;
      let snapshot_messageId = part.messageId;
      let snapshot_partType = part.partType;
      let snapshot = {
        id: snapshot_id,
        sessionId: snapshot_sessionId,
        messageId: snapshot_messageId,
        partType: snapshot_partType
      };
      return innerAcc.concat([{
          sessionId: part.sessionId,
          messageId: part.messageId,
          part: snapshot,
          streamedChars: part.text.length,
          text: part.text
        }]);
    }));
    setTrackedMessages(items => {
      let sessionItems = items.filter(item => item.sessionId === sessionId);
      let remaining = items.filter(item => item.sessionId !== sessionId);
      let mergedSessionItems = Stdlib_Array.reduce(hydratedMessages, sessionItems, (acc, hydrated) => upsertTrackedMessage(acc, hydrated.message));
      return mergedSessionItems.concat(remaining);
    });
    return setTrackedParts(items => {
      let sessionItems = items.filter(item => item.sessionId === sessionId);
      let remaining = items.filter(item => item.sessionId !== sessionId);
      let mergedSessionItems = Stdlib_Array.reduce(hydratedParts, sessionItems, (acc, hydratedPart) => {
        let withPart = upsertTrackedPart(acc, hydratedPart.part);
        return withPart.map(item => {
          if (item.sessionId === hydratedPart.sessionId && item.messageId === hydratedPart.messageId && item.part.id === hydratedPart.part.id) {
            return {
              sessionId: item.sessionId,
              messageId: item.messageId,
              part: item.part,
              streamedChars: hydratedPart.streamedChars,
              text: hydratedPart.text !== "" ? hydratedPart.text : item.text
            };
          } else {
            return item;
          }
        });
      });
      return mergedSessionItems.concat(remaining);
    });
  };
  let loadFocusedSessionById = async sessionId => {
    let sdk = client();
    let found = await OpencodeClient.sessionById(sdk, sessionId);
    if (found.TAG === "Ok") {
      let found$1 = found._0;
      setFocusedSession(param => found$1);
      setFocusedSessionError(param => {});
      await hydrateSessionConversationById(sessionId);
      return;
    }
    let error = found._0;
    setFocusedSession(param => {});
    return setFocusedSessionError(param => OpencodeClient.errorToString(error));
  };
  let appendObservedEvent = event => setRecentEvents(events => {
    let capped = Belt_Array.concatMany([
      [event],
      events
    ]);
    let seen = {
      contents: 0
    };
    return capped.filter(param => {
      let keep = seen.contents < 60;
      seen.contents = seen.contents + 1 | 0;
      return keep;
    });
  });
  let applySessionStatusChanged = payload => {
    let nextStatus = sessionStatusFromEventKind(payload.status);
    let nextItem_id = payload.sessionId;
    let nextItem = {
      id: nextItem_id,
      status: nextStatus
    };
    setSessionStatuses(items => {
      let hasExisting = items.some(item => item.id === payload.sessionId);
      let updated = items.map(item => {
        if (item.id === payload.sessionId) {
          return nextItem;
        } else {
          return item;
        }
      });
      if (hasExisting) {
        return updated;
      } else {
        return Belt_Array.concatMany([
          [nextItem],
          updated
        ]);
      }
    });
  };
  let applySessionDeleted = payload => {
    setSessions(items => items.filter(item => item.id !== payload.sessionId));
    setSessionStatuses(items => items.filter(item => item.id !== payload.sessionId));
    setTrackedQueueRequests(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedTodos(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedDiffs(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedMessages(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedParts(items => items.filter(item => item.sessionId !== payload.sessionId));
    let activeSessionId = focusedSessionId();
    if (activeSessionId !== undefined && activeSessionId === payload.sessionId) {
      setFocusedSession(param => {});
      return setFocusedSessionError(param => {});
    }
  };
  let applySessionScoped = payload => {
    let match = OpencodeEvent.queueRequestMutationFromScoped(payload);
    if (match !== undefined) {
      if (match.TAG === "UpsertQueueRequest") {
        let match$1 = match._0;
        let requestId = match$1.requestId;
        let sessionId = match$1.sessionId;
        let queue = match$1.queue;
        setTrackedQueueRequests(items => {
          let exists = items.some(item => {
            if (item.queue === queue && item.sessionId === sessionId) {
              return item.requestId === requestId;
            } else {
              return false;
            }
          });
          if (exists) {
            return items;
          } else {
            return Belt_Array.concatMany([
              [{
                  queue: queue,
                  sessionId: sessionId,
                  requestId: requestId
                }],
              items
            ]);
          }
        });
      } else {
        let match$2 = match._0;
        let requestId$1 = match$2.requestId;
        let sessionId$1 = match$2.sessionId;
        let queue$1 = match$2.queue;
        setTrackedQueueRequests(items => items.filter(item => item.queue !== queue$1 || item.sessionId !== sessionId$1 || item.requestId !== requestId$1));
      }
    }
    let match$3 = OpencodeEvent.todoUpdatedFromScoped(payload);
    if (match$3 !== undefined) {
      let todos = match$3.todos;
      let sessionId$2 = match$3.sessionId;
      setTrackedTodos(items => {
        let remaining = items.filter(item => item.sessionId !== sessionId$2);
        return Belt_Array.concatMany([
          [{
              sessionId: sessionId$2,
              todos: todos
            }],
          remaining
        ]);
      });
    }
    let match$4 = OpencodeEvent.sessionDiffFromScoped(payload);
    if (match$4 !== undefined) {
      let diff = match$4.diff;
      let sessionId$3 = match$4.sessionId;
      setTrackedDiffs(items => {
        let remaining = items.filter(item => item.sessionId !== sessionId$3);
        return Belt_Array.concatMany([
          [{
              sessionId: sessionId$3,
              diff: diff
            }],
          remaining
        ]);
      });
    }
    let match$5 = OpencodeEvent.messageMutationFromScoped(payload);
    if (match$5 === undefined) {
      return;
    }
    switch (match$5.TAG) {
      case "UpsertMessage" :
        let message = match$5._0.message;
        return setTrackedMessages(items => upsertTrackedMessage(items, message));
      case "RemoveMessage" :
        let match$6 = match$5._0;
        let messageId = match$6.messageId;
        let sessionId$4 = match$6.sessionId;
        setTrackedMessages(items => items.filter(item => item.sessionId !== sessionId$4 || item.message.id !== messageId));
        return setTrackedParts(items => items.filter(part => part.sessionId !== sessionId$4 || part.messageId !== messageId));
      case "UpsertPart" :
        let part = match$5._0.part;
        let inferredMessage_id = part.messageId;
        let inferredMessage_sessionId = part.sessionId;
        let inferredMessage = {
          id: inferredMessage_id,
          sessionId: inferredMessage_sessionId,
          role: undefined
        };
        setTrackedMessages(items => upsertTrackedMessage(items, inferredMessage));
        return setTrackedParts(items => upsertTrackedPart(items, part));
      case "RemovePart" :
        let match$7 = match$5._0;
        let partId = match$7.partId;
        let messageId$1 = match$7.messageId;
        let sessionId$5 = match$7.sessionId;
        return setTrackedParts(items => items.filter(part => {
          if (sessionId$5 !== undefined) {
            return part.sessionId !== sessionId$5 || part.messageId !== messageId$1 || part.part.id !== partId;
          } else {
            return part.messageId !== messageId$1 || part.part.id !== partId;
          }
        }));
      case "AppendPartDelta" :
        let match$8 = match$5._0;
        let deltaText = match$8.deltaText;
        let deltaChars = match$8.deltaChars;
        let partId$1 = match$8.partId;
        let messageId$2 = match$8.messageId;
        let sessionId$6 = match$8.sessionId;
        return setTrackedParts(items => {
          let appendedText = Stdlib_Option.getOr(deltaText, "");
          let hasAppendedText = appendedText !== "";
          if (deltaChars <= 0 && !hasAppendedText) {
            return items;
          }
          let hasMatch = items.some(part => {
            if (sessionId$6 !== undefined) {
              if (part.sessionId === sessionId$6 && part.messageId === messageId$2) {
                return part.part.id === partId$1;
              } else {
                return false;
              }
            } else if (part.messageId === messageId$2) {
              return part.part.id === partId$1;
            } else {
              return false;
            }
          });
          if (hasMatch) {
            return items.map(part => {
              if (sessionId$6 !== undefined) {
                if (part.sessionId === sessionId$6 && part.messageId === messageId$2 && part.part.id === partId$1) {
                  return {
                    sessionId: part.sessionId,
                    messageId: part.messageId,
                    part: part.part,
                    streamedChars: part.streamedChars + deltaChars | 0,
                    text: hasAppendedText ? part.text + appendedText : part.text
                  };
                } else {
                  return part;
                }
              } else if (part.messageId === messageId$2 && part.part.id === partId$1) {
                return {
                  sessionId: part.sessionId,
                  messageId: part.messageId,
                  part: part.part,
                  streamedChars: part.streamedChars + deltaChars | 0,
                  text: hasAppendedText ? part.text + appendedText : part.text
                };
              } else {
                return part;
              }
            });
          } else if (sessionId$6 !== undefined) {
            return Belt_Array.concatMany([
              [{
                  sessionId: sessionId$6,
                  messageId: messageId$2,
                  part: {
                    id: partId$1,
                    sessionId: sessionId$6,
                    messageId: messageId$2,
                    partType: undefined
                  },
                  streamedChars: deltaChars,
                  text: appendedText
                }],
              items
            ]);
          } else {
            return items;
          }
        });
    }
  };
  let refreshData = async query => {
    setState(param => "Loading");
    let firstError = {
      contents: undefined
    };
    await loadHealthData(firstError);
    await loadProjectData(firstError);
    await loadSessionData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshProjectSlice = async () => {
    let firstError = {
      contents: undefined
    };
    await loadProjectData(firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionListSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionListData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionStatusesSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionStatusData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let applyServer = () => {
    let nextServer = serverDraft().trim();
    let resolvedServer = nextServer === "" ? initialServer : nextServer;
    setActiveServer(param => resolvedServer);
    setServerDraft(param => resolvedServer);
    platformValue.setDefaultServerUrl(resolvedServer);
    refreshData(sessionQuery());
  };
  let resetServer = () => {
    setServerDraft(param => initialServer);
    setActiveServer(param => initialServer);
    platformValue.setDefaultServerUrl(initialServer);
    refreshData(sessionQuery());
  };
  let refreshFromContext = () => {
    refreshData(sessionQuery());
  };
  let applySessionFilters = () => {
    let nextQuery = buildSessionQuery(sessionDirectoryDraft(), sessionSearchDraft(), sessionLimitDraft());
    setSessionQuery(param => nextQuery);
    refreshSessionSlice(nextQuery);
  };
  let clearSessionFilters = () => {
    setSessionDirectoryDraft(param => "");
    setSessionSearchDraft(param => "");
    setSessionLimitDraft(param => "");
    setSessionQuery(param => {});
    refreshSessionSlice(undefined);
  };
  let serverValue_setServerDraft = value => setServerDraft(param => value);
  let serverValue = {
    activeServer: activeServer,
    serverDraft: serverDraft,
    setServerDraft: serverValue_setServerDraft,
    applyServer: applyServer,
    resetServer: resetServer,
    refresh: refreshFromContext
  };
  let sdkValue = {
    client: client
  };
  SolidJs.onMount(() => {
    refreshData(sessionQuery());
  });
  let rootLayout = props => {
    let isRouting = Router.useIsRouting();
    let location = Router.useLocation();
    let message = streamError();
    return AppProviders.routerRoot(<main
      className={"page"}
    >
      <header
        className={"hero"}
      >
        <h1>
          {"OpenCode Web Reimplement (ReScript)"}
        </h1>
        <p>
          {"Client SDK against the existing OpenCode server"}
        </p>
      </header>
      <nav
        className={"navBar"}
      >
        <Router.A
          href={"/"}
          inactiveClass={"navItem"}
          activeClass={"navItem active"}
        >
          {"Overview"}
        </Router.A>
        <Router.A
          href={"/sessions"}
          inactiveClass={"navItem"}
          activeClass={"navItem active"}
        >
          {"Sessions"}
        </Router.A>
        <Router.A
          href={"/workspace/session"}
          inactiveClass={"navItem"}
          activeClass={"navItem active"}
        >
          {"Workspace"}
        </Router.A>
      </nav>
      <div
        className={"actionBar"}
      >
        <button
          className={"ghostBtn"}
          onClick={param => platformValue.back()}
        >
          {"Back"}
        </button>
        <button
          className={"ghostBtn"}
          onClick={param => platformValue.forward()}
        >
          {"Forward"}
        </button>
        <button
          className={"ghostBtn"}
          onClick={param => platformValue.restart()}
        >
          {"Reload"}
        </button>
        <button
          className={"ghostBtn"}
          onClick={param => platformValue.openLink("https://github.com/anomalyco/opencode")}
        >
          {"Open Upstream"}
        </button>
      </div>
      <section
        className={"panel statusPanel"}
      >
        <div
          className={"statusLine"}
        >
          <h2>
            {"Server"}
          </h2>
          <span
            className={isRouting() ? "routeState moving" : "routeState"}
          >
            {isRouting() ? "routing" : "idle"}
          </span>
        </div>
        <code>
          {activeServer()}
        </code>
        <p
          className={"statusPath"}
        >
          {`Path: ` + location.pathname}
        </p>
        <p
          className={"streamMeta"}
        >
          {`Stream: ` + streamStatus() + ` (events ` + streamEventCount().toString() + `)`}
        </p>
        {message !== undefined ? <p
            className={"errorText"}
          >
            {`Stream error: ` + message}
          </p> : <span />}
        <p
          className={"streamMeta"}
        >
          {`Last event: ` + Stdlib_Option.getOr(streamLastEventKind(), "none")}
        </p>
        <div
          className={"serverForm"}
        >
          <input
            id={"server-url-input"}
            placeholder={"https://your-opencode-server"}
            type={"text"}
            value={serverDraft()}
            onInput={event => serverValue_setServerDraft(event.target.value)}
          />
          <button
            className={"refreshBtn"}
            id={"server-apply-btn"}
            onClick={param => applyServer()}
          >
            {"Apply"}
          </button>
          <button
            className={"ghostBtn"}
            id={"server-reset-btn"}
            onClick={param => resetServer()}
          >
            {"Reset"}
          </button>
          <button
            className={"ghostBtn"}
            id={"server-refresh-btn"}
            onClick={param => {
              refreshData(sessionQuery());
            }}
          >
            {"Refresh"}
          </button>
        </div>
      </section>
      {props.children}
    </main>);
  };
  let overviewPage = param => {
    let sync = GlobalSyncContext.use();
    let message = state();
    let tmp;
    tmp = typeof message !== "object" ? (
        message === "Loading" ? <p
            className={"loadingText"}
          >
            {"Loading ..."}
          </p> : <p
            className={"okText"}
          >
            {"Data loaded from server"}
          </p>
      ) : <p
        className={"errorText"}
      >
        {`Request failed: ` + message._0}
      </p>;
    return <section
      className={"panel"}
    >
      <h2>
        {"Overview"}
      </h2>
      <ul
        className={"summaryList"}
      >
        <li>
          <strong>
            {"Health"}
          </strong>
          <span>
            {healthText()}
          </span>
        </li>
        <li>
          <strong>
            {"Project"}
          </strong>
          <span>
            {projectText()}
          </span>
        </li>
        <li>
          <strong>
            {"Sessions"}
          </strong>
          <span>
            {sessions().length.toString()}
          </span>
        </li>
        <li>
          <strong>
            {"Projects"}
          </strong>
          <span>
            {projects().length.toString()}
          </span>
        </li>
        <li>
          <strong>
            {"Last Event"}
          </strong>
          <span>
            {Stdlib_Option.getOr(sync.lastEventKind(), "none")}
          </span>
        </li>
        <li>
          <strong>
            {"Running Sessions"}
          </strong>
          <span>
            {countRunningSessions(sessionStatuses()).toString()}
          </span>
        </li>
      </ul>
      <ul
        className={"projectList"}
      >
        {projects().map((project, index) => <li
          className={"projectRow"}
        >
          <span
            className={"eventIndex"}
          >
            {`#` + index.toString()}
          </span>
          <span>
            {renderProjectLabel(project)}
          </span>
        </li>)}
      </ul>
      {tmp}
    </section>;
  };
  let sessionsPage = param => <section
    className={"panel"}
  >
    <h2>
      {"Sessions"}
    </h2>
    <div
      className={"queryGrid"}
    >
      <label>
        <span>
          {"Directory"}
        </span>
        <input
          id={"sessions-directory-filter"}
          placeholder={"workspace"}
          type={"text"}
          value={sessionDirectoryDraft()}
          onInput={event => {
            let value = event.target.value;
            setSessionDirectoryDraft(param => value);
          }}
        />
      </label>
      <label>
        <span>
          {"Search"}
        </span>
        <input
          id={"sessions-search-filter"}
          placeholder={"title text"}
          type={"text"}
          value={sessionSearchDraft()}
          onInput={event => {
            let value = event.target.value;
            setSessionSearchDraft(param => value);
          }}
        />
      </label>
      <label>
        <span>
          {"Limit"}
        </span>
        <input
          id={"sessions-limit-filter"}
          min={"1"}
          placeholder={"25"}
          type={"number"}
          value={sessionLimitDraft()}
          onInput={event => {
            let value = event.target.value;
            setSessionLimitDraft(param => value);
          }}
        />
      </label>
    </div>
    <div
      className={"queryActions"}
    >
      <button
        className={"refreshBtn"}
        id={"sessions-apply-filters-btn"}
        onClick={param => applySessionFilters()}
      >
        {"Apply filters"}
      </button>
      <button
        className={"ghostBtn"}
        id={"sessions-clear-filters-btn"}
        onClick={param => clearSessionFilters()}
      >
        {"Clear"}
      </button>
      <span
        className={"streamMeta"}
      >
        {`Active query: ` + renderSessionQuery(sessionQuery())}
      </span>
    </div>
    {sessions().length !== 0 ? <ul
        className={"eventList"}
      >
        {sessions().map((session, index) => {
          let status = findSessionStatus(sessionStatuses(), session.id);
          let routeDirectory = routeDirectoryForSessions(sessionQuery());
          return <li
            className={"eventRow"}
          >
            <span
              className={"eventIndex"}
            >
              {`#` + index.toString()}
            </span>
            <span
              className={"eventKind"}
            >
              {session.id}
            </span>
            <span
              className={"sessionMeta"}
            >
              {renderSessionSubtitle(session)}
            </span>
            <span
              className={Primitive_object.equal(status, "running") ? "badge hot" : "badge"}
            >
              {renderSessionStatus(status)}
            </span>
            <Router.A
              href={`/` + routeDirectory + `/session/` + session.id}
              inactiveClass={"inlineLink"}
              activeClass={"inlineLink"}
            >
              {"open"}
            </Router.A>
          </li>;
        })}
      </ul> : <p
        className={"loadingText"}
      >
        {"No sessions matched the current filters"}
      </p>}
  </section>;
  let dirIndexPage = param => {
    let params = Router.useParams();
    let dir = Stdlib_Option.getOr(params["dir"], "workspace");
    return <Router.Navigate
      href={`/` + dir + `/session`}
    />;
  };
  let sessionPage = param => {
    let params = Router.useParams();
    let dir = Stdlib_Option.getOr(params["dir"], "workspace");
    let sessionId = Stdlib_Option.getOr(params["id"], "latest");
    SolidJs.createEffect(() => {
      let id = params["id"];
      if (id !== undefined) {
        setFocusedSessionId(param => id);
        setComposerError(param => {});
        loadFocusedSessionById(id);
        return;
      } else {
        setFocusedSessionId(param => {});
        setFocusedSession(param => {});
        setFocusedSessionError(param => {});
        setComposerDraft(param => "");
        return setComposerError(param => {});
      }
    });
    let selected = Stdlib_Array.reduce(sessions(), undefined, (found, item) => {
      if (found !== undefined) {
        return found;
      } else if (item.id === sessionId) {
        return item;
      } else {
        return;
      }
    });
    let session = focusedSession();
    let focusedMatch = session !== undefined && (sessionId === "latest" || session.id === sessionId) ? session : undefined;
    let hasSessionMetadata = Stdlib_Option.isSome(selected) || Stdlib_Option.isSome(focusedMatch);
    let displayedSession = selected !== undefined ? selected : (
        focusedMatch !== undefined ? focusedMatch : (
            sessionId === "latest" ? undefined : ({
                id: sessionId,
                title: undefined,
                updatedAt: undefined
              })
          )
      );
    let counterSessionId = sessionId === "latest" && displayedSession !== undefined ? displayedSession.id : sessionId;
    let pendingPermissionCount = () => countTrackedQueueRequests(trackedQueueRequests(), counterSessionId, "permission");
    let pendingQuestionCount = () => countTrackedQueueRequests(trackedQueueRequests(), counterSessionId, "question");
    let trackedSessionMessages = () => trackedMessages().filter(item => item.sessionId === counterSessionId);
    let trackedSessionParts = () => trackedParts().filter(item => item.sessionId === counterSessionId);
    let streamedCharCount = () => Stdlib_Array.reduce(trackedSessionParts(), 0, (count, item) => count + item.streamedChars | 0);
    let hasSessionActivity = () => {
      if (Stdlib_Option.isSome(findSessionStatus(sessionStatuses(), counterSessionId)) || pendingPermissionCount() > 0 || pendingQuestionCount() > 0 || trackedTodoCountForSession(trackedTodos(), counterSessionId) > 0 || trackedDiffFileCountForSession(trackedDiffs(), counterSessionId) > 0 || trackedSessionMessages().length !== 0 || trackedSessionParts().length !== 0) {
        return true;
      } else {
        return streamedCharCount() > 0;
      }
    };
    let effectiveRouteStatus = () => {
      let status = findSessionStatus(sessionStatuses(), counterSessionId);
      if (status !== undefined) {
        return status;
      } else if (hasSessionActivity()) {
        return "running";
      } else {
        return;
      }
    };
    let conversationRows = () => {
      let sessionParts = trackedSessionParts();
      let knownMessages = trackedSessionMessages().map(item => item.message);
      let mergedMessages = Stdlib_Array.reduce(sessionParts, knownMessages, (messages, part) => {
        let exists = messages.some(message => message.id === part.messageId);
        if (exists) {
          return messages;
        }
        let inferredMessage_id = part.messageId;
        let inferredMessage_sessionId = part.sessionId;
        let inferredMessage = {
          id: inferredMessage_id,
          sessionId: inferredMessage_sessionId,
          role: undefined
        };
        return [inferredMessage].concat(messages);
      });
      return reverseItems(mergedMessages).map(message => {
        let messageParts = reverseItems(sessionParts.filter(part => part.messageId === message.id));
        let combinedText = combineTrackedPartText(messageParts);
        let match = combinedText.trim();
        let tmp = match === "" ? "[awaiting streamed content]" : combinedText;
        return {
          message: message,
          text: tmp,
          partCount: messageParts.length
        };
      }).filter(row => {
        if (row.partCount > 0) {
          return true;
        } else {
          return row.message.role !== undefined;
        }
      });
    };
    let composerTargetSessionId = sessionId === "latest" && displayedSession !== undefined ? displayedSession.id : sessionId;
    let canSendComposer = composerTargetSessionId !== "" && composerTargetSessionId !== "latest";
    let sendComposer = async () => {
      let prompt = composerDraft().trim();
      if (prompt === "") {
        return;
      }
      if (!canSendComposer) {
        return setComposerError(param => "Select a concrete session before sending a prompt");
      }
      let localNonce = streamEventCount().toString() + `-` + trackedSessionParts().length.toString() + `-` + prompt.length.toString();
      let localMessageId = `local-user-message-` + composerTargetSessionId + `-` + localNonce;
      let localPartId = `local-user-part-` + localNonce;
      let optimisticMessage_role = "UserRole";
      let optimisticMessage = {
        id: localMessageId,
        sessionId: composerTargetSessionId,
        role: optimisticMessage_role
      };
      let optimisticPart_partType = "TextPart";
      let optimisticPart = {
        id: localPartId,
        sessionId: composerTargetSessionId,
        messageId: localMessageId,
        partType: optimisticPart_partType
      };
      setComposerError(param => {});
      setIsComposerSending(param => true);
      setTrackedMessages(items => upsertTrackedMessage(items, optimisticMessage));
      setTrackedParts(items => {
        let withPart = upsertTrackedPart(items, optimisticPart);
        return withPart.map(item => {
          if (item.sessionId !== composerTargetSessionId || item.messageId !== localMessageId || item.part.id !== localPartId) {
            return item;
          }
          let match = item.text;
          if (match === "") {
            return {
              sessionId: item.sessionId,
              messageId: item.messageId,
              part: item.part,
              streamedChars: prompt.length,
              text: prompt
            };
          } else {
            return item;
          }
        });
      });
      setComposerDraft(param => "");
      setFocusedSessionId(param => composerTargetSessionId);
      loadFocusedSessionById(composerTargetSessionId);
      refreshSessionSlice(sessionQuery());
      let model = normalizeQueryText(composerModelDraft());
      let error = await OpencodeClient.sendSessionTextMessage(client(), composerTargetSessionId, prompt, model);
      if (error.TAG !== "Ok") {
        let error$1 = error._0;
        setComposerError(param => `Send failed: ` + OpencodeClient.errorToString(error$1));
      }
      return setIsComposerSending(param => false);
    };
    let composerModelSelectValue = () => {
      if (composerCustomModelEnabled()) {
        return customModelSentinel;
      }
      let value = normalizeQueryText(composerModelDraft());
      if (value !== undefined) {
        if (isKnownModelPreset(value)) {
          return value;
        } else {
          return customModelSentinel;
        }
      } else {
        return "";
      }
    };
    let error = composerError();
    let error$1 = focusedSessionError();
    let sessionBody = <div
      className={"sessionBody"}
    >
      <div
        className={"sessionMainStack"}
      >
        <section
          className={"panel sessionHeaderPanel"}
        >
          <h2>
            {`Workspace ` + dir}
          </h2>
          <p
            className={"sessionRoute"}
          >
            {`Session Route ID: ` + sessionId}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Session Status: ` + renderSessionStatus(effectiveRouteStatus())}
          </p>
          {displayedSession !== undefined ? <p>
              {(
                hasSessionMetadata ? `Matched: ` + renderSessionSubtitle(displayedSession) : `Route session: ` + displayedSession.id + ` (metadata pending)`
              )}
            </p> : (
              hasSessionActivity() ? <p
                  className={"okText"}
                >
                  {"Session activity is flowing; metadata list is still syncing for this route."}
                </p> : <p
                  className={"loadingText"}
                >
                  {"No matching session in current list. Fetching from server may still be pending."}
                </p>
            )}
        </section>
        <section
          className={"panel sessionTimelinePanel"}
        >
          <h3>
            {"Timeline"}
          </h3>
          <p
            className={"sessionRoute"}
          >
            {"Recent sessions in current workspace scope"}
          </p>
          <ul
            className={"sessionMiniList"}
          >
            {sessions().map(item => <li
              className={item.id === sessionId ? "miniSessionRow active" : "miniSessionRow"}
            >
              <span
                className={"eventKind"}
              >
                {item.id}
              </span>
              <span
                className={"sessionMeta"}
              >
                {renderSessionSubtitle(item)}
              </span>
            </li>)}
          </ul>
        </section>
        <section
          className={"panel sessionComposerPanel"}
        >
          <h3>
            {"Composer"}
          </h3>
          <p
            className={"sessionRoute"}
          >
            {"Prompt dock for continuing the selected session"}
          </p>
          <div
            className={"composerModelRow"}
          >
            <p
              className={"sessionRoute"}
            >
              {"Model override (optional)"}
            </p>
            <select
              className={"composerModelSelect"}
              id={"composer-model-select"}
              value={composerModelSelectValue()}
              onInput={event => {
                let value = event.target.value;
                if (value === "") {
                  setComposerCustomModelEnabled(param => false);
                  return setComposerModelDraft(param => "");
                } else if (value === customModelSentinel) {
                  return setComposerCustomModelEnabled(param => true);
                } else {
                  setComposerCustomModelEnabled(param => false);
                  return setComposerModelDraft(param => value);
                }
              }}
            >
              <option
                value={""}
              >
                {"Default (session model)"}
              </option>
              {modelPresetOptions.map(param => <option
                value={param[0]}
              >
                {param[1]}
              </option>)}
              <option
                value={customModelSentinel}
              >
                {"Custom model..."}
              </option>
            </select>
            {composerCustomModelEnabled() ? <input
                className={"composerModelInput"}
                id={"composer-model-input"}
                placeholder={"e.g. anthropic/claude-sonnet-4-5"}
                value={composerModelDraft()}
                onInput={event => {
                  let value = event.target.value;
                  setComposerModelDraft(param => value);
                }}
              /> : <p
                className={"sessionRoute composerModelHint"}
              >
                {"Select a preset or use custom for a manual model id."}
              </p>}
          </div>
          <textarea
            className={"composerInput"}
            placeholder={"Ask OpenCode to continue this session..."}
            value={composerDraft()}
            onKeyDown={event => {
              let key = event.key;
              if (key !== "Enter" || event.shiftKey) {
                return;
              }
              event.preventDefault();
              let canTrigger = !(isComposerSending() || composerDraft().trim() === "" || !canSendComposer);
              if (canTrigger) {
                sendComposer();
                return;
              }
            }}
            onInput={event => {
              let value = event.target.value;
              setComposerDraft(param => value);
            }}
          />
          <div
            className={"queryActions"}
          >
            <button
              className={"refreshBtn"}
              id={"composer-send-btn"}
              disabled={isComposerSending() || composerDraft().trim() === "" || !canSendComposer}
              onClick={param => {
                sendComposer();
              }}
            >
              {isComposerSending() ? "Sending..." : "Send"}
            </button>
            <button
              className={"ghostBtn"}
              id={"composer-clear-btn"}
              disabled={isComposerSending() || composerDraft() === ""}
              onClick={param => {
                setComposerDraft(param => "");
                setComposerError(param => {});
              }}
            >
              {"Clear draft"}
            </button>
          </div>
          {error !== undefined ? <p
              className={"errorText"}
            >
              {error}
            </p> : <span />}
        </section>
        <section
          className={"panel sessionTerminalPanel sessionChatPanel"}
        >
          <h3>
            {"Conversation"}
          </h3>
          <p
            className={"sessionRoute"}
          >
            {"Live assistant and user message stream"}
          </p>
          {conversationRows().length !== 0 ? <ul
              className={"chatList"}
            >
              {conversationRows().map(row => {
                let bubbleClass = messageRoleClass(row.message.role);
                return <li
                  className={`chatRow ` + bubbleClass}
                >
                  <div
                    className={"chatMetaRow"}
                  >
                    <span
                      className={"chatRole"}
                    >
                      {renderMessageRole(row.message.role)}
                    </span>
                    <span
                      className={"terminalPartMeta"}
                    >
                      {row.message.id}
                    </span>
                  </div>
                  <pre
                    className={"chatBubbleText"}
                  >
                    {row.text}
                  </pre>
                </li>;
              })}
            </ul> : <pre
              className={"terminalStub"}
            >
              {"$ waiting for stream output..."}
            </pre>}
        </section>
      </div>
      <aside
        className={"sessionSidePanel"}
      >
        <section
          className={"panel sideSection"}
        >
          <h3>
            {"Review"}
          </h3>
          <p
            className={"sessionRoute"}
          >
            {"Reducer-routed global activity for this workspace"}
          </p>
          {error$1 !== undefined ? <p
              className={"errorText"}
            >
              {`Server lookup failed: ` + error$1}
            </p> : <span />}
          {recentEvents().length !== 0 ? <ul
              className={"sideEventList"}
            >
              {recentEvents().map(event => <li
                className={"sideEventRow"}
              >
                {renderObservedEvent(event)}
              </li>)}
            </ul> : <p
              className={"loadingText"}
            >
              {"No events captured from the stream yet"}
            </p>}
        </section>
        <section
          className={"panel sideSection"}
        >
          <h3>
            {"Context"}
          </h3>
          {displayedSession !== undefined ? <ul
              className={"summaryList sideSummaryList"}
            >
              <li>
                <strong>
                  {"Session"}
                </strong>
                <span>
                  {displayedSession.id}
                </span>
              </li>
              <li>
                <strong>
                  {"Title"}
                </strong>
                <span>
                  {Stdlib_Option.getOr(displayedSession.title, "Untitled")}
                </span>
              </li>
              <li>
                <strong>
                  {"Updated"}
                </strong>
                <span>
                  {Stdlib_Option.getOr(displayedSession.updatedAt, "Unknown")}
                </span>
              </li>
              <li>
                <strong>
                  {"Status"}
                </strong>
                <span>
                  {renderSessionStatus(effectiveRouteStatus())}
                </span>
              </li>
            </ul> : <p
              className={"loadingText"}
            >
              {"No session payload is cached yet"}
            </p>}
          <p
            className={"sessionRoute"}
          >
            {`Filter scope: ` + renderSessionQuery(sessionQuery())}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Known sessions: ` + sessions().length.toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Running sessions: ` + Stdlib_Array.reduce(sessionStatuses(), 0, (count, item) => {
              if (item.status === "running") {
                return count + 1 | 0;
              } else {
                return count;
              }
            }).toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Pending permissions: ` + pendingPermissionCount().toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Pending questions: ` + pendingQuestionCount().toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Todos tracked: ` + trackedTodoCountForSession(trackedTodos(), counterSessionId).toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Diff files tracked: ` + trackedDiffFileCountForSession(trackedDiffs(), counterSessionId).toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Messages tracked: ` + trackedSessionMessages().length.toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Message parts tracked: ` + trackedSessionParts().length.toString()}
          </p>
          <p
            className={"sessionRoute"}
          >
            {`Streamed chars: ` + streamedCharCount().toString()}
          </p>
        </section>
        <section
          className={"panel sideSection"}
        >
          <h3>
            {"Files"}
          </h3>
          {projects().length !== 0 ? <ul
              className={"sideProjectList"}
            >
              {projects().map(project => {
                let name = Stdlib_Option.getOr(project.name, "Unnamed project");
                let path = Stdlib_Option.getOr(project.path, "Path unavailable");
                return <li
                  className={"sideProjectRow"}
                >
                  <span
                    className={"eventKind"}
                  >
                    {name}
                  </span>
                  <span
                    className={"sessionMeta"}
                  >
                    {path}
                  </span>
                </li>;
              })}
            </ul> : <p
              className={"loadingText"}
            >
              {"No project roots loaded from SDK"}
            </p>}
        </section>
      </aside>
    </div>;
    return AppProviders.sessionProviders(<section
      className={"sessionDetailLayout"}
    >
      {sessionBody}
      <Router.A
        href={"/sessions"}
        inactiveClass={"inlineLink"}
        activeClass={"inlineLink"}
      >
        {"Back to sessions"}
      </Router.A>
    </section>);
  };
  let routedShell = <Router.Router
    root={rootLayout}
  >
    <Router.Route
      path={"/"}
      component={overviewPage}
    />
    <Router.Route
      path={"/sessions"}
      component={sessionsPage}
    />
    <Router.Route
      path={"/:dir"}
    >
      <Router.Route
        path={"/"}
        component={dirIndexPage}
      />
      <Router.Route
        path={"/session/:id?"}
        component={sessionPage}
      />
    </Router.Route>
  </Router.Router>;
  let guardedShell = AppProviders.serverGate(activeServer, <GlobalSDKContext.make
    value={sdkValue}
  >
    <GlobalSyncContext.make
      client={client}
      onOpen={() => {
        setStreamStatus(param => "connected");
        setStreamError(param => {});
      }}
      onError={message => {
        setStreamStatus(param => "error");
        setStreamError(param => message);
      }}
      onEvent={event => {
        setStreamStatus(param => "connected");
        setStreamError(param => {});
        setStreamEventCount(prev => prev + 1 | 0);
        setStreamLastEventKind(param => OpencodeEvent.kind(event));
        GlobalEventReducer.apply(event, {
          refreshAll: () => {
            refreshData(sessionQuery());
          },
          refreshProjects: () => {
            refreshProjectSlice();
          },
          refreshSessions: () => {
            refreshSessionListSlice(sessionQuery());
          },
          refreshStatuses: () => {
            refreshSessionStatusesSlice(sessionQuery());
          },
          applySessionDeleted: applySessionDeleted,
          applySessionStatusChanged: applySessionStatusChanged,
          applySessionScoped: applySessionScoped,
          refreshSessionById: sessionId => {
            loadFocusedSessionById(sessionId);
          },
          activeSessionId: () => focusedSessionId(),
          onObservedEvent: appendObservedEvent
        });
      }}
    >
      {routedShell}
    </GlobalSyncContext.make>
  </GlobalSDKContext.make>);
  return AppProviders.appBaseProviders(<PlatformContext.make
    value={platformValue}
  >
    <ServerContext.make
      value={serverValue}
    >
      {guardedShell}
    </ServerContext.make>
  </PlatformContext.make>);
}

let make = App;

export {
  make,
}
/* solid-js Not a pure module */
