// Generated by ReScript, PLEASE EDIT WITH CARE

import * as AppShell from "./AppShell.mjs";
import * as SolidJs from "solid-js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.mjs";
import * as Stdlib_Int from "@rescript/runtime/lib/es6/Stdlib_Int.mjs";
import * as H from "solid-js/h";
import * as AppProviders from "./AppProviders.mjs";
import * as OverviewPage from "./OverviewPage.mjs";
import * as SessionsPage from "./SessionsPage.mjs";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as OpencodeEvent from "opencode-example-sdk/src/OpencodeEvent.mjs";
import * as ServerContext from "./ServerContext.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";
import * as OpencodeClient from "opencode-example-sdk/src/OpencodeClient.mjs";
import * as Router from "@solidjs/router";
import * as PlatformContext from "./PlatformContext.mjs";
import * as GlobalSDKContext from "./GlobalSDKContext.mjs";
import * as Primitive_object from "@rescript/runtime/lib/es6/Primitive_object.mjs";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";
import * as SessionPageFrame from "./SessionPageFrame.mjs";
import * as SessionSidePanel from "./SessionSidePanel.mjs";
import * as GlobalSyncContext from "./GlobalSyncContext.mjs";
import * as GlobalEventReducer from "./GlobalEventReducer.mjs";
import * as ReactivityProbePage from "./ReactivityProbePage.mjs";
import * as SessionComposerRegion from "./SessionComposerRegion.mjs";
import * as SessionPageController from "./SessionPageController.mjs";
import * as SessionConversationPanel from "./SessionConversationPanel.mjs";

function renderProjectLabel(project) {
  let name = Stdlib_Option.getOr(project.name, "unnamed");
  let path = Stdlib_Option.getOr(project.path, "unknown-path");
  return name + ` - ` + path;
}

function renderSessionSubtitle(session) {
  let title = Stdlib_Option.getOr(session.title, "(untitled)");
  let updatedAt = Stdlib_Option.getOr(session.updatedAt, "unknown-updated-time");
  return title + ` - ` + updatedAt;
}

function renderSessionStatus(status) {
  if (status !== undefined) {
    if (status === "running") {
      return "running";
    } else {
      return "idle";
    }
  } else {
    return "unknown";
  }
}

function renderMessageRole(role) {
  if (role === undefined) {
    return "Message";
  }
  if (typeof role === "object") {
    return role._0;
  }
  switch (role) {
    case "UserRole" :
      return "User";
    case "AssistantRole" :
      return "Assistant";
    case "ToolRole" :
      return "Tool";
    case "SystemRole" :
      return "System";
  }
}

function messageRoleClass(role) {
  if (role === undefined) {
    return "chatUnknown";
  }
  if (typeof role === "object") {
    return "chatUnknown";
  }
  switch (role) {
    case "UserRole" :
      return "chatUser";
    case "AssistantRole" :
      return "chatAssistant";
    case "ToolRole" :
      return "chatTool";
    case "SystemRole" :
      return "chatSystem";
  }
}

function countRunningSessions(items) {
  return Stdlib_Array.reduce(items, 0, (count, item) => {
    let match = item.status;
    if (match === "running") {
      return count + 1 | 0;
    } else {
      return count;
    }
  });
}

function findSessionStatus(items, sessionId) {
  return Stdlib_Array.reduce(items, undefined, (found, item) => {
    if (found !== undefined) {
      return found;
    } else if (item.id === sessionId) {
      return item.status;
    } else {
      return;
    }
  });
}

function upsertTrackedMessage(items, message) {
  let exists = items.some(item => {
    if (item.sessionId === message.sessionId) {
      return item.message.id === message.id;
    } else {
      return false;
    }
  });
  if (exists) {
    return items.map(item => {
      if (item.sessionId === message.sessionId && item.message.id === message.id) {
        return {
          sessionId: message.sessionId,
          message: message
        };
      } else {
        return item;
      }
    });
  } else {
    return Belt_Array.concatMany([
      [{
          sessionId: message.sessionId,
          message: message
        }],
      items
    ]);
  }
}

function upsertTrackedPart(items, part) {
  let exists = items.some(item => {
    if (item.sessionId === part.sessionId && item.messageId === part.messageId) {
      return item.part.id === part.id;
    } else {
      return false;
    }
  });
  if (exists) {
    return items.map(item => {
      if (item.sessionId === part.sessionId && item.messageId === part.messageId && item.part.id === part.id) {
        return {
          sessionId: item.sessionId,
          messageId: item.messageId,
          part: part,
          streamedChars: item.streamedChars,
          text: item.text
        };
      } else {
        return item;
      }
    });
  } else {
    return Belt_Array.concatMany([
      [{
          sessionId: part.sessionId,
          messageId: part.messageId,
          part: part,
          streamedChars: 0,
          text: ""
        }],
      items
    ]);
  }
}

function sessionStatusFromEventKind(status) {
  if (typeof status !== "object" && status === "Idle") {
    return "idle";
  } else {
    return "running";
  }
}

function normalizeQueryText(value) {
  let trimmed = value.trim();
  if (trimmed === "") {
    return;
  } else {
    return trimmed;
  }
}

function normalizeQueryLimit(value) {
  let limit = Stdlib_Int.fromString(value.trim());
  if (limit !== undefined && limit > 0) {
    return limit;
  }
}

function buildSessionQuery(directoryText, searchText, limitText) {
  let directory = normalizeQueryText(directoryText);
  let search = normalizeQueryText(searchText);
  let limit = normalizeQueryLimit(limitText);
  if (directory === undefined && search === undefined && limit === undefined) {
    return;
  } else {
    return {
      directory: directory,
      search: search,
      limit: limit
    };
  }
}

function renderSessionQuery(query) {
  if (query === undefined) {
    return "No filters";
  }
  let limit = query.limit;
  let directoryText = Stdlib_Option.getOr(query.directory, "any-dir");
  let searchText = Stdlib_Option.getOr(query.search, "any-text");
  let limitText = limit !== undefined ? limit.toString() : "default";
  return `dir=` + directoryText + `, search=` + searchText + `, limit=` + limitText;
}

function routeDirectoryForSessions(query) {
  if (query === undefined) {
    return "workspace";
  }
  let directory = query.directory;
  if (directory !== undefined) {
    return directory;
  } else {
    return "workspace";
  }
}

function App$ServerStatusPanel(props) {
  let onRefreshServer = props.onRefreshServer;
  let onResetServer = props.onResetServer;
  let onApplyServer = props.onApplyServer;
  let onServerDraftChange = props.onServerDraftChange;
  let streamError = props.streamError;
  let isRouting = props.isRouting;
  return <section
    className={"panel statusPanel"}
  >
    <div
      className={"statusLine"}
    >
      <h2>
        {"Server"}
      </h2>
      <span
        className={isRouting ? "routeState moving" : "routeState"}
      >
        {isRouting ? "routing" : "idle"}
      </span>
    </div>
    <code>
      {props.activeServer}
    </code>
    <p
      className={"statusPath"}
    >
      {`Path: ` + props.locationPathname}
    </p>
    <p
      className={"streamMeta"}
    >
      {`Stream: ` + props.streamStatusText + ` (events ` + props.streamEventCount.toString() + `)`}
    </p>
    {streamError !== undefined ? <p
        className={"errorText"}
      >
        {`Stream error: ` + streamError}
      </p> : <span />}
    <p
      className={"streamMeta"}
    >
      {`Last event: ` + Stdlib_Option.getOr(props.streamLastEventKind, "none")}
    </p>
    <div
      className={"serverForm"}
    >
      <input
        id={"server-url-input"}
        placeholder={"https://your-opencode-server"}
        type={"text"}
        value={props.serverDraft}
        onInput={event => onServerDraftChange(event.target.value)}
      />
      <button
        className={"refreshBtn"}
        id={"server-apply-btn"}
        onClick={param => onApplyServer()}
      >
        {"Apply"}
      </button>
      <button
        className={"ghostBtn"}
        id={"server-reset-btn"}
        onClick={param => onResetServer()}
      >
        {"Reset"}
      </button>
      <button
        className={"ghostBtn"}
        id={"server-refresh-btn"}
        onClick={param => onRefreshServer()}
      >
        {"Refresh"}
      </button>
    </div>
  </section>;
}

let ServerStatusPanel = {
  make: App$ServerStatusPanel
};

function App$SessionsEventList(props) {
  let sessionStatuses = props.sessionStatuses;
  let routeDirectory = routeDirectoryForSessions(props.sessionQuery);
  return <ul
    className={"eventList"}
  >
    <SolidJs.For
      each={props.sessions}
      fallback={<li
        className={"eventRow"}
      >
        <span
          className={"loadingText"}
        >
          {"No sessions matched the current filters"}
        </span>
      </li>}
    >
      {(session, index) => {
        let status = findSessionStatus(sessionStatuses, session.id);
        return <li
          className={"eventRow"}
        >
          <span
            className={"eventIndex"}
          >
            {`#` + index().toString()}
          </span>
          <span
            className={"eventKind"}
          >
            {session.id}
          </span>
          <span
            className={"sessionMeta"}
          >
            {renderSessionSubtitle(session)}
          </span>
          <span
            className={Primitive_object.equal(status, "running") ? "badge hot" : "badge"}
          >
            {renderSessionStatus(status)}
          </span>
          <Router.A
            href={`/` + routeDirectory + `/session/` + session.id}
            inactiveClass={"inlineLink"}
            activeClass={"inlineLink"}
          >
            {"open"}
          </Router.A>
        </li>;
      }}
    </SolidJs.For>
  </ul>;
}

let SessionsEventList = {
  make: App$SessionsEventList
};

let composerModelStorageKey = "opencode.settings.dat:composerModelOverride";

let customModelSentinel = "__custom__";

let fallbackModelPresetOptions = [
  {
    value: "anthropic/claude-sonnet-4-5",
    label: "Claude Sonnet 4.5",
    providerID: "anthropic",
    modelID: "claude-sonnet-4-5"
  },
  {
    value: "anthropic/claude-opus-4-1",
    label: "Claude Opus 4.1",
    providerID: "anthropic",
    modelID: "claude-opus-4-1"
  },
  {
    value: "openai/gpt-5",
    label: "GPT-5",
    providerID: "openai",
    modelID: "gpt-5"
  },
  {
    value: "openai/gpt-5-mini",
    label: "GPT-5 Mini",
    providerID: "openai",
    modelID: "gpt-5-mini"
  },
  {
    value: "openai/gpt-5.3-codex",
    label: "GPT-5.3 Codex",
    providerID: "openai",
    modelID: "gpt-5.3-codex"
  }
];

function isKnownModelPreset(options, value) {
  return options.some(option => option.value === value);
}

function resolveModelSelection(options, value) {
  let option = options.find(option => option.value === value);
  if (option !== undefined) {
    return {
      providerID: option.providerID,
      modelID: option.modelID
    };
  } else {
    let match = value.split("/");
    if (match.length !== 2) {
      return;
    }
    let providerID = match[0];
    let modelID = match[1];
    let normalizedProviderID = providerID.trim();
    let normalizedModelID = modelID.trim();
    if (normalizedProviderID === "" || normalizedModelID === "") {
      return;
    } else {
      return {
        providerID: normalizedProviderID,
        modelID: normalizedModelID
      };
    }
  }
}

function getStoredComposerModel() {
  try {
    let storage = window.localStorage;
    if (storage !== undefined) {
      return Stdlib_Option.flatMap(Primitive_option.fromNullable(Primitive_option.valFromOption(storage).getItem(composerModelStorageKey)), normalizeQueryText);
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function pendingComposerStorageKeyForSession(sessionId) {
  return "opencode.settings.dat:pendingComposerEntries" + `:` + sessionId;
}

function getStoredPendingComposerText(sessionId) {
  try {
    let storage = window.localStorage;
    if (storage !== undefined) {
      return Stdlib_Option.flatMap(Primitive_option.fromNullable(Primitive_option.valFromOption(storage).getItem(pendingComposerStorageKeyForSession(sessionId))), normalizeQueryText);
    } else {
      return;
    }
  } catch (exn) {
    return;
  }
}

function setStoredPendingComposerText(sessionId, text) {
  try {
    let storage = window.localStorage;
    if (storage === undefined) {
      return;
    }
    let storage$1 = Primitive_option.valFromOption(storage);
    let trimmedText = Stdlib_Option.flatMap(text, normalizeQueryText);
    if (trimmedText !== undefined) {
      storage$1.setItem(pendingComposerStorageKeyForSession(sessionId), trimmedText);
    } else {
      storage$1.removeItem(pendingComposerStorageKeyForSession(sessionId));
    }
    return;
  } catch (exn) {
    return;
  }
}

function resolvePendingComposerEntry(requestedSessionId, hydratedSessionId) {
  let text = getStoredPendingComposerText(requestedSessionId);
  if (text !== undefined) {
    return [
      requestedSessionId,
      text
    ];
  } else if (hydratedSessionId === requestedSessionId) {
    return;
  } else {
    return Stdlib_Option.map(getStoredPendingComposerText(hydratedSessionId), text => [
      hydratedSessionId,
      text
    ]);
  }
}

function rememberFirstError(firstError, message) {
  if (Stdlib_Option.isNone(firstError.contents)) {
    firstError.contents = message;
    return;
  }
}

function syncRequestState(setState, firstError) {
  if (firstError !== undefined) {
    return setState(param => ({
      TAG: "Failed",
      _0: firstError
    }));
  } else {
    return setState(param => "Ready");
  }
}

function renderObservedEvent(event) {
  let sessionId = event.sessionId;
  let sessionSuffix = sessionId !== undefined ? ` [` + sessionId + `]` : "";
  return OpencodeEvent.kindTagToString(event.kind) + sessionSuffix + ` -> ` + OpencodeEvent.refreshPathToString(event.refreshPath);
}

function App(props) {
  let platformValue = PlatformContext.web(undefined, undefined);
  let value = platformValue.getDefaultServerUrl();
  let fallbackServer;
  if (value !== undefined) {
    let trimmed = value.trim();
    fallbackServer = trimmed === "" ? "http://localhost:4096" : trimmed;
  } else {
    fallbackServer = "http://localhost:4096";
  }
  let value$1 = props.defaultServer.trim();
  let initialServer = value$1 === "" ? fallbackServer : value$1;
  let match = SolidJs.createSignal(initialServer);
  let setActiveServer = match[1];
  let activeServer = match[0];
  let match$1 = SolidJs.createSignal(initialServer);
  let setServerDraft = match$1[1];
  let serverDraft = match$1[0];
  let match$2 = SolidJs.createSignal("Loading /global/health ...");
  let setHealthText = match$2[1];
  let healthText = match$2[0];
  let match$3 = SolidJs.createSignal("Loading /project/current ...");
  let setProjectText = match$3[1];
  let projectText = match$3[0];
  let match$4 = SolidJs.createSignal([]);
  let setProjects = match$4[1];
  let projects = match$4[0];
  let match$5 = SolidJs.createSignal([]);
  let setSessions = match$5[1];
  let sessions = match$5[0];
  let match$6 = SolidJs.createSignal([]);
  let setSessionStatuses = match$6[1];
  let sessionStatuses = match$6[0];
  let match$7 = SolidJs.createSignal("");
  let setSessionDirectoryDraft = match$7[1];
  let sessionDirectoryDraft = match$7[0];
  let match$8 = SolidJs.createSignal("");
  let setSessionSearchDraft = match$8[1];
  let sessionSearchDraft = match$8[0];
  let match$9 = SolidJs.createSignal("");
  let setSessionLimitDraft = match$9[1];
  let sessionLimitDraft = match$9[0];
  let match$10 = SolidJs.createSignal(undefined);
  let setSessionQuery = match$10[1];
  let sessionQuery = match$10[0];
  let match$11 = SolidJs.createSignal(undefined);
  let setFocusedSessionId = match$11[1];
  let focusedSessionId = match$11[0];
  let match$12 = SolidJs.createSignal(undefined);
  let setFocusedSession = match$12[1];
  let focusedSession = match$12[0];
  let match$13 = SolidJs.createSignal(undefined);
  let setFocusedSessionError = match$13[1];
  let focusedSessionError = match$13[0];
  let match$14 = SolidJs.createSignal([]);
  let setTrackedQueueRequests = match$14[1];
  let trackedQueueRequests = match$14[0];
  let match$15 = SolidJs.createSignal([]);
  let setTrackedTodos = match$15[1];
  let trackedTodos = match$15[0];
  let match$16 = SolidJs.createSignal([]);
  let setTrackedDiffs = match$16[1];
  let trackedDiffs = match$16[0];
  let match$17 = SolidJs.createSignal([]);
  let setTrackedMessages = match$17[1];
  let trackedMessages = match$17[0];
  let match$18 = SolidJs.createSignal([]);
  let setTrackedParts = match$18[1];
  let trackedParts = match$18[0];
  let match$19 = SolidJs.createSignal([]);
  let setRecentEvents = match$19[1];
  let recentEvents = match$19[0];
  let match$20 = SolidJs.createSignal("");
  let setComposerDraft = match$20[1];
  let composerDraft = match$20[0];
  let initialComposerModel = Stdlib_Option.getOr(getStoredComposerModel(), "");
  let match$21 = SolidJs.createSignal(fallbackModelPresetOptions);
  let setComposerModelOptions = match$21[1];
  let composerModelOptions = match$21[0];
  let match$22 = SolidJs.createSignal(initialComposerModel);
  let setComposerModelDraft = match$22[1];
  let composerModelDraft = match$22[0];
  let value$2 = normalizeQueryText(initialComposerModel);
  let match$23 = SolidJs.createSignal(value$2 !== undefined ? !isKnownModelPreset(fallbackModelPresetOptions, value$2) : false);
  let setComposerCustomModelEnabled = match$23[1];
  let composerCustomModelEnabled = match$23[0];
  let match$24 = SolidJs.createSignal(undefined);
  let setComposerError = match$24[1];
  let composerError = match$24[0];
  let match$25 = SolidJs.createSignal(false);
  let setIsComposerSending = match$25[1];
  let isComposerSending = match$25[0];
  let match$26 = SolidJs.createSignal("disconnected");
  let setStreamStatus = match$26[1];
  let streamStatus = match$26[0];
  let match$27 = SolidJs.createSignal(undefined);
  let setStreamError = match$27[1];
  let streamError = match$27[0];
  let match$28 = SolidJs.createSignal(0);
  let setStreamEventCount = match$28[1];
  let streamEventCount = match$28[0];
  let match$29 = SolidJs.createSignal(undefined);
  let setStreamLastEventKind = match$29[1];
  let streamLastEventKind = match$29[0];
  let match$30 = SolidJs.createSignal("Loading");
  let setState = match$30[1];
  let state = match$30[0];
  let client = SolidJs.createMemo(() => OpencodeClient.make(activeServer(), undefined, undefined, undefined));
  let loadHealthData = async firstError => {
    let sdk = client();
    let health = await OpencodeClient.health(sdk);
    if (health.TAG === "Ok") {
      let health$1 = health._0;
      let version = health$1.version;
      let versionSuffix = version !== undefined ? ` (version ` + version + `)` : "";
      return setHealthText(param => health$1.status + versionSuffix);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(health._0));
    return setHealthText(param => "Unavailable");
  };
  let loadProjectData = async firstError => {
    let sdk = client();
    let project = await OpencodeClient.projectCurrent(sdk);
    if (project.TAG === "Ok") {
      let project$1 = project._0;
      setProjectText(param => {
        if (project$1 === undefined) {
          return "No active project returned by /project/current";
        }
        let id = Stdlib_Option.getOr(project$1.id, "unknown-id");
        let name = Stdlib_Option.getOr(project$1.name, "unnamed");
        let path = Stdlib_Option.getOr(project$1.path, "unknown-path");
        return name + ` (` + id + `) at ` + path;
      });
    } else {
      rememberFirstError(firstError, OpencodeClient.errorToString(project._0));
      setProjectText(param => "Unavailable");
    }
    let items = await OpencodeClient.projects(sdk);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setProjects(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setProjects(param => []);
  };
  let loadSessionListData = async (query, firstError) => {
    let sdk = client();
    let items = await OpencodeClient.sessions(sdk, query, undefined);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setSessions(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setSessions(param => []);
  };
  let loadSessionStatusData = async (query, firstError) => {
    let sdk = client();
    let items = await OpencodeClient.sessionStatuses(sdk, query, undefined);
    if (items.TAG === "Ok") {
      let items$1 = items._0;
      return setSessionStatuses(param => items$1);
    }
    rememberFirstError(firstError, OpencodeClient.errorToString(items._0));
    return setSessionStatuses(param => []);
  };
  let loadSessionData = async (query, firstError) => {
    await loadSessionListData(query, firstError);
    return await loadSessionStatusData(query, firstError);
  };
  let loadComposerModelOptions = async () => {
    let sdk = client();
    let items = await OpencodeClient.configModels(sdk);
    if (items.TAG !== "Ok") {
      return setComposerModelOptions(param => fallbackModelPresetOptions);
    }
    let items$1 = items._0;
    let nextOptions = items$1.length !== 0 ? items$1.map(item => ({
        value: item.id,
        label: item.label,
        providerID: item.providerID,
        modelID: item.modelID
      })) : fallbackModelPresetOptions;
    setComposerModelOptions(param => nextOptions);
    let value = normalizeQueryText(composerModelDraft());
    if (value !== undefined && isKnownModelPreset(nextOptions, value)) {
      return setComposerCustomModelEnabled(param => false);
    }
  };
  SolidJs.createEffect(() => {
    let value = composerModelDraft();
    try {
      let storage = window.localStorage;
      if (storage === undefined) {
        return;
      }
      let storage$1 = Primitive_option.valFromOption(storage);
      let trimmed = normalizeQueryText(value);
      if (trimmed !== undefined) {
        storage$1.setItem(composerModelStorageKey, trimmed);
      } else {
        storage$1.removeItem(composerModelStorageKey);
      }
      return;
    } catch (exn) {
      return;
    }
  });
  let hydrateSessionConversationById = async sessionId => {
    let sdk = client();
    let messages = await OpencodeClient.sessionMessages(sdk, sessionId);
    if (messages.TAG !== "Ok") {
      return;
    }
    let messages$1 = messages._0;
    let hydratedSessionId = Stdlib_Option.getOr(Stdlib_Array.findMap(messages$1, message => {
      let value = message.sessionId.trim();
      if (value === "") {
        return;
      } else {
        return value;
      }
    }), sessionId);
    let hydratedMessages = messages$1.map(message => {
      let snapshot_id = message.id;
      let snapshot_sessionId = message.sessionId;
      let snapshot_role = message.role;
      let snapshot = {
        id: snapshot_id,
        sessionId: snapshot_sessionId,
        role: snapshot_role
      };
      return {
        sessionId: message.sessionId,
        message: snapshot
      };
    });
    let hydratedParts = Stdlib_Array.reduce(messages$1, [], (partsAcc, message) => Stdlib_Array.reduce(message.parts, partsAcc, (innerAcc, part) => {
      let snapshot_id = part.id;
      let snapshot_sessionId = part.sessionId;
      let snapshot_messageId = part.messageId;
      let snapshot_partType = part.partType;
      let snapshot = {
        id: snapshot_id,
        sessionId: snapshot_sessionId,
        messageId: snapshot_messageId,
        partType: snapshot_partType
      };
      return innerAcc.concat([{
          sessionId: part.sessionId,
          messageId: part.messageId,
          part: snapshot,
          streamedChars: part.text.length,
          text: part.text
        }]);
    }));
    let historyHasText = text => {
      let trimmed = text.trim();
      if (trimmed !== "") {
        return hydratedParts.some(part => part.text.trim() === trimmed);
      } else {
        return false;
      }
    };
    let pendingComposerEntry = resolvePendingComposerEntry(sessionId, hydratedSessionId);
    let pendingText = Stdlib_Option.map(pendingComposerEntry, param => param[1]);
    let pendingTrackedMessages;
    if (pendingText !== undefined) {
      if (historyHasText(pendingText)) {
        pendingTrackedMessages = [];
      } else {
        let pendingMessageId = `pending-user-message-` + hydratedSessionId;
        let snapshot_role = "UserRole";
        let snapshot = {
          id: pendingMessageId,
          sessionId: hydratedSessionId,
          role: snapshot_role
        };
        pendingTrackedMessages = [{
            sessionId: hydratedSessionId,
            message: snapshot
          }];
      }
    } else {
      pendingTrackedMessages = [];
    }
    let pendingTrackedParts;
    if (pendingText !== undefined) {
      if (historyHasText(pendingText)) {
        pendingTrackedParts = [];
      } else {
        let pendingMessageId$1 = `pending-user-message-` + hydratedSessionId;
        let snapshot_id = `pending-user-part-` + hydratedSessionId;
        let snapshot_partType = "TextPart";
        let snapshot$1 = {
          id: snapshot_id,
          sessionId: hydratedSessionId,
          messageId: pendingMessageId$1,
          partType: snapshot_partType
        };
        pendingTrackedParts = [{
            sessionId: hydratedSessionId,
            messageId: pendingMessageId$1,
            part: snapshot$1,
            streamedChars: pendingText.length,
            text: pendingText
          }];
      }
    } else {
      pendingTrackedParts = [];
    }
    let hydratedMessagesAll = hydratedMessages.concat(pendingTrackedMessages);
    let hydratedPartsAll = hydratedParts.concat(pendingTrackedParts);
    setTrackedMessages(items => {
      let sessionItems = items.filter(item => item.sessionId === hydratedSessionId);
      let remaining = items.filter(item => item.sessionId !== hydratedSessionId);
      let mergedSessionItems = Stdlib_Array.reduce(hydratedMessagesAll, sessionItems, (acc, hydrated) => upsertTrackedMessage(acc, hydrated.message));
      return mergedSessionItems.concat(remaining);
    });
    return setTrackedParts(items => {
      let sessionItems = items.filter(item => item.sessionId === hydratedSessionId);
      let remaining = items.filter(item => item.sessionId !== hydratedSessionId);
      let mergedSessionItems = Stdlib_Array.reduce(hydratedPartsAll, sessionItems, (acc, hydratedPart) => {
        let withPart = upsertTrackedPart(acc, hydratedPart.part);
        return withPart.map(item => {
          if (item.sessionId === hydratedPart.sessionId && item.messageId === hydratedPart.messageId && item.part.id === hydratedPart.part.id) {
            return {
              sessionId: item.sessionId,
              messageId: item.messageId,
              part: item.part,
              streamedChars: hydratedPart.streamedChars,
              text: hydratedPart.text !== "" ? hydratedPart.text : item.text
            };
          } else {
            return item;
          }
        });
      });
      return mergedSessionItems.concat(remaining);
    });
  };
  let loadFocusedSessionById = async sessionId => {
    let sdk = client();
    let found = await OpencodeClient.sessionById(sdk, sessionId);
    if (found.TAG === "Ok") {
      let found$1 = found._0;
      setFocusedSession(param => found$1);
      setFocusedSessionError(param => {});
      let hydratedSessionId = found$1 !== undefined ? found$1.id : sessionId;
      await hydrateSessionConversationById(hydratedSessionId);
      return;
    }
    let error = found._0;
    setFocusedSession(param => {});
    return setFocusedSessionError(param => OpencodeClient.errorToString(error));
  };
  let appendObservedEvent = event => setRecentEvents(events => {
    let capped = Belt_Array.concatMany([
      [event],
      events
    ]);
    let seen = {
      contents: 0
    };
    return capped.filter(param => {
      let keep = seen.contents < 60;
      seen.contents = seen.contents + 1 | 0;
      return keep;
    });
  });
  let applySessionStatusChanged = payload => {
    let nextStatus = sessionStatusFromEventKind(payload.status);
    let nextItem_id = payload.sessionId;
    let nextItem = {
      id: nextItem_id,
      status: nextStatus
    };
    setSessionStatuses(items => {
      let hasExisting = items.some(item => item.id === payload.sessionId);
      let updated = items.map(item => {
        if (item.id === payload.sessionId) {
          return nextItem;
        } else {
          return item;
        }
      });
      if (hasExisting) {
        return updated;
      } else {
        return Belt_Array.concatMany([
          [nextItem],
          updated
        ]);
      }
    });
  };
  let applySessionDeleted = payload => {
    setSessions(items => items.filter(item => item.id !== payload.sessionId));
    setSessionStatuses(items => items.filter(item => item.id !== payload.sessionId));
    setTrackedQueueRequests(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedTodos(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedDiffs(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedMessages(items => items.filter(item => item.sessionId !== payload.sessionId));
    setTrackedParts(items => items.filter(item => item.sessionId !== payload.sessionId));
    setStoredPendingComposerText(payload.sessionId, undefined);
    let activeSessionId = focusedSessionId();
    if (activeSessionId !== undefined && activeSessionId === payload.sessionId) {
      setFocusedSession(param => {});
      return setFocusedSessionError(param => {});
    }
  };
  let applySessionScoped = payload => {
    let match = OpencodeEvent.queueRequestMutationFromScoped(payload);
    if (match !== undefined) {
      if (match.TAG === "UpsertQueueRequest") {
        let match$1 = match._0;
        let requestId = match$1.requestId;
        let sessionId = match$1.sessionId;
        let queue = match$1.queue;
        setTrackedQueueRequests(items => {
          let exists = items.some(item => {
            if (item.queue === queue && item.sessionId === sessionId) {
              return item.requestId === requestId;
            } else {
              return false;
            }
          });
          if (exists) {
            return items;
          } else {
            return Belt_Array.concatMany([
              [{
                  queue: queue,
                  sessionId: sessionId,
                  requestId: requestId
                }],
              items
            ]);
          }
        });
      } else {
        let match$2 = match._0;
        let requestId$1 = match$2.requestId;
        let sessionId$1 = match$2.sessionId;
        let queue$1 = match$2.queue;
        setTrackedQueueRequests(items => items.filter(item => item.queue !== queue$1 || item.sessionId !== sessionId$1 || item.requestId !== requestId$1));
      }
    }
    let match$3 = OpencodeEvent.todoUpdatedFromScoped(payload);
    if (match$3 !== undefined) {
      let todos = match$3.todos;
      let sessionId$2 = match$3.sessionId;
      setTrackedTodos(items => {
        let remaining = items.filter(item => item.sessionId !== sessionId$2);
        return Belt_Array.concatMany([
          [{
              sessionId: sessionId$2,
              todos: todos
            }],
          remaining
        ]);
      });
    }
    let match$4 = OpencodeEvent.sessionDiffFromScoped(payload);
    if (match$4 !== undefined) {
      let diff = match$4.diff;
      let sessionId$3 = match$4.sessionId;
      setTrackedDiffs(items => {
        let remaining = items.filter(item => item.sessionId !== sessionId$3);
        return Belt_Array.concatMany([
          [{
              sessionId: sessionId$3,
              diff: diff
            }],
          remaining
        ]);
      });
    }
    let match$5 = OpencodeEvent.messageMutationFromScoped(payload);
    if (match$5 === undefined) {
      return;
    }
    switch (match$5.TAG) {
      case "UpsertMessage" :
        let message = match$5._0.message;
        return setTrackedMessages(items => upsertTrackedMessage(items, message));
      case "RemoveMessage" :
        let match$6 = match$5._0;
        let messageId = match$6.messageId;
        let sessionId$4 = match$6.sessionId;
        setTrackedMessages(items => items.filter(item => item.sessionId !== sessionId$4 || item.message.id !== messageId));
        return setTrackedParts(items => items.filter(part => part.sessionId !== sessionId$4 || part.messageId !== messageId));
      case "UpsertPart" :
        let part = match$5._0.part;
        let inferredMessage_id = part.messageId;
        let inferredMessage_sessionId = part.sessionId;
        let inferredMessage = {
          id: inferredMessage_id,
          sessionId: inferredMessage_sessionId,
          role: undefined
        };
        setTrackedMessages(items => upsertTrackedMessage(items, inferredMessage));
        return setTrackedParts(items => upsertTrackedPart(items, part));
      case "RemovePart" :
        let match$7 = match$5._0;
        let partId = match$7.partId;
        let messageId$1 = match$7.messageId;
        let sessionId$5 = match$7.sessionId;
        return setTrackedParts(items => items.filter(part => {
          if (sessionId$5 !== undefined) {
            return part.sessionId !== sessionId$5 || part.messageId !== messageId$1 || part.part.id !== partId;
          } else {
            return part.messageId !== messageId$1 || part.part.id !== partId;
          }
        }));
      case "AppendPartDelta" :
        let match$8 = match$5._0;
        let deltaText = match$8.deltaText;
        let deltaChars = match$8.deltaChars;
        let partId$1 = match$8.partId;
        let messageId$2 = match$8.messageId;
        let sessionId$6 = match$8.sessionId;
        return setTrackedParts(items => {
          let appendedText = Stdlib_Option.getOr(deltaText, "");
          let hasAppendedText = appendedText !== "";
          if (deltaChars <= 0 && !hasAppendedText) {
            return items;
          }
          let hasMatch = items.some(part => {
            if (sessionId$6 !== undefined) {
              if (part.sessionId === sessionId$6 && part.messageId === messageId$2) {
                return part.part.id === partId$1;
              } else {
                return false;
              }
            } else if (part.messageId === messageId$2) {
              return part.part.id === partId$1;
            } else {
              return false;
            }
          });
          if (hasMatch) {
            return items.map(part => {
              if (sessionId$6 !== undefined) {
                if (part.sessionId === sessionId$6 && part.messageId === messageId$2 && part.part.id === partId$1) {
                  return {
                    sessionId: part.sessionId,
                    messageId: part.messageId,
                    part: part.part,
                    streamedChars: part.streamedChars + deltaChars | 0,
                    text: hasAppendedText ? part.text + appendedText : part.text
                  };
                } else {
                  return part;
                }
              } else if (part.messageId === messageId$2 && part.part.id === partId$1) {
                return {
                  sessionId: part.sessionId,
                  messageId: part.messageId,
                  part: part.part,
                  streamedChars: part.streamedChars + deltaChars | 0,
                  text: hasAppendedText ? part.text + appendedText : part.text
                };
              } else {
                return part;
              }
            });
          } else if (sessionId$6 !== undefined) {
            return Belt_Array.concatMany([
              [{
                  sessionId: sessionId$6,
                  messageId: messageId$2,
                  part: {
                    id: partId$1,
                    sessionId: sessionId$6,
                    messageId: messageId$2,
                    partType: undefined
                  },
                  streamedChars: deltaChars,
                  text: appendedText
                }],
              items
            ]);
          } else {
            return items;
          }
        });
    }
  };
  let refreshData = async query => {
    setState(param => "Loading");
    let firstError = {
      contents: undefined
    };
    await loadHealthData(firstError);
    await loadProjectData(firstError);
    await loadComposerModelOptions();
    await loadSessionData(query, firstError);
    let activeSessionId = focusedSessionId();
    if (activeSessionId !== undefined) {
      await loadFocusedSessionById(activeSessionId);
    }
    return syncRequestState(setState, firstError.contents);
  };
  let refreshProjectSlice = async () => {
    let firstError = {
      contents: undefined
    };
    await loadProjectData(firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionListSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionListData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let refreshSessionStatusesSlice = async query => {
    let firstError = {
      contents: undefined
    };
    await loadSessionStatusData(query, firstError);
    return syncRequestState(setState, firstError.contents);
  };
  let applyServer = () => {
    let nextServer = serverDraft().trim();
    let resolvedServer = nextServer === "" ? initialServer : nextServer;
    setActiveServer(param => resolvedServer);
    setServerDraft(param => resolvedServer);
    platformValue.setDefaultServerUrl(resolvedServer);
    refreshData(sessionQuery());
  };
  let resetServer = () => {
    setServerDraft(param => initialServer);
    setActiveServer(param => initialServer);
    platformValue.setDefaultServerUrl(initialServer);
    refreshData(sessionQuery());
  };
  let refreshFromContext = () => {
    refreshData(sessionQuery());
  };
  let applySessionFilters = () => {
    let nextQuery = buildSessionQuery(sessionDirectoryDraft(), sessionSearchDraft(), sessionLimitDraft());
    setSessionQuery(param => nextQuery);
    refreshSessionSlice(nextQuery);
  };
  let clearSessionFilters = () => {
    setSessionDirectoryDraft(param => "");
    setSessionSearchDraft(param => "");
    setSessionLimitDraft(param => "");
    setSessionQuery(param => {});
    refreshSessionSlice(undefined);
  };
  let serverValue_setServerDraft = value => setServerDraft(param => value);
  let serverValue = {
    activeServer: activeServer,
    serverDraft: serverDraft,
    setServerDraft: serverValue_setServerDraft,
    applyServer: applyServer,
    resetServer: resetServer,
    refresh: refreshFromContext
  };
  let sdkValue = {
    client: client
  };
  SolidJs.onMount(() => {
    refreshData(sessionQuery());
  });
  let rootLayout = props => {
    let isRouting = Router.useIsRouting();
    let location = Router.useLocation();
    let sidebarSessions = SolidJs.createMemo(() => {
      let routeDirectory = routeDirectoryForSessions(sessionQuery());
      let statuses = sessionStatuses();
      return sessions().map(session => ({
        id: session.id,
        href: `/` + routeDirectory + `/session/` + session.id,
        isRunning: Primitive_object.equal(findSessionStatus(statuses, session.id), "running")
      }));
    });
    return AppProviders.routerRoot(<AppShell.make
      serverStatusPanel={<ServerStatusPanel.make
        isRouting={isRouting()}
        activeServer={activeServer()}
        locationPathname={location.pathname}
        streamStatusText={streamStatus()}
        streamEventCount={streamEventCount()}
        streamError={streamError()}
        streamLastEventKind={streamLastEventKind()}
        serverDraft={serverDraft()}
        onServerDraftChange={value => serverValue_setServerDraft(value)}
        onApplyServer={() => applyServer()}
        onResetServer={() => resetServer()}
        onRefreshServer={() => {
          refreshData(sessionQuery());
        }}
      />}
      sidebarSessions={sidebarSessions()}
      onBack={() => platformValue.back()}
      onForward={() => platformValue.forward()}
      onReload={() => platformValue.restart()}
      onOpenUpstream={() => platformValue.openLink("https://github.com/anomalyco/opencode")}
    >
      {props.children}
    </AppShell.make>);
  };
  let overviewPage = param => {
    let sync = GlobalSyncContext.use();
    let overviewProjects = projects().map(project => ({
      label: renderProjectLabel(project)
    }));
    let message = state();
    let overviewStatus;
    overviewStatus = typeof message !== "object" ? (
        message === "Loading" ? ({
            className: "loadingText",
            text: "Loading ..."
          }) : ({
            className: "okText",
            text: "Data loaded from server"
          })
      ) : ({
        className: "errorText",
        text: `Request failed: ` + message._0
      });
    return <OverviewPage.make
      activeServer={activeServer()}
      healthText={healthText()}
      projectText={projectText()}
      sessionCount={sessions().length}
      projectCount={projects().length}
      lastEvent={Stdlib_Option.getOr(sync.lastEventKind(), "none")}
      runningSessionCount={countRunningSessions(sessionStatuses())}
      projects={overviewProjects}
      statusLine={overviewStatus}
    />;
  };
  let sessionsPage = param => <SessionsPage.make
    directoryDraft={sessionDirectoryDraft()}
    searchDraft={sessionSearchDraft()}
    limitDraft={sessionLimitDraft()}
    onDirectoryDraftChange={value => setSessionDirectoryDraft(param => value)}
    onSearchDraftChange={value => setSessionSearchDraft(param => value)}
    onLimitDraftChange={value => setSessionLimitDraft(param => value)}
    onApplyFilters={() => applySessionFilters()}
    onClearFilters={() => clearSessionFilters()}
    activeQueryText={renderSessionQuery(sessionQuery())}
    eventsList={<SessionsEventList.make
      sessions={sessions()}
      sessionStatuses={sessionStatuses()}
      sessionQuery={sessionQuery()}
    />}
  />;
  let reactivityProbePage = param => <ReactivityProbePage.make
    streamEventCount={streamEventCount()}
    recentEventCount={recentEvents().length}
    trackedMessageCount={trackedMessages().length}
    trackedPartCount={trackedParts().length}
    sessionCount={sessions().length}
    activeSessionId={focusedSessionId()}
  />;
  let dirIndexPage = param => {
    let params = Router.useParams();
    let dir = Stdlib_Option.getOr(params["dir"], "workspace");
    return <Router.Navigate
      href={`/` + dir + `/session`}
    />;
  };
  let sessionPage = param => {
    let params = Router.useParams();
    let dir = Stdlib_Option.getOr(params["dir"], "workspace");
    let sessionId = Stdlib_Option.getOr(params["id"], "latest");
    SolidJs.createEffect(() => {
      let id = params["id"];
      if (id !== undefined) {
        setFocusedSessionId(param => id);
        setComposerError(param => {});
        loadFocusedSessionById(id);
        return;
      } else {
        setFocusedSessionId(param => {});
        setFocusedSession(param => {});
        setFocusedSessionError(param => {});
        setComposerDraft(param => "");
        return setComposerError(param => {});
      }
    });
    let derived = SessionPageController.derive(sessionId, renderSessionQuery(sessionQuery()), sessions(), focusedSession(), sessionStatuses(), trackedQueueRequests().map(item => ({
      queue: item.queue,
      sessionId: item.sessionId
    })), trackedMessages().map(item => ({
      sessionId: item.sessionId,
      message: item.message
    })), trackedParts().map(item => ({
      sessionId: item.sessionId,
      messageId: item.messageId,
      streamedChars: item.streamedChars,
      text: item.text
    })), trackedTodos().map(item => ({
      sessionId: item.sessionId,
      todoCount: item.todos.length
    })), trackedDiffs().map(item => ({
      sessionId: item.sessionId,
      diffFileCount: item.diff.length
    })));
    let canSendComposer = derived.composerTargetSessionId !== "" && derived.composerTargetSessionId !== "latest";
    let sendComposer = async () => {
      let prompt = composerDraft().trim();
      if (prompt === "") {
        return;
      }
      if (!canSendComposer) {
        return setComposerError(param => "Select a concrete session before sending a prompt");
      }
      let localNonce = streamEventCount().toString() + `-` + derived.messagePartCount.toString() + `-` + prompt.length.toString();
      let localMessageId = `local-user-message-` + derived.composerTargetSessionId + `-` + localNonce;
      let localPartId = `local-user-part-` + localNonce;
      let optimisticMessage_sessionId = derived.composerTargetSessionId;
      let optimisticMessage_role = "UserRole";
      let optimisticMessage = {
        id: localMessageId,
        sessionId: optimisticMessage_sessionId,
        role: optimisticMessage_role
      };
      let optimisticPart_sessionId = derived.composerTargetSessionId;
      let optimisticPart_partType = "TextPart";
      let optimisticPart = {
        id: localPartId,
        sessionId: optimisticPart_sessionId,
        messageId: localMessageId,
        partType: optimisticPart_partType
      };
      setComposerError(param => {});
      setIsComposerSending(param => true);
      setTrackedMessages(items => upsertTrackedMessage(items, optimisticMessage));
      setTrackedParts(items => {
        let withPart = upsertTrackedPart(items, optimisticPart);
        return withPart.map(item => {
          if (item.sessionId !== derived.composerTargetSessionId || item.messageId !== localMessageId || item.part.id !== localPartId) {
            return item;
          }
          let match = item.text;
          if (match === "") {
            return {
              sessionId: item.sessionId,
              messageId: item.messageId,
              part: item.part,
              streamedChars: prompt.length,
              text: prompt
            };
          } else {
            return item;
          }
        });
      });
      setStoredPendingComposerText(derived.composerTargetSessionId, prompt);
      setComposerDraft(param => "");
      setFocusedSessionId(param => derived.composerTargetSessionId);
      loadFocusedSessionById(derived.composerTargetSessionId);
      refreshSessionSlice(sessionQuery());
      let value = normalizeQueryText(composerModelDraft());
      let model = value !== undefined ? resolveModelSelection(composerModelOptions(), value) : undefined;
      let error = await OpencodeClient.sendSessionTextMessage(client(), derived.composerTargetSessionId, prompt, model);
      if (error.TAG !== "Ok") {
        let error$1 = error._0;
        let sessionId = derived.composerTargetSessionId;
        setStoredPendingComposerText(sessionId, undefined);
        setComposerError(param => `Send failed: ` + OpencodeClient.errorToString(error$1));
      }
      return setIsComposerSending(param => false);
    };
    let composerModelSelectValue = () => {
      if (composerCustomModelEnabled()) {
        return customModelSentinel;
      }
      let value = normalizeQueryText(composerModelDraft());
      if (value !== undefined) {
        if (isKnownModelPreset(composerModelOptions(), value)) {
          return value;
        } else {
          return customModelSentinel;
        }
      } else {
        return "";
      }
    };
    let conversationPanelRows = () => derived.conversationRows.map(row => ({
      roleLabel: renderMessageRole(row.message.role),
      roleClass: messageRoleClass(row.message.role),
      messageId: row.message.id,
      text: row.text
    }));
    let composerViewModelOptions = () => composerModelOptions().map(option => ({
      value: option.value,
      label: option.label
    }));
    let onComposerSubmitFromKeyboard = () => {
      let canTrigger = !(isComposerSending() || composerDraft().trim() === "" || !canSendComposer);
      if (canTrigger) {
        sendComposer();
        return;
      }
    };
    let sidePanelSessionInfo = () => {
      let session = derived.displayedSession;
      if (session !== undefined) {
        return {
          id: session.id,
          title: Stdlib_Option.getOr(session.title, "Untitled"),
          updatedAt: Stdlib_Option.getOr(session.updatedAt, "Unknown"),
          status: renderSessionStatus(derived.effectiveRouteStatus)
        };
      }
    };
    let sidePanelProjects = () => projects().map(project => ({
      name: Stdlib_Option.getOr(project.name, "Unnamed project"),
      path: Stdlib_Option.getOr(project.path, "Path unavailable")
    }));
    let session = derived.displayedSession;
    let frameDisplayedSession = session !== undefined ? ({
        id: session.id,
        subtitle: renderSessionSubtitle(session)
      }) : undefined;
    let conversationPanel = <SessionConversationPanel.make
      rows={conversationPanelRows()}
    />;
    let composerRegion = <SessionComposerRegion.make
      modelSelectValue={composerModelSelectValue()}
      modelOptions={composerViewModelOptions()}
      customModelSentinel={customModelSentinel}
      customModelEnabled={composerCustomModelEnabled()}
      modelDraft={composerModelDraft()}
      onModelSelectionChange={value => {
        if (value === "") {
          setComposerCustomModelEnabled(param => false);
          return setComposerModelDraft(param => "");
        } else if (value === customModelSentinel) {
          return setComposerCustomModelEnabled(param => true);
        } else {
          setComposerCustomModelEnabled(param => false);
          return setComposerModelDraft(param => value);
        }
      }}
      onModelDraftInput={value => setComposerModelDraft(param => value)}
      composerDraft={composerDraft()}
      onComposerInput={value => setComposerDraft(param => value)}
      isSending={isComposerSending()}
      canSend={canSendComposer}
      onSend={() => {
        sendComposer();
      }}
      onClear={() => {
        setComposerDraft(param => "");
        setComposerError(param => {});
      }}
      onComposerSubmitFromKeyboard={() => onComposerSubmitFromKeyboard()}
      composerError={composerError()}
    />;
    let sidePanel = <SessionSidePanel.make
      serverLookupError={focusedSessionError()}
      recentEvents={recentEvents().map(renderObservedEvent)}
      sessionInfo={sidePanelSessionInfo()}
      contextLines={derived.contextLines}
      projectRows={sidePanelProjects()}
    />;
    return AppProviders.sessionProviders(<SessionPageFrame.make
      workspaceDirectory={dir}
      sessionRouteId={sessionId}
      statusText={renderSessionStatus(derived.effectiveRouteStatus)}
      displayedSession={frameDisplayedSession}
      hasSessionMetadata={derived.hasSessionMetadata}
      hasSessionActivity={derived.hasSessionActivity}
      conversationPanel={conversationPanel}
      composerRegion={composerRegion}
      sidePanel={sidePanel}
      backHref={"/sessions"}
    />);
  };
  let routedShell = <Router.Router
    root={rootLayout}
  >
    <Router.Route
      path={"/"}
      component={overviewPage}
    />
    <Router.Route
      path={"/sessions"}
      component={sessionsPage}
    />
    <Router.Route
      path={"/dev/reactivity"}
      component={reactivityProbePage}
    />
    <Router.Route
      path={"/:dir"}
    >
      <Router.Route
        path={"/"}
        component={dirIndexPage}
      />
      <Router.Route
        path={"/session/:id?"}
        component={sessionPage}
      />
    </Router.Route>
  </Router.Router>;
  let guardedShell = AppProviders.serverGate(activeServer, <GlobalSDKContext.make
    value={sdkValue}
  >
    <GlobalSyncContext.make
      client={client}
      onOpen={() => {
        setStreamStatus(param => "connected");
        setStreamError(param => {});
      }}
      onError={message => {
        setStreamStatus(param => "error");
        setStreamError(param => message);
      }}
      onEvent={event => {
        setStreamStatus(param => "connected");
        setStreamError(param => {});
        setStreamEventCount(prev => prev + 1 | 0);
        setStreamLastEventKind(param => OpencodeEvent.kind(event));
        GlobalEventReducer.apply(event, {
          refreshAll: () => {
            refreshData(sessionQuery());
          },
          refreshProjects: () => {
            refreshProjectSlice();
          },
          refreshSessions: () => {
            refreshSessionListSlice(sessionQuery());
          },
          refreshStatuses: () => {
            refreshSessionStatusesSlice(sessionQuery());
          },
          applySessionDeleted: applySessionDeleted,
          applySessionStatusChanged: applySessionStatusChanged,
          applySessionScoped: applySessionScoped,
          refreshSessionById: sessionId => {
            loadFocusedSessionById(sessionId);
          },
          activeSessionId: () => focusedSessionId(),
          onObservedEvent: appendObservedEvent
        });
      }}
    >
      {routedShell}
    </GlobalSyncContext.make>
  </GlobalSDKContext.make>);
  return AppProviders.appBaseProviders(<PlatformContext.make
    value={platformValue}
  >
    <ServerContext.make
      value={serverValue}
    >
      {guardedShell}
    </ServerContext.make>
  </PlatformContext.make>);
}

let make = App;

export {
  make,
}
/* AppShell Not a pure module */
