// Generated by ReScript, PLEASE EDIT WITH CARE

import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function appBaseProviders(children) {
  return <section
    className={"baseProviders"}
  >
    {children}
  </section>;
}

function appShellProviders(children) {
  return <section
    className={"shellProviders"}
  >
    {children}
  </section>;
}

function sessionProviders(children) {
  return <section
    className={"sessionProviders"}
  >
    {children}
  </section>;
}

let routerRoot = appShellProviders;

function serverGate(server, children) {
  if (server() === "") {
    return <section
      className={"panel"}
    >
      <p
        className={"errorText"}
      >
        {"No active server configured"}
      </p>
    </section>;
  } else {
    return children;
  }
}

export {
  appBaseProviders,
  appShellProviders,
  sessionProviders,
  routerRoot,
  serverGate,
}
/* @solidjs/h/jsx-runtime Not a pure module */
