// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as Router from "@solidjs/router";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function AppShell(props) {
  let onOpenUpstream = props.onOpenUpstream;
  let sidebarSessions = props.sidebarSessions;
  let sidebarMeta = sidebarSessions.length !== 0 ? sidebarSessions.length.toString() + ` recent` : "";
  return <main
    className={"appFrame"}
  >
    <header
      className={"titlebar"}
    >
      <div
        className={"titlebarWindow"}
      >
        <span
          className={"winDot red"}
        />
        <span
          className={"winDot yellow"}
        />
        <span
          className={"winDot green"}
        />
      </div>
      <div
        className={"titlebarCenter"}
      >
        <span
          className={"titlebarBrand"}
        >
          {"OpenCode"}
        </span>
        <input
          className={"titlebarSearch"}
          placeholder={"Search"}
          type={"text"}
        />
      </div>
      <div
        className={"titlebarActions"}
      >
        <span
          className={"titlePill"}
        />
        <span
          className={"titlePill"}
        />
        <span
          className={"titlePill"}
        />
      </div>
    </header>
    <div
      className={"appShell"}
    >
      <aside
        className={"sidebarShell"}
      >
        <nav
          className={"sidebarIconRail"}
        >
          <Router.A
            href={"/"}
            inactiveClass={"iconNavItem"}
            activeClass={"iconNavItem active"}
          >
            <span
              className={"railDot railDotOrange"}
            />
          </Router.A>
          <Router.A
            href={"/sessions"}
            inactiveClass={"iconNavItem"}
            activeClass={"iconNavItem active"}
          >
            <span
              className={"railDot railDotBlue"}
            />
          </Router.A>
          <Router.A
            href={"/workspace/session"}
            inactiveClass={"iconNavItem"}
            activeClass={"iconNavItem active"}
          >
            <span
              className={"railDot railDotGreen"}
            />
          </Router.A>
          <button
            className={"iconNavItem railAuxBtn"}
            onClick={param => onOpenUpstream()}
          >
            <span
              className={"railDot railDotNeutral"}
            />
          </button>
        </nav>
        <section
          className={"sidebarPanel"}
        >
          <header
            className={"sidebarPanelHeader"}
          >
            <div>
              <h3
                className={"sidebarSessionTitle"}
              >
                {"New session"}
              </h3>
              {sidebarMeta !== "" ? <p
                  className={"sidebarPanelMeta"}
                >
                  {sidebarMeta}
                </p> : <span />}
            </div>
          </header>
          <ul
            className={"sidebarSessionList"}
          >
            <SolidJs.For
              each={sidebarSessions}
              fallback={<li
                className={"sidebarSessionEmpty"}
              >
                {"No sessions yet"}
              </li>}
            >
              {(session, _index) => <li>
                <Router.A
                  href={session.href}
                  inactiveClass={"sidebarSessionItem"}
                  activeClass={"sidebarSessionItem active"}
                >
                  <span
                    className={session.isRunning ? "sidebarStatusDot running" : "sidebarStatusDot"}
                  />
                  <span
                    className={"sidebarSessionText"}
                  >
                    {session.id}
                  </span>
                </Router.A>
              </li>}
            </SolidJs.For>
          </ul>
        </section>
      </aside>
      <section
        className={"workspaceViewport"}
      >
        <div
          className={"routeViewport"}
        >
          {props.children}
        </div>
      </section>
    </div>
  </main>;
}

let make = AppShell;

export {
  make,
}
/* solid-js Not a pure module */
