// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as OpencodeEvent from "opencode-example-sdk/src/OpencodeEvent.mjs";
import * as ContextSupport from "./ContextSupport.mjs";
import * as OpencodeClient from "opencode-example-sdk/src/OpencodeClient.mjs";

function defaultValue_streamStatus() {
  return "disconnected";
}

function defaultValue_streamError() {
  
}

function defaultValue_eventCount() {
  return 0;
}

function defaultValue_lastEventKind() {
  
}

let defaultValue = {
  streamStatus: defaultValue_streamStatus,
  streamError: defaultValue_streamError,
  eventCount: defaultValue_eventCount,
  lastEventKind: defaultValue_lastEventKind
};

let context = SolidJs.createContext(defaultValue);

function use() {
  return SolidJs.useContext(context);
}

function GlobalSyncContext(props) {
  let __onEvent = props.onEvent;
  let __onError = props.onError;
  let __onOpen = props.onOpen;
  let client = props.client;
  let onOpen = __onOpen !== undefined ? __onOpen : () => {};
  let onError = __onError !== undefined ? __onError : param => {};
  let onEvent = __onEvent !== undefined ? __onEvent : param => {};
  let match = SolidJs.createSignal("disconnected");
  let setStreamStatus = match[1];
  let match$1 = SolidJs.createSignal(undefined);
  let setStreamError = match$1[1];
  let match$2 = SolidJs.createSignal(0);
  let setEventCount = match$2[1];
  let match$3 = SolidJs.createSignal(undefined);
  let setLastEventKind = match$3[1];
  SolidJs.createEffect(() => {
    let sdk = client();
    let subscription = OpencodeClient.subscribeGlobalEvents(sdk, event => {
      setStreamStatus(param => "connected");
      setStreamError(param => {});
      setEventCount(prev => prev + 1 | 0);
      setLastEventKind(param => OpencodeEvent.kind(event));
      onEvent(event);
    }, () => {
      setStreamStatus(param => "connected");
      setStreamError(param => {});
      onOpen();
    }, message => {
      setStreamStatus(param => "error");
      setStreamError(param => message);
      onError(message);
    }, undefined);
    SolidJs.onCleanup(() => OpencodeClient.closeSubscription(subscription));
  });
  let value_streamStatus = match[0];
  let value_streamError = match$1[0];
  let value_eventCount = match$2[0];
  let value_lastEventKind = match$3[0];
  let value = {
    streamStatus: value_streamStatus,
    streamError: value_streamError,
    eventCount: value_eventCount,
    lastEventKind: value_lastEventKind
  };
  let providerComponent = ContextSupport.provider(context);
  return providerComponent({
    value: value,
    children: props.children
  });
}

let make = GlobalSyncContext;

export {
  use,
  make,
}
/* context Not a pure module */
