// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as ContextSupport from "./ContextSupport.mjs";
import * as OpencodeClient from "opencode-example-sdk/src/OpencodeClient.mjs";

function defaultClient() {
  return OpencodeClient.make("", undefined, undefined, undefined);
}

let defaultValue = {
  client: defaultClient
};

let context = SolidJs.createContext(defaultValue);

function use() {
  return SolidJs.useContext(context);
}

function GlobalSDKContext(props) {
  let providerComponent = ContextSupport.provider(context);
  return providerComponent({
    value: props.value,
    children: props.children
  });
}

let make = GlobalSDKContext;

export {
  use,
  make,
}
/* context Not a pure module */
