// Generated by ReScript, PLEASE EDIT WITH CARE

import * as OpencodeEvent from "opencode-example-sdk/src/OpencodeEvent.mjs";

function apply(event, handlers) {
  let kind = OpencodeEvent.kindTag(event);
  let refreshPath = OpencodeEvent.refreshPath(event);
  let sessionId = OpencodeEvent.sessionId(event);
  handlers.onObservedEvent({
    kind: kind,
    refreshPath: refreshPath,
    sessionId: sessionId
  });
  if (typeof event !== "object") {
    if (event === "InvalidPayload") {
      return;
    } else {
      return handlers.refreshAll();
    }
  }
  switch (event.TAG) {
    case "ProjectUpdated" :
      return handlers.refreshProjects();
    case "SessionCreated" :
    case "SessionUpdated" :
    case "SessionEnded" :
      break;
    case "SessionDeleted" :
      return handlers.applySessionDeleted(event._0);
    case "SessionStatusChanged" :
      return handlers.applySessionStatusChanged(event._0);
    case "SessionScoped" :
      let payload = event._0;
      handlers.applySessionScoped(payload);
      handlers.refreshStatuses();
      let match = payload.sessionId;
      let match$1 = handlers.activeSessionId();
      if (match !== undefined && match$1 !== undefined && match === match$1) {
        return handlers.refreshSessionById(match);
      } else {
        return;
      }
    case "Unknown" :
      let type_ = event._0.type_;
      if (type_ === "session.deleted") {
        handlers.refreshSessions();
        return handlers.refreshStatuses();
      } else if (type_ === "session.status") {
        return handlers.refreshStatuses();
      } else {
        return;
      }
  }
  handlers.refreshSessions();
  handlers.refreshStatuses();
}

export {
  apply,
}
/* OpencodeEvent Not a pure module */
