// Generated by ReScript, PLEASE EDIT WITH CARE

import * as App from "./App.mjs";
import * as Document from "./Document.mjs";
import * as H from "solid-js/h";
import * as WebPlatform from "./WebPlatform.mjs";
import * as Web from "solid-js/web";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

function mount() {
  let root = Document.getElementById("app");
  if (root !== undefined) {
    let initialServer = WebPlatform.deriveDefaultServerUrl();
    Web.render(() => <App.make
      defaultServer={initialServer}
    />, Primitive_option.valFromOption(root));
    return;
  }
  console.error("Could not find root element");
}

mount();

export {
  mount,
}
/*  Not a pure module */
