// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Router from "@solidjs/router";

function OverviewPage(props) {
  let statusLine = props.statusLine;
  let projects = props.projects;
  let activeServer = props.activeServer;
  let displayedServer = activeServer.includes("localhost") ? "Local server" : activeServer;
  return <section
    className={"homePage"}
  >
    <div
      className={"homeLogoWrap"}
    >
      <h1
        className={"homeLogo"}
      >
        {"OpenCode"}
      </h1>
      <button
        className={"homeServerPill"}
        type={"button"}
      >
        <span
          className={statusLine.className === "okText" ? "homeServerDot ok" : (
              statusLine.className === "errorText" ? "homeServerDot error" : "homeServerDot"
            )}
        />
        {displayedServer}
      </button>
    </div>
    {projects.length !== 0 ? <div
        className={"homeRecentBlock"}
      >
        <div
          className={"homeRecentHeader"}
        >
          <h2>
            {"Recent projects"}
          </h2>
          <Router.A
            href={"/workspace/session"}
            inactiveClass={"homeRecentAction"}
            activeClass={"homeRecentAction"}
          >
            {"Open project"}
          </Router.A>
        </div>
        <ul
          className={"homeRecentList"}
        >
          <SolidJs.For
            each={projects}
            fallback={<span />}
          >
            {(project, _index) => <li
              className={"homeRecentItem"}
            >
              <Router.A
                href={"/workspace/session"}
                inactiveClass={"homeRecentPath"}
                activeClass={"homeRecentPath homeRecentPathActive"}
              >
                {project.label}
              </Router.A>
            </li>}
          </SolidJs.For>
        </ul>
      </div> : <div
        className={"homeEmptyState"}
      >
        <span
          className={"homeEmptyIcon"}
        >
          {"+"}
        </span>
        <h2>
          {"No projects yet"}
        </h2>
        <p>
          {"Open a directory to start a new session."}
        </p>
        <Router.A
          href={"/workspace/session"}
          inactiveClass={"homePrimaryAction"}
          activeClass={"homePrimaryAction"}
        >
          {"Open project"}
        </Router.A>
      </div>}
    {statusLine.className === "errorText" ? <p
        className={statusLine.className}
      >
        {statusLine.text}
      </p> : <span />}
  </section>;
}

let make = OverviewPage;

export {
  make,
}
/* solid-js Not a pure module */
