// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as WebPlatform from "./WebPlatform.mjs";
import * as ContextSupport from "./ContextSupport.mjs";

function defaultValue_openLink(param) {
  
}

function defaultValue_back() {
  
}

function defaultValue_forward() {
  
}

function defaultValue_restart() {
  
}

function defaultValue_getDefaultServerUrl() {
  
}

function defaultValue_setDefaultServerUrl(param) {
  
}

let defaultValue = {
  platform: "web",
  version: undefined,
  openLink: defaultValue_openLink,
  back: defaultValue_back,
  forward: defaultValue_forward,
  restart: defaultValue_restart,
  getDefaultServerUrl: defaultValue_getDefaultServerUrl,
  setDefaultServerUrl: defaultValue_setDefaultServerUrl
};

let context = SolidJs.createContext(defaultValue);

function web(version, param) {
  let history = window.history;
  let location = window.location;
  return {
    platform: "web",
    version: version,
    openLink: url => {
      window.open(url, "_blank");
    },
    back: () => {
      history.back();
    },
    forward: () => {
      history.forward();
    },
    restart: () => {
      location.reload();
    },
    getDefaultServerUrl: () => WebPlatform.getDefaultServerUrl(),
    setDefaultServerUrl: WebPlatform.setDefaultServerUrl
  };
}

function use() {
  return SolidJs.useContext(context);
}

function PlatformContext(props) {
  let providerComponent = ContextSupport.provider(context);
  return providerComponent({
    value: props.value,
    children: props.children
  });
}

let make = PlatformContext;

export {
  web,
  use,
  make,
}
/* context Not a pure module */
