// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as Belt_Array from "@rescript/runtime/lib/es6/Belt_Array.mjs";
import * as H from "solid-js/h";
import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";

function ReactivityProbePage(props) {
  let match = SolidJs.createSignal([0]);
  let setSamples = match[1];
  let buildChunk = (_size, _next, _acc) => {
    while (true) {
      let acc = _acc;
      let next = _next;
      let size = _size;
      if (size <= 0) {
        return acc;
      }
      _acc = acc.concat([next]);
      _next = next + 1 | 0;
      _size = size - 1 | 0;
      continue;
    };
  };
  let burst = size => setSamples(items => {
    let base = items.length;
    let nextChunk = buildChunk(size, base + 1 | 0, []);
    return items.concat(nextChunk);
  });
  let reverseOrder = () => setSamples(items => Stdlib_Array.reduce(items, [], (acc, item) => Belt_Array.concatMany([
    [item],
    acc
  ])));
  let pruneHalf = () => setSamples(items => {
    let keepNext = {
      contents: true
    };
    return items.filter(param => {
      let keep = keepNext.contents;
      keepNext.contents = !keepNext.contents;
      return keep;
    });
  });
  return <section
    className={"panel sessionsPanel"}
  >
    <h2>
      {"Reactivity Probe"}
    </h2>
    <p
      className={"sessionRoute"}
    >
      {"Stress helper for For/Show update behavior while stream events are flowing through the app."}
    </p>
    <ul
      className={"summaryList"}
    >
      <li>
        <strong>
          {"Stream events"}
        </strong>
        <span>
          {props.streamEventCount.toString()}
        </span>
      </li>
      <li>
        <strong>
          {"Recent reducer events"}
        </strong>
        <span>
          {props.recentEventCount.toString()}
        </span>
      </li>
      <li>
        <strong>
          {"Tracked messages"}
        </strong>
        <span>
          {props.trackedMessageCount.toString()}
        </span>
      </li>
      <li>
        <strong>
          {"Tracked parts"}
        </strong>
        <span>
          {props.trackedPartCount.toString()}
        </span>
      </li>
      <li>
        <strong>
          {"Sessions in memory"}
        </strong>
        <span>
          {props.sessionCount.toString()}
        </span>
      </li>
      <li>
        <strong>
          {"Active session id"}
        </strong>
        <span>
          {Stdlib_Option.getOr(props.activeSessionId, "none")}
        </span>
      </li>
    </ul>
    <div
      className={"queryActions"}
    >
      <button
        className={"refreshBtn"}
        onClick={param => burst(50)}
      >
        {"Burst +50"}
      </button>
      <button
        className={"refreshBtn"}
        onClick={param => burst(200)}
      >
        {"Burst +200"}
      </button>
      <button
        className={"ghostBtn"}
        onClick={param => reverseOrder()}
      >
        {"Reverse"}
      </button>
      <button
        className={"ghostBtn"}
        onClick={param => pruneHalf()}
      >
        {"Prune half"}
      </button>
      <button
        className={"ghostBtn"}
        onClick={param => setSamples(param => [])}
      >
        {"Clear"}
      </button>
    </div>
    <ul
      className={"eventList"}
    >
      <SolidJs.For
        each={match[0]()}
        fallback={<li
          className={"eventRow"}
        >
          {"No local samples"}
        </li>}
      >
        {(sample, _index) => <li
          className={"eventRow"}
        >
          <span
            className={"eventKind"}
          >
            {`sample-` + sample.toString()}
          </span>
          <span
            className={"sessionMeta"}
          >
            {"local reactive row"}
          </span>
        </li>}
      </SolidJs.For>
    </ul>
  </section>;
}

let make = ReactivityProbePage;

export {
  make,
}
/* solid-js Not a pure module */
