// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as ContextSupport from "./ContextSupport.mjs";

function emptyValue_activeServer() {
  return "";
}

function emptyValue_serverDraft() {
  return "";
}

function emptyValue_setServerDraft(param) {
  
}

function emptyValue_applyServer() {
  
}

function emptyValue_resetServer() {
  
}

function emptyValue_refresh() {
  
}

let emptyValue = {
  activeServer: emptyValue_activeServer,
  serverDraft: emptyValue_serverDraft,
  setServerDraft: emptyValue_setServerDraft,
  applyServer: emptyValue_applyServer,
  resetServer: emptyValue_resetServer,
  refresh: emptyValue_refresh
};

let context = SolidJs.createContext(emptyValue);

function use() {
  return SolidJs.useContext(context);
}

function ServerContext(props) {
  let providerComponent = ContextSupport.provider(context);
  return providerComponent({
    value: props.value,
    children: props.children
  });
}

let make = ServerContext;

export {
  use,
  make,
}
/* context Not a pure module */
