// Generated by ReScript, PLEASE EDIT WITH CARE

import * as H from "solid-js/h";

function SessionsPage(props) {
  let onClearFilters = props.onClearFilters;
  let onApplyFilters = props.onApplyFilters;
  let onLimitDraftChange = props.onLimitDraftChange;
  let onSearchDraftChange = props.onSearchDraftChange;
  let onDirectoryDraftChange = props.onDirectoryDraftChange;
  return <section
    className={"panel sessionsPanel"}
  >
    <h2>
      {"Sessions"}
    </h2>
    <div
      className={"queryGrid"}
    >
      <label>
        <span>
          {"Directory"}
        </span>
        <input
          id={"sessions-directory-filter"}
          placeholder={"workspace"}
          type={"text"}
          value={props.directoryDraft}
          onInput={event => onDirectoryDraftChange(event.target.value)}
        />
      </label>
      <label>
        <span>
          {"Search"}
        </span>
        <input
          id={"sessions-search-filter"}
          placeholder={"title text"}
          type={"text"}
          value={props.searchDraft}
          onInput={event => onSearchDraftChange(event.target.value)}
        />
      </label>
      <label>
        <span>
          {"Limit"}
        </span>
        <input
          id={"sessions-limit-filter"}
          min={"1"}
          placeholder={"25"}
          type={"number"}
          value={props.limitDraft}
          onInput={event => onLimitDraftChange(event.target.value)}
        />
      </label>
    </div>
    <div
      className={"queryActions"}
    >
      <button
        className={"refreshBtn"}
        id={"sessions-apply-filters-btn"}
        onClick={param => onApplyFilters()}
      >
        {"Apply filters"}
      </button>
      <button
        className={"ghostBtn"}
        id={"sessions-clear-filters-btn"}
        onClick={param => onClearFilters()}
      >
        {"Clear"}
      </button>
      <span
        className={"streamMeta"}
      >
        {`Active query: ` + props.activeQueryText}
      </span>
    </div>
    {props.eventsList}
  </section>;
}

let make = SessionsPage;

export {
  make,
}
/* solid-js/h Not a pure module */
