// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Router from "@solidjs/router";

function SessionPageFrame(props) {
  let sidePanel = props.sidePanel;
  let displayedSession = props.displayedSession;
  let statusText = props.statusText;
  let sessionRouteId = props.sessionRouteId;
  let match = SolidJs.createSignal(false);
  let setIsMobileLayout = match[1];
  let match$1 = SolidJs.createSignal("Main");
  let setActiveMobileTab = match$1[1];
  let activeMobileTab = match$1[0];
  SolidJs.onMount(() => {
    let mediaQuery = window.matchMedia("(max-width: 960px)");
    let syncMobileLayout = () => {
      let isMobile = mediaQuery.matches();
      setIsMobileLayout(param => isMobile);
      if (!isMobile) {
        return setActiveMobileTab(param => "Main");
      }
    };
    syncMobileLayout();
    mediaQuery.addEventListener("change", syncMobileLayout);
    SolidJs.onCleanup(() => {
      mediaQuery.removeEventListener("change", syncMobileLayout);
    });
  });
  let statusClass;
  switch (statusText) {
    case "idle" :
      statusClass = "sessionStatusPill";
      break;
    case "running" :
      statusClass = "sessionStatusPill running";
      break;
    default:
      statusClass = "";
  }
  let headerStatusElement = displayedSession !== undefined ? <p
      className={"sessionTopSubtitle"}
    >
      {displayedSession.subtitle}
    </p> : <span />;
  let sessionMainStack = <div
    className={"sessionMainStack"}
  >
    {props.conversationPanel}
    {props.composerRegion}
  </div>;
  let sessionBodyElement;
  if (match[0]()) {
    let match$2 = activeMobileTab();
    let tmp;
    tmp = match$2 === "Main" ? sessionMainStack : sidePanel;
    sessionBodyElement = <div
      className={"sessionMobileLayout"}
    >
      <div
        className={"sessionMobileTabs"}
      >
        <button
          className={activeMobileTab() === "Main" ? "sessionMobileTabBtn active" : "sessionMobileTabBtn"}
          type={"button"}
          onClick={param => setActiveMobileTab(param => "Main")}
        >
          {"Session"}
        </button>
        <button
          className={activeMobileTab() === "Side" ? "sessionMobileTabBtn active" : "sessionMobileTabBtn"}
          type={"button"}
          onClick={param => setActiveMobileTab(param => "Side")}
        >
          {"Side Panel"}
        </button>
      </div>
      <div
        className={"sessionBody"}
      >
        {tmp}
      </div>
    </div>;
  } else {
    sessionBodyElement = <div
      className={"sessionBody"}
    >
      {sessionMainStack}
      {sidePanel}
    </div>;
  }
  return <section
    className={"sessionView"}
  >
    <header
      className={"sessionTopBar"}
    >
      <div
        className={"sessionTopMain"}
      >
        <div
          className={"sessionTopTitleRow"}
        >
          <h2>
            {props.workspaceDirectory}
          </h2>
          {statusClass !== "" ? <span
              className={statusClass}
            >
              {statusText}
            </span> : <span />}
        </div>
        <p
          className={"sessionTopSubtitle"}
        >
          {sessionRouteId === "latest" ? "new session" : `session/` + sessionRouteId}
        </p>
        {headerStatusElement}
      </div>
      <Router.A
        href={props.backHref}
        inactiveClass={"inlineLink sessionBackLink"}
        activeClass={"inlineLink sessionBackLink"}
      >
        {"Back"}
      </Router.A>
    </header>
    {sessionBodyElement}
  </section>;
}

let make = SessionPageFrame;

export {
  make,
}
/* solid-js Not a pure module */
