// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function SessionSidePanel(props) {
  let projectRows = props.projectRows;
  let recentEvents = props.recentEvents;
  let serverLookupError = props.serverLookupError;
  let match = SolidJs.createSignal("Unified");
  let setReviewMode = match[1];
  let reviewMode = match[0];
  let match$1 = SolidJs.createSignal(false);
  let setReviewCollapsed = match$1[1];
  let reviewCollapsed = match$1[0];
  let match$2 = SolidJs.createSignal("ReviewTab");
  let setActiveTab = match$2[1];
  let activeTab = match$2[0];
  let reviewRows = recentEvents.map((line, index) => {
    let number = index + 1 | 0;
    return {
      id: number,
      text: line
    };
  });
  let reviewContent = reviewCollapsed() ? <p
      className={"loadingText"}
    >
      {"Review rows collapsed. Expand to inspect changes."}
    </p> : (
      reviewRows.length !== 0 ? <ul
          className={"reviewEventList"}
        >
          <SolidJs.For
            each={reviewRows}
            fallback={<li
              className={"reviewEventRow"}
            >
              {"No activity yet"}
            </li>}
          >
            {(row, _index) => <li
              className={"reviewEventRow"}
            >
              <span
                className={"reviewEventLineNo"}
              >
                {row.id.toString()}
              </span>
              <span
                className={"reviewEventText"}
              >
                {row.text}
              </span>
            </li>}
          </SolidJs.For>
        </ul> : <p
          className={"loadingText"}
        >
          {"No activity yet. Events appear here after the next stream update."}
        </p>
    );
  let filesContent = projectRows.length !== 0 ? <ul
      className={"sideProjectList"}
    >
      <SolidJs.For
        each={projectRows}
        fallback={<li
          className={"sideProjectRow"}
        >
          {"No files yet"}
        </li>}
      >
        {(row, _index) => <li
          className={"sideProjectRow"}
        >
          <span
            className={"eventKind"}
          >
            {row.name}
          </span>
          <span
            className={"sessionMeta"}
          >
            {row.path}
          </span>
        </li>}
      </SolidJs.For>
    </ul> : <p
      className={"loadingText"}
    >
      {"No files available for this session yet."}
    </p>;
  let match$3 = activeTab();
  let tmp;
  tmp = match$3 === "ReviewTab" ? recentEvents.length.toString() : projectRows.length.toString();
  let match$4 = activeTab();
  let tmp$1;
  tmp$1 = match$4 === "ReviewTab" ? <div
      className={"reviewPaneControls"}
    >
      <p
        className={"sessionRoute"}
      >
        {"Session changes"}
      </p>
      <div
        className={"reviewPaneControlActions"}
      >
        <button
          className={reviewMode() === "Unified" ? "reviewModeBtn active" : "reviewModeBtn"}
          type={"button"}
          onClick={param => setReviewMode(param => "Unified")}
        >
          {"Unified"}
        </button>
        <button
          className={reviewMode() === "Split" ? "reviewModeBtn active" : "reviewModeBtn"}
          type={"button"}
          onClick={param => setReviewMode(param => "Split")}
        >
          {"Split"}
        </button>
        <button
          className={"reviewModeBtn"}
          type={"button"}
          onClick={param => setReviewCollapsed(prev => !prev)}
        >
          {(
            reviewCollapsed() ? "Expand all" : "Collapse all"
          )}
        </button>
      </div>
    </div> : <p
      className={"sessionRoute"}
    >
      {"Session files and workspace paths"}
    </p>;
  let match$5 = activeTab();
  let tmp$2;
  tmp$2 = match$5 === "ReviewTab" ? reviewContent : filesContent;
  return <aside
    className={"sessionSideRail"}
  >
    <section
      className={reviewMode() === "Split" ? "sideCard reviewPane split" : "sideCard reviewPane unified"}
    >
      <header
        className={"reviewPaneHeader"}
      >
        <div
          className={"reviewPaneTabs"}
        >
          <button
            className={activeTab() === "ReviewTab" ? "reviewTabBtn active" : "reviewTabBtn"}
            type={"button"}
            onClick={param => setActiveTab(param => "ReviewTab")}
          >
            {"Review"}
          </button>
          <button
            className={activeTab() === "FilesTab" ? "reviewTabBtn active" : "reviewTabBtn"}
            type={"button"}
            onClick={param => setActiveTab(param => "FilesTab")}
          >
            {"Files"}
          </button>
        </div>
        <span
          className={"badge"}
        >
          {tmp}
        </span>
      </header>
      {tmp$1}
      {serverLookupError !== undefined ? <p
          className={"errorText"}
        >
          {`Server lookup failed: ` + serverLookupError}
        </p> : <span />}
      {tmp$2}
    </section>
  </aside>;
}

let make = SessionSidePanel;

export {
  make,
}
/* solid-js Not a pure module */
