// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Array from "@rescript/runtime/lib/es6/Stdlib_Array.mjs";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.mjs";

function reverseItems(items) {
  return Stdlib_Array.reduce(items, [], (acc, item) => [item].concat(acc));
}

function findSessionStatus(items, sessionId) {
  return Stdlib_Array.reduce(items, undefined, (found, item) => {
    if (found !== undefined) {
      return found;
    } else if (item.id === sessionId) {
      return item.status;
    } else {
      return;
    }
  });
}

function countRunningSessions(items) {
  return Stdlib_Array.reduce(items, 0, (count, item) => {
    let match = item.status;
    if (match === "running") {
      return count + 1 | 0;
    } else {
      return count;
    }
  });
}

function countTrackedQueueRequests(items, sessionId, queue) {
  return Stdlib_Array.reduce(items, 0, (count, item) => {
    if (item.queue === queue && item.sessionId === sessionId) {
      return count + 1 | 0;
    } else {
      return count;
    }
  });
}

function trackedTodoCountForSession(items, sessionId) {
  return Stdlib_Option.getOr(Stdlib_Array.findMap(items, item => {
    if (item.sessionId === sessionId) {
      return item.todoCount;
    }
  }), 0);
}

function trackedDiffFileCountForSession(items, sessionId) {
  return Stdlib_Option.getOr(Stdlib_Array.findMap(items, item => {
    if (item.sessionId === sessionId) {
      return item.diffFileCount;
    }
  }), 0);
}

function renderTrackedPartFragment(part) {
  let match = part.text.trim();
  if (match === "") {
    if (part.streamedChars > 0) {
      return `[streaming ` + part.streamedChars.toString() + ` chars]`;
    } else {
      return "";
    }
  } else {
    return part.text;
  }
}

function combineTrackedPartText(parts) {
  return Stdlib_Array.reduce(parts, "", (combined, part) => {
    let fragment = renderTrackedPartFragment(part);
    if (fragment === "") {
      return combined;
    } else if (combined === "") {
      return fragment;
    } else {
      return combined + `\n` + fragment;
    }
  });
}

function derive(sessionId, sessionQueryText, sessions, focusedSession, sessionStatuses, trackedQueueRequests, trackedMessages, trackedParts, trackedTodos, trackedDiffs) {
  let selected = Stdlib_Array.reduce(sessions, undefined, (found, item) => {
    if (found !== undefined) {
      return found;
    } else if (item.id === sessionId) {
      return item;
    } else {
      return;
    }
  });
  let focusedMatch = focusedSession !== undefined && (sessionId === "latest" || focusedSession.id === sessionId) ? focusedSession : undefined;
  let hasSessionMetadata = Stdlib_Option.isSome(selected) || Stdlib_Option.isSome(focusedMatch);
  let displayedSession = selected !== undefined ? selected : (
      focusedMatch !== undefined ? focusedMatch : (
          sessionId === "latest" ? undefined : ({
              id: sessionId,
              title: undefined,
              updatedAt: undefined
            })
        )
    );
  let counterSessionId = sessionId === "latest" && displayedSession !== undefined ? displayedSession.id : sessionId;
  let pendingPermissionCount = countTrackedQueueRequests(trackedQueueRequests, counterSessionId, "permission");
  let pendingQuestionCount = countTrackedQueueRequests(trackedQueueRequests, counterSessionId, "question");
  let sessionMessages = trackedMessages.filter(item => item.sessionId === counterSessionId);
  let sessionParts = trackedParts.filter(item => item.sessionId === counterSessionId);
  let trackedTodoCount = trackedTodoCountForSession(trackedTodos, counterSessionId);
  let trackedDiffFileCount = trackedDiffFileCountForSession(trackedDiffs, counterSessionId);
  let messageCount = sessionMessages.length;
  let messagePartCount = sessionParts.length;
  let streamedCharCount = Stdlib_Array.reduce(sessionParts, 0, (count, item) => count + item.streamedChars | 0);
  let routeStatus = findSessionStatus(sessionStatuses, counterSessionId);
  let hasSessionActivity = Stdlib_Option.isSome(routeStatus) || pendingPermissionCount > 0 || pendingQuestionCount > 0 || trackedTodoCount > 0 || trackedDiffFileCount > 0 || messageCount > 0 || messagePartCount > 0 || streamedCharCount > 0;
  let effectiveRouteStatus = routeStatus !== undefined ? routeStatus : (
      hasSessionActivity ? "running" : undefined
    );
  let knownMessages = sessionMessages.map(item => item.message);
  let mergedMessages = Stdlib_Array.reduce(sessionParts, knownMessages, (messages, part) => {
    let exists = messages.some(message => message.id === part.messageId);
    if (exists) {
      return messages;
    }
    let inferredMessage_id = part.messageId;
    let inferredMessage_sessionId = part.sessionId;
    let inferredMessage = {
      id: inferredMessage_id,
      sessionId: inferredMessage_sessionId,
      role: undefined
    };
    return [inferredMessage].concat(messages);
  });
  let conversationRows = reverseItems(mergedMessages).map(message => {
    let messageParts = reverseItems(sessionParts.filter(part => part.messageId === message.id));
    let combinedText = combineTrackedPartText(messageParts);
    let match = combinedText.trim();
    let tmp = match === "" ? "[awaiting streamed content]" : combinedText;
    return {
      message: message,
      text: tmp,
      partCount: messageParts.length
    };
  }).filter(row => {
    if (row.partCount > 0) {
      return true;
    } else {
      return row.message.role !== undefined;
    }
  });
  let contextLines = [
    `Filter scope: ` + sessionQueryText,
    `Known sessions: ` + sessions.length.toString(),
    `Running sessions: ` + countRunningSessions(sessionStatuses).toString(),
    `Pending permissions: ` + pendingPermissionCount.toString(),
    `Pending questions: ` + pendingQuestionCount.toString(),
    `Todos tracked: ` + trackedTodoCount.toString(),
    `Diff files tracked: ` + trackedDiffFileCount.toString(),
    `Messages tracked: ` + messageCount.toString(),
    `Message parts tracked: ` + messagePartCount.toString(),
    `Streamed chars: ` + streamedCharCount.toString()
  ];
  return {
    displayedSession: displayedSession,
    hasSessionMetadata: hasSessionMetadata,
    composerTargetSessionId: counterSessionId,
    pendingPermissionCount: pendingPermissionCount,
    pendingQuestionCount: pendingQuestionCount,
    trackedTodoCount: trackedTodoCount,
    trackedDiffFileCount: trackedDiffFileCount,
    messageCount: messageCount,
    messagePartCount: messagePartCount,
    streamedCharCount: streamedCharCount,
    routeStatus: routeStatus,
    effectiveRouteStatus: effectiveRouteStatus,
    hasSessionActivity: hasSessionActivity,
    conversationRows: conversationRows,
    contextLines: contextLines
  };
}

export {
  derive,
}
/* No side effect */
