// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function SessionConversationPanel(props) {
  let rows = props.rows;
  return <section
    className={"sessionConversationPanel"}
  >
    <header
      className={"chatMetaRow"}
    >
      <p
        className={"sessionRoute"}
      >
        {"Timeline"}
      </p>
      <span
        className={"terminalPartMeta"}
      >
        {"Session events and assistant turns"}
      </span>
    </header>
    <div
      className={"sessionChatPanel"}
    >
      {rows.length !== 0 ? <ul
          className={"chatList"}
        >
          <SolidJs.For
            each={rows}
            fallback={<li
              className={"loadingText"}
            >
              {"No timeline entries yet"}
            </li>}
          >
            {(row, _index) => <li
              className={`chatRow ` + row.roleClass}
            >
              <div
                className={"chatMetaRow"}
              >
                <span
                  className={"chatRole"}
                >
                  {row.roleLabel}
                </span>
                <span
                  className={"terminalPartMeta"}
                >
                  {row.messageId}
                </span>
              </div>
              <pre
                className={"chatBubbleText"}
              >
                {row.text}
              </pre>
            </li>}
          </SolidJs.For>
        </ul> : <div
          className={"sessionTimelineEmpty"}
        >
          <div>
            <p
              className={"loadingText"}
            >
              {"No messages in this session yet."}
            </p>
            <pre
              className={"terminalStub"}
            >
              {"$ send a prompt to begin the timeline"}
            </pre>
          </div>
        </div>}
    </div>
  </section>;
}

let make = SessionConversationPanel;

export {
  make,
}
/* solid-js Not a pure module */
