// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function SessionComposerRegion(props) {
  let composerError = props.composerError;
  let onComposerSubmitFromKeyboard = props.onComposerSubmitFromKeyboard;
  let onClear = props.onClear;
  let onSend = props.onSend;
  let isSending = props.isSending;
  let onComposerInput = props.onComposerInput;
  let composerDraft = props.composerDraft;
  let onModelDraftInput = props.onModelDraftInput;
  let onModelSelectionChange = props.onModelSelectionChange;
  return <section
    className={"sessionComposerDock"}
  >
    <header>
      <p
        className={"sessionRoute"}
      >
        {"Composer"}
      </p>
      <p
        className={"composerModelHint"}
      >
        {"Draft the next turn, then send or clear this session input."}
      </p>
    </header>
    <div
      className={"composerModelRow"}
    >
      <p
        className={"sessionRoute"}
      >
        {"Model override"}
      </p>
      <select
        className={"composerModelSelect"}
        id={"composer-model-select"}
        value={props.modelSelectValue}
        onInput={event => onModelSelectionChange(event.target.value)}
      >
        <option
          value={""}
        >
          {"Default (session model)"}
        </option>
        <SolidJs.For
          each={props.modelOptions}
          fallback={<option
            value={""}
          >
            {"No models available"}
          </option>}
        >
          {(option, _index) => <option
            value={option.value}
          >
            {option.label}
          </option>}
        </SolidJs.For>
        <option
          value={props.customModelSentinel}
        >
          {"Custom model..."}
        </option>
      </select>
      {props.customModelEnabled ? <input
          className={"composerModelInput"}
          id={"composer-model-input"}
          placeholder={"e.g. anthropic/claude-sonnet-4-5"}
          value={props.modelDraft}
          onInput={event => onModelDraftInput(event.target.value)}
        /> : <p
          className={"sessionRoute composerModelHint"}
        >
          {"Use the session default, choose a preset, or provide a custom model id."}
        </p>}
    </div>
    <textarea
      className={"composerInput"}
      placeholder={"Ask OpenCode to continue this session..."}
      value={composerDraft}
      onKeyDown={event => {
        let key = event.key;
        if (key === "Enter" && !event.shiftKey) {
          event.preventDefault();
          return onComposerSubmitFromKeyboard();
        }
      }}
      onInput={event => onComposerInput(event.target.value)}
    />
    <div
      className={"queryActions"}
    >
      <button
        className={"refreshBtn"}
        id={"composer-send-btn"}
        disabled={isSending || composerDraft.trim() === "" || !props.canSend}
        onClick={param => onSend()}
      >
        {isSending ? "Sending..." : "Send"}
      </button>
      <button
        className={"ghostBtn"}
        id={"composer-clear-btn"}
        disabled={isSending || composerDraft === ""}
        onClick={param => onClear()}
      >
        {"Clear"}
      </button>
    </div>
    {composerError !== undefined ? <p
        className={"errorText"}
      >
        {composerError}
      </p> : <p
        className={"composerModelHint"}
      >
        {"Press Enter to send and Shift+Enter for a new line."}
      </p>}
  </section>;
}

let make = SessionComposerRegion;

export {
  make,
}
/* solid-js Not a pure module */
