// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

let defaultServerStorageKey = "opencode.settings.dat:defaultServerUrl";

function getDefaultServerUrl() {
  let storage = Primitive_option.fromNullable(window.localStorage);
  if (storage === undefined) {
    return;
  }
  try {
    let url = Primitive_option.valFromOption(storage).getItem(defaultServerStorageKey);
    if (url == null) {
      return;
    }
    let normalized = url.trim();
    if (normalized === "") {
      return;
    } else {
      return normalized;
    }
  } catch (exn) {
    return;
  }
}

function setDefaultServerUrl(value) {
  let normalized = value.trim();
  let storage = Primitive_option.fromNullable(window.localStorage);
  if (storage === undefined) {
    return;
  }
  let storage$1 = Primitive_option.valFromOption(storage);
  if (normalized === "") {
    try {
      storage$1.removeItem(defaultServerStorageKey);
      return;
    } catch (exn) {
      return;
    }
  } else {
    try {
      storage$1.setItem(defaultServerStorageKey, normalized);
      return;
    } catch (exn$1) {
      return;
    }
  }
}

function deriveDefaultServerUrl() {
  let url = getDefaultServerUrl();
  if (url !== undefined) {
    return url;
  } else if (location.hostname.includes("opencode.ai") || location.hostname === "localhost" || location.hostname === "127.0.0.1") {
    return "http://localhost:4096";
  } else {
    return location.origin;
  }
}

export {
  defaultServerStorageKey,
  getDefaultServerUrl,
  setDefaultServerUrl,
  deriveDefaultServerUrl,
}
/* No side effect */
