// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJSX from "rescript-solid/src/SolidJSX.mjs";
import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function DeferRepro(props) {
  let match = SolidJs.createSignal(0);
  let count = match[0];
  return <div>
    <p>
      {"Probe"}
    </p>
    {SolidJSX.ppxDefer(() => <p>
      {"Deferred count: " + count().toString()}
    </p>)}
  </div>;
}

let make = DeferRepro;

export {
  make,
}
/* SolidJSX Not a pure module */
