// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function DeferRepro(props) {
  let match = SolidJs.createSignal(0);
  return <div>
    <p>
      {"Probe"}
    </p>
    <p>
      {"Deferred count: " + match[0]().toString()}
    </p>
  </div>;
}

let make = DeferRepro;

export {
  make,
}
/* solid-js Not a pure module */
