// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as JsxRuntime from "@solidjs/h/jsx-runtime";

function PpxSmoke(props) {
  let match = SolidJs.createSignal(2);
  let count = match[0];
  let maybeLabel = SolidJs.createMemo(() => {
    if (count() % 2 === 0) {
      return "even";
    }
  });
  let label = maybeLabel();
  let deferredLabel = label !== undefined ? "label: " + label + ", n=" + count().toString() : "label: odd";
  return <section>
    <p>
      {"PPX smoke"}
    </p>
    <p>
      {deferredLabel}
    </p>
    <p>
      {"Deferred JSX value: " + count().toString()}
    </p>
  </section>;
}

let make = PpxSmoke;

export {
  make,
}
/* solid-js Not a pure module */
