// Generated by ReScript, PLEASE EDIT WITH CARE


let Router = {};

let Routes = {};

let Route = {};

let RouteEl = {};

let RouterRoot = {};

let HashRouter = {};

let MemoryRouter = {};

let Link = {};

let Navigate = {};

let A = {};

export {
  Router,
  Routes,
  Route,
  RouteEl,
  RouterRoot,
  HashRouter,
  MemoryRouter,
  Link,
  Navigate,
  A,
}
/* No side effect */
