// Generated by ReScript, PLEASE EDIT WITH CARE


let Router = {};

let Route = {};

let RouteEl = {};

let RouterRoot = {};

let HashRouter = {};

let MemoryRouter = {};

let Link = {};

let Navigate = {};

let Data = {};

function MakeParams(P) {
  return {};
}

function MakeSearchParams(S) {
  return {};
}

function MakeAction(A) {
  return {};
}

let A = {};

export {
  Router,
  Route,
  RouteEl,
  RouterRoot,
  HashRouter,
  MemoryRouter,
  Link,
  Navigate,
  Data,
  MakeParams,
  MakeSearchParams,
  MakeAction,
  A,
}
/* No side effect */
