// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function Counter(props) {
  let __initialCount = props.initialCount;
  let initialCount = __initialCount !== undefined ? __initialCount : 0;
  let match = SolidJs.createSignal(initialCount);
  let setCount = match[1];
  let count = match[0];
  let increment = param => setCount(prev => prev + 1 | 0);
  let decrement = param => setCount(prev => prev - 1 | 0);
  let reset = param => setCount(param => initialCount);
  let doubleCount = SolidJs.createMemo(() => (count() << 1));
  return <div>
    <h2>
      {"Counter Component"}
    </h2>
    <p>
      {"Count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <p>
      {"Double: "}
      <strong>
        {doubleCount()}
      </strong>
    </p>
    <div>
      <button
        onClick={decrement}
      >
        {"Decrement"}
      </button>
      <button
        onClick={reset}
      >
        {"Reset"}
      </button>
      <button
        onClick={increment}
      >
        {"Increment"}
      </button>
    </div>
  </div>;
}

let make = Counter;

export {
  make,
}
/* solid-js Not a pure module */
