// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.mjs";

function getElementById(id) {
  return Primitive_option.fromNullable(document.getElementById(id));
}

export {
  getElementById,
}
/* No side effect */
