// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Document from "./Document.mjs";
import * as SolidJs from "solid-js";
import * as H from "solid-js/h";
import * as Web from "solid-js/web";
import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";
import * as Stdlib_JsError from "@rescript/runtime/lib/es6/Stdlib_JsError.js";
import * as Primitive_option from "@rescript/runtime/lib/es6/Primitive_option.js";

function Features$Thrower(props) {
  if (props.shouldThrow) {
    Stdlib_JsError.throwWithMessage("Boom!");
  }
  return <div>
    {"All good"}
  </div>;
}

let Thrower = {
  make: Features$Thrower
};

function Features$ToggleError(props) {
  let match = SolidJs.createSignal(false);
  let setShouldThrow = match[1];
  return <div>
    <button
      onClick={param => setShouldThrow(prev => !prev)}
    >
      {"Toggle Error"}
    </button>
    <SolidJs.ErrorBoundary
      fallback={(e, _reset) => <div>
        {"Error: " + e.message}
      </div>}
    >
      <Thrower.make
        shouldThrow={match[0]()}
      />
    </SolidJs.ErrorBoundary>
  </div>;
}

let ToggleError = {
  make: Features$ToggleError
};

function Features(props) {
  let fetchGreeting = () => new Promise((resolve, _reject) => {
    setTimeout(() => resolve("Hello from network"), 600);
  });
  let match = SolidJs.createResource(fetchGreeting);
  let greeting = match[0];
  let mount = Document.getElementById("portal-root");
  let match$1 = SolidJs.createSignal(1);
  let setN = match$1[1];
  let n = match$1[0];
  let doubled = SolidJs.createMemo(() => (n() << 1));
  return <div>
    <h3>
      {"Resource + Suspense"}
    </h3>
    <SolidJs.Show
      when={greeting()}
      fallback={"Loading..."}
    >
      {value => {
        if (value !== undefined) {
          return <div>
            {value}
          </div>;
        } else {
          return "";
        }
      }}
    </SolidJs.Show>
    <SolidJs.Suspense
      fallback={"Loading Suspense"}
    >
      {Stdlib_Option.mapOr(greeting(), "No greeting", arg => arg)}
    </SolidJs.Suspense>
    <hr />
    <h3>
      {"Portal"}
    </h3>
    {mount !== undefined ? <Web.Portal
        mount={Primitive_option.some(Primitive_option.valFromOption(mount))}
      >
        <div>
          {"I am in a portal"}
        </div>
      </Web.Portal> : <div>
        {"No portal root"}
      </div>}
    <hr />
    <h3>
      {"Memo + Effect"}
    </h3>
    {SolidJs.createEffect(() => {
      console.log("n=" + String(n()) + ", doubled=" + String(doubled()));
    }), <div>
      <button
        onClick={param => setN(prev => prev + 1 | 0)}
      >
        {"Inc"}
      </button>
      <div>
        {"n="}
        {n()}
        {", doubled="}
        {doubled()}
      </div>
    </div>}
    <hr />
    <h3>
      {"ErrorBoundary"}
    </h3>
    <div>
      <SolidJs.ErrorBoundary
        fallback={(e, _reset) => <div>
          {"Error: " + e.message}
        </div>}
      >
        <div>
          {"forget about it"}
        </div>
      </SolidJs.ErrorBoundary>
    </div>
  </div>;
}

let Suspense;

let Show;

let ErrorBoundary;

let Portal;

let Scope;

let make = Features;

export {
  Suspense,
  Show,
  ErrorBoundary,
  Portal,
  Scope,
  Thrower,
  ToggleError,
  make,
}
/* solid-js Not a pure module */
