// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function ReactivityEdgeCases$IIFEInJSX(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let attemptIIFE = (count() << 1);
  return <div>
    <h3>
      {"IIFE in JSX Test"}
    </h3>
    <p>
      {"Attempt IIFE: "}
      {attemptIIFE}
    </p>
    <p>
      {"Direct call: "}
      {(count() << 1)}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let IIFEInJSX = {
  make: ReactivityEdgeCases$IIFEInJSX
};

function ReactivityEdgeCases$ComplexExpressionsLifted(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let doubled = (count() << 1);
  let tripled = count() * 3 | 0;
  let complexCalc = doubled + tripled | 0;
  return <div>
    <h3>
      {"Complex Expression Lifting"}
    </h3>
    <p>
      {"Complex calc: "}
      {complexCalc}
    </p>
    <p>
      {"Count: "}
      {count()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - Does complexCalc update?"}
    </button>
  </div>;
}

let ComplexExpressionsLifted = {
  make: ReactivityEdgeCases$ComplexExpressionsLifted
};

function ReactivityEdgeCases$InlineConditionals(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let result = count() > 5 ? (count() << 1) : count() + 1 | 0;
  return <div>
    <h3>
      {"Inline Conditionals"}
    </h3>
    <p>
      {"Result (computed once): "}
      {result}
    </p>
    <p>
      {"Result (inline): "}
      {count() > 5 ? (count() << 1) : count() + 1 | 0}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let InlineConditionals = {
  make: ReactivityEdgeCases$InlineConditionals
};

function ReactivityEdgeCases$PatternMatchingSignals(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let n = count();
  let message = n > 10 ? "High" : (
      n > 5 ? "Medium" : "Low"
    );
  let n$1 = count();
  return <div>
    <h3>
      {"Pattern Matching with Signals"}
    </h3>
    <p>
      {"Message (computed once): "}
      {message}
    </p>
    <p>
      {"Message (inline): "}
      {n$1 > 10 ? "High" : (
          n$1 > 5 ? "Medium" : "Low"
        )}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let PatternMatchingSignals = {
  make: ReactivityEdgeCases$PatternMatchingSignals
};

function ReactivityEdgeCases$ArrayOpsInJSX(props) {
  let match = SolidJs.createSignal([
    1,
    2,
    3
  ]);
  let setItems = match[1];
  let items = match[0];
  let mapped = items().map(x => (x << 1));
  return <div>
    <h3>
      {"Array Operations in JSX"}
    </h3>
    <p>
      {"Mapped length (computed once): "}
      {mapped.length}
    </p>
    <p>
      {"Items count: "}
      {items().length}
    </p>
    <SolidJs.For
      each={items().map(x => (x << 1))}
    >
      {(item, _i) => <span>
        {item}
        {" "}
      </span>}
    </SolidJs.For>
    <button
      onClick={param => setItems(prev => prev.concat([prev.length + 1 | 0]))}
    >
      {"Add Item"}
    </button>
  </div>;
}

let ArrayOpsInJSX = {
  make: ReactivityEdgeCases$ArrayOpsInJSX
};

function ReactivityEdgeCases$NestedReactiveContexts(props) {
  let match = SolidJs.createSignal(0);
  let setOuter = match[1];
  let outer = match[0];
  let match$1 = SolidJs.createSignal(0);
  let setInner = match$1[1];
  let inner = match$1[0];
  let combined = SolidJs.createMemo(() => outer() + inner() | 0);
  let snapshot = combined();
  return <div>
    <h3>
      {"Nested Reactive Contexts"}
    </h3>
    <p>
      {"Outer: "}
      {outer()}
    </p>
    <p>
      {"Inner: "}
      {inner()}
    </p>
    <p>
      {"Combined (memo): "}
      {combined()}
    </p>
    <p>
      {"Snapshot: "}
      {snapshot}
    </p>
    <button
      onClick={param => setOuter(prev => prev + 1 | 0)}
    >
      {"Inc Outer"}
    </button>
    <button
      onClick={param => setInner(prev => prev + 1 | 0)}
    >
      {"Inc Inner"}
    </button>
  </div>;
}

let NestedReactiveContexts = {
  make: ReactivityEdgeCases$NestedReactiveContexts
};

function ReactivityEdgeCases$ObjectCreationWithSignals(props) {
  let match = SolidJs.createSignal("John");
  let setFirstName = match[1];
  let firstName = match[0];
  let match$1 = SolidJs.createSignal("Doe");
  let lastName = match$1[0];
  let person = {
    first: firstName(),
    last: lastName(),
    full: firstName() + " " + lastName()
  };
  return <div>
    <h3>
      {"Object Creation with Signals"}
    </h3>
    <p>
      {"Person.full (created once): "}
      {person.full}
    </p>
    <p>
      {"Direct concat: "}
      {firstName() + " " + lastName()}
    </p>
    <button
      onClick={param => setFirstName(param => "Jane")}
    >
      {"Change First Name"}
    </button>
  </div>;
}

let ObjectCreationWithSignals = {
  make: ReactivityEdgeCases$ObjectCreationWithSignals
};

function computeExpensive(n) {
  console.log("Computing expensive: " + n.toString());
  return n * n | 0;
}

function ReactivityEdgeCases$FunctionCallsWithSignals(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let result1 = computeExpensive(count());
  let result2 = SolidJs.createMemo(() => computeExpensive(count()));
  return <div>
    <h3>
      {"Function Calls with Signals"}
    </h3>
    <p>
      {"Result1 (called once): "}
      {result1}
    </p>
    <p>
      {"Result2 (memo): "}
      {result2()}
    </p>
    <p>
      {"Result3 (inline): "}
      {computeExpensive(count())}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - Check console"}
    </button>
  </div>;
}

let FunctionCallsWithSignals = {
  computeExpensive: computeExpensive,
  make: ReactivityEdgeCases$FunctionCallsWithSignals
};

function ReactivityEdgeCases$ClosureScoping(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let captured = count();
  let closureValue = () => captured;
  return <div>
    <h3>
      {"Closure Scoping"}
    </h3>
    <p>
      {"Closure value: "}
      {closureValue()}
    </p>
    <p>
      {"Direct value: "}
      {count()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let ClosureScoping = {
  make: ReactivityEdgeCases$ClosureScoping
};

function ReactivityEdgeCases$MultipleSignalReads(props) {
  let match = SolidJs.createSignal(1);
  let setA = match[1];
  let a = match[0];
  let match$1 = SolidJs.createSignal(2);
  let setB = match$1[1];
  let b = match$1[0];
  let match$2 = SolidJs.createSignal(3);
  let setC = match$2[1];
  let c = match$2[0];
  let sum = (a() + b() | 0) + c() | 0;
  return <div>
    <h3>
      {"Multiple Signal Reads"}
    </h3>
    <p>
      {"Sum (computed once): "}
      {sum}
    </p>
    <p>
      {"Sum (inline): "}
      {(a() + b() | 0) + c() | 0}
    </p>
    <button
      onClick={param => setA(prev => prev + 1 | 0)}
    >
      {"Inc A"}
    </button>
    <button
      onClick={param => setB(prev => prev + 1 | 0)}
    >
      {"Inc B"}
    </button>
    <button
      onClick={param => setC(prev => prev + 1 | 0)}
    >
      {"Inc C"}
    </button>
  </div>;
}

let MultipleSignalReads = {
  make: ReactivityEdgeCases$MultipleSignalReads
};

function ReactivityEdgeCases$StringInterpolation(props) {
  let match = SolidJs.createSignal("World");
  let setName = match[1];
  let name = match[0];
  let match$1 = SolidJs.createSignal(0);
  let setCount = match$1[1];
  let count = match$1[0];
  let greeting = "Hello " + name() + ", count: " + count().toString();
  return <div>
    <h3>
      {"String Interpolation"}
    </h3>
    <p>
      {"Greeting (created once): "}
      {greeting}
    </p>
    <p>
      {"Greeting (inline): "}
      {"Hello " + name() + ", count: " + count().toString()}
    </p>
    <button
      onClick={param => setName(param => "Solid")}
    >
      {"Change Name"}
    </button>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Inc Count"}
    </button>
  </div>;
}

let StringInterpolation = {
  make: ReactivityEdgeCases$StringInterpolation
};

function ReactivityEdgeCases$OptionalChainingSignals(props) {
  let match = SolidJs.createSignal({
    name: "Alice",
    age: 25
  });
  let setUser = match[1];
  let user = match[0];
  let age = user().age;
  let n = user().age;
  return <div>
    <h3>
      {"Optional Chaining"}
    </h3>
    <p>
      {"Age (captured): "}
      {age !== undefined ? age : "N/A"}
    </p>
    <p>
      {"Age (inline): "}
      {n !== undefined ? n : "N/A"}
    </p>
    <button
      onClick={param => setUser(param => ({
        name: "Bob",
        age: 30
      }))}
    >
      {"Change User"}
    </button>
    <button
      onClick={param => setUser(param => ({
        name: "Charlie",
        age: undefined
      }))}
    >
      {"Clear Age"}
    </button>
  </div>;
}

let OptionalChainingSignals = {
  make: ReactivityEdgeCases$OptionalChainingSignals
};

function ReactivityEdgeCases$SwitchInlineVsExtracted(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let n = count();
  let extractedMessage = n > 10 ? "Very High" : (
      n > 5 ? "High" : (
          n > 0 ? "Medium" : "Low"
        )
    );
  let accessorMessage = () => {
    let n = count();
    if (n > 10) {
      return "Very High";
    } else if (n > 5) {
      return "High";
    } else if (n > 0) {
      return "Medium";
    } else {
      return "Low";
    }
  };
  let memoMessage = SolidJs.createMemo(() => {
    let n = count();
    if (n > 10) {
      return "Very High";
    } else if (n > 5) {
      return "High";
    } else if (n > 0) {
      return "Medium";
    } else {
      return "Low";
    }
  });
  let n$1 = count();
  return <div>
    <h3>
      {"🔬 Switch Statement Tests"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <p>
      {"Extracted (should freeze): "}
      {extractedMessage}
    </p>
    <p>
      {"Accessor (should update): "}
      {accessorMessage()}
    </p>
    <p>
      {"Memo (should update): "}
      {memoMessage()}
    </p>
    <p>
      {"Inline (should update): "}
      {n$1 > 10 ? "Very High" : (
          n$1 > 5 ? "High" : (
              n$1 > 0 ? "Medium" : "Low"
            )
        )}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <button
      onClick={param => setCount(param => 0)}
    >
      {"Reset"}
    </button>
  </div>;
}

let SwitchInlineVsExtracted = {
  make: ReactivityEdgeCases$SwitchInlineVsExtracted
};

function ReactivityEdgeCases$ShowTypeNarrowingTest(props) {
  let match = SolidJs.createSignal(undefined);
  let setUser = match[1];
  return <div>
    <h3>
      {"🔬 Show Component + Type Narrowing"}
    </h3>
    <SolidJs.Show
      when={match[0]()}
      fallback={"No user"}
    >
      {userValue => {
        if (userValue === undefined) {
          return "Unexpected None";
        }
        let age = userValue.age;
        return <div>
          <p>
            {"Name: "}
            {userValue.name}
          </p>
          <p>
            {"Age: "}
            {age !== undefined ? age : "Unknown"}
          </p>
        </div>;
      }}
    </SolidJs.Show>
    <button
      onClick={param => setUser(param => ({
        name: "Alice",
        age: 25
      }))}
    >
      {"Set Alice (25)"}
    </button>
    <button
      onClick={param => setUser(param => ({
        name: "Bob",
        age: undefined
      }))}
    >
      {"Set Bob (no age)"}
    </button>
    <button
      onClick={param => setUser(param => {})}
    >
      {"Clear"}
    </button>
  </div>;
}

let ShowTypeNarrowingTest = {
  make: ReactivityEdgeCases$ShowTypeNarrowingTest
};

function ReactivityEdgeCases$ForComponentTest(props) {
  let match = SolidJs.createSignal([
    {
      id: 1,
      name: "Item 1",
      active: true
    },
    {
      id: 2,
      name: "Item 2",
      active: false
    },
    {
      id: 3,
      name: "Item 3",
      active: true
    }
  ]);
  let setItems = match[1];
  let items = match[0];
  let frozenFiltered = items().filter(item => item.active);
  let accessorFiltered = () => items().filter(item => item.active);
  let memoFiltered = SolidJs.createMemo(() => items().filter(item => item.active));
  return <div>
    <h3>
      {"🔬 For Component Tests"}
    </h3>
    <p>
      {"Frozen filtered count: "}
      {frozenFiltered.length}
    </p>
    <p>
      {"Accessor filtered count: "}
      {accessorFiltered().length}
    </p>
    <p>
      {"Memo filtered count: "}
      {memoFiltered().length}
    </p>
    <h4>
      {"All Items:"}
    </h4>
    <SolidJs.For
      each={items()}
    >
      {(item, _i) => <div>
        <input
          checked={item.active}
          type={"checkbox"}
          onChange={param => {
            let id = item.id;
            setItems(prev => prev.map(item => {
              if (item.id === id) {
                return {
                  id: item.id,
                  name: item.name,
                  active: !item.active
                };
              } else {
                return item;
              }
            }));
          }}
        />
        {item.name}
      </div>}
    </SolidJs.For>
    <h4>
      {"Filtered (inline - should update):"}
    </h4>
    <SolidJs.For
      each={items().filter(item => item.active)}
    >
      {(item, _i) => <div>
        {item.name}
      </div>}
    </SolidJs.For>
    <h4>
      {"Filtered (memo - should update):"}
    </h4>
    <SolidJs.For
      each={memoFiltered()}
    >
      {(item, _i) => <div>
        {item.name}
      </div>}
    </SolidJs.For>
  </div>;
}

let ForComponentTest = {
  make: ReactivityEdgeCases$ForComponentTest
};

function ReactivityEdgeCases$ScopingTests(props) {
  let match = SolidJs.createSignal(0);
  let setOuter = match[1];
  let outer = match[0];
  let inner = outer();
  let scopeTest2 = () => {
    let inner = outer();
    return (inner << 1);
  };
  let times3 = () => outer() * 3 | 0;
  let times5 = () => outer() * 5 | 0;
  return <div>
    <h3>
      {"🔬 Scoping Tests"}
    </h3>
    <p>
      {"Outer: "}
      {outer()}
    </p>
    <p>
      {"ScopeTest1 (frozen inner): "}
      {(inner << 1)}
    </p>
    <p>
      {"ScopeTest2 (fresh read): "}
      {scopeTest2()}
    </p>
    <p>
      {"Times 3 (closure): "}
      {times3()}
    </p>
    <p>
      {"Times 5 (closure): "}
      {times5()}
    </p>
    <button
      onClick={param => setOuter(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let ScopingTests = {
  make: ReactivityEdgeCases$ScopingTests
};

function expensiveComputation(n) {
  console.log("Computing expensive for: " + n.toString());
  return (n * n | 0) * n | 0;
}

function ReactivityEdgeCases$ManualAccessorVsMemo(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let frozenExpensive = expensiveComputation(count());
  let memoExpensive = SolidJs.createMemo(() => expensiveComputation(count()));
  return <div>
    <h3>
      {"🔬 Manual Accessor vs Memo"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <p>
      {"Frozen (never updates): "}
      {frozenExpensive}
    </p>
    <p>
      {"Accessor (check console - calls multiple times): "}
      {expensiveComputation(count())}
      {" | "}
      {expensiveComputation(count())}
      {" (called twice!)"}
    </p>
    <p>
      {"Memo (cached - only one computation): "}
      {memoExpensive()}
      {" | "}
      {memoExpensive()}
      {" (cached!)"}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment (check console)"}
    </button>
  </div>;
}

let ManualAccessorVsMemo = {
  expensiveComputation: expensiveComputation,
  make: ReactivityEdgeCases$ManualAccessorVsMemo
};

function ReactivityEdgeCases$TypeNarrowingPatternMatch(props) {
  let match = SolidJs.createSignal("Loading");
  let setResponse = match[1];
  let response = match[0];
  let match$1 = response();
  let extractedMessage;
  extractedMessage = typeof match$1 !== "object" ? "Loading..." : (
      match$1.TAG === "Success" ? "Success: " + match$1.data + " (" + match$1.count.toString() + ")" : "Error: " + match$1.message
    );
  let accessorMessage = () => {
    let match = response();
    if (typeof match !== "object") {
      return "Loading...";
    } else if (match.TAG === "Success") {
      return "Success: " + match.data + " (" + match.count.toString() + ")";
    } else {
      return "Error: " + match.message;
    }
  };
  let match$2 = response();
  let tmp;
  tmp = typeof match$2 !== "object" ? "Loading..." : (
      match$2.TAG === "Success" ? "Success: " + match$2.data + " (" + match$2.count.toString() + ")" : "Error: " + match$2.message
    );
  let match$3 = response();
  let tmp$1;
  tmp$1 = typeof match$3 !== "object" ? false : match$3.TAG === "Success";
  return <div>
    <h3>
      {"🔬 Type Narrowing + Pattern Match"}
    </h3>
    <p>
      {"Extracted (frozen): "}
      {extractedMessage}
    </p>
    <p>
      {"Accessor (updates): "}
      {accessorMessage()}
    </p>
    <p>
      {"Inline (updates): "}
      {tmp}
    </p>
    <h4>
      {"Using Show component:"}
    </h4>
    <SolidJs.Show
      when={tmp$1}
      fallback={"Not success"}
    >
      {param => {
        let match = response();
        if (typeof match !== "object" || match.TAG !== "Success") {
          return null;
        } else {
          return <div>
            {"Data: " + match.data + ", Count: " + match.count.toString()}
          </div>;
        }
      }}
    </SolidJs.Show>
    <div>
      <button
        onClick={param => setResponse(param => "Loading")}
      >
        {"Set Loading"}
      </button>
      <button
        onClick={param => setResponse(param => ({
          TAG: "Success",
          data: "Hello",
          count: 42
        }))}
      >
        {"Set Success"}
      </button>
      <button
        onClick={param => setResponse(param => ({
          TAG: "Error",
          message: "Oops!"
        }))}
      >
        {"Set Error"}
      </button>
    </div>
  </div>;
}

let TypeNarrowingPatternMatch = {
  make: ReactivityEdgeCases$TypeNarrowingPatternMatch
};

function ReactivityEdgeCases(props) {
  return <div>
    <h1>
      {"🔬 Reactivity Edge Cases & Limitations"}
    </h1>
    <p>
      {"Testing ReScript compilation + Solid reactivity interactions"}
    </p>
    <p>
      <strong>
        {"⚠️ Look for values that don't update when they should!"}
      </strong>
    </p>
    <hr />
    <IIFEInJSX.make />
    <hr />
    <ComplexExpressionsLifted.make />
    <hr />
    <InlineConditionals.make />
    <hr />
    <PatternMatchingSignals.make />
    <hr />
    <ArrayOpsInJSX.make />
    <hr />
    <NestedReactiveContexts.make />
    <hr />
    <ObjectCreationWithSignals.make />
    <hr />
    <ReactivityEdgeCases$FunctionCallsWithSignals />
    <hr />
    <ClosureScoping.make />
    <hr />
    <MultipleSignalReads.make />
    <hr />
    <StringInterpolation.make />
    <hr />
    <OptionalChainingSignals.make />
    <hr />
    <h2>
      {"🔬 VERIFICATION TESTS"}
    </h2>
    <SwitchInlineVsExtracted.make />
    <hr />
    <ShowTypeNarrowingTest.make />
    <hr />
    <ForComponentTest.make />
    <hr />
    <ScopingTests.make />
    <hr />
    <ReactivityEdgeCases$ManualAccessorVsMemo />
    <hr />
    <TypeNarrowingPatternMatch.make />
  </div>;
}

let make = ReactivityEdgeCases;

export {
  IIFEInJSX,
  ComplexExpressionsLifted,
  InlineConditionals,
  PatternMatchingSignals,
  ArrayOpsInJSX,
  NestedReactiveContexts,
  ObjectCreationWithSignals,
  FunctionCallsWithSignals,
  ClosureScoping,
  MultipleSignalReads,
  StringInterpolation,
  OptionalChainingSignals,
  SwitchInlineVsExtracted,
  ShowTypeNarrowingTest,
  ForComponentTest,
  ScopingTests,
  ManualAccessorVsMemo,
  TypeNarrowingPatternMatch,
  make,
}
/* solid-js Not a pure module */
