// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function ReactivityTest$Section(props) {
  return <div>
    <h3>
      {props.title}
    </h3>
    {props.children}
    <hr />
  </div>;
}

let Section = {
  make: ReactivityTest$Section
};

function ReactivityTest$BasicSignal(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  return <Section.make
    title={"1. Basic Signal (SHOULD work)"}
  >
    <p>
      {"Count: "}
      <strong>
        {match[0]()}
      </strong>
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p
      className={"note"}
    >
      {"Signal read directly in JSX - reactive"}
    </p>
  </Section.make>;
}

let BasicSignal = {
  make: ReactivityTest$BasicSignal
};

function ReactivityTest$DerivedMemo(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let doubled = SolidJs.createMemo(() => (count() << 1));
  let tripled = SolidJs.createMemo(() => count() * 3 | 0);
  return <Section.make
    title={"2. Derived with createMemo (SHOULD work)"}
  >
    <p>
      {"Count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <p>
      {"Doubled: "}
      <strong>
        {doubled()}
      </strong>
    </p>
    <p>
      {"Tripled: "}
      <strong>
        {tripled()}
      </strong>
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p
      className={"note"}
    >
      {"Memos track signal and update reactively"}
    </p>
  </Section.make>;
}

let DerivedMemo = {
  make: ReactivityTest$DerivedMemo
};

function ReactivityTest$BrokenEager(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let capturedValue = count();
  let eagerDoubled = (capturedValue << 1);
  return <Section.make
    title={"3. BROKEN: Eager Evaluation (will NOT update)"}
  >
    <p>
      {"Reactive count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <p
      className={"broken"}
    >
      {"Captured value: "}
      <strong>
        {capturedValue}
      </strong>
    </p>
    <p
      className={"broken"}
    >
      {"Eager doubled: "}
      <strong>
        {eagerDoubled}
      </strong>
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p
      className={"note"}
    >
      {"capturedValue reads signal outside tracking context - static!"}
    </p>
  </Section.make>;
}

let BrokenEager = {
  make: ReactivityTest$BrokenEager
};

function ReactivityTest$FixedLazy(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let lazyDoubled = () => (count() << 1);
  return <Section.make
    title={"3b. FIXED: Lazy Evaluation (SHOULD work)"}
  >
    <p>
      {"Reactive count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <p
      className={"fixed"}
    >
      {"Lazy doubled: "}
      <strong>
        {() => (count() << 1)}
      </strong>
    </p>
    <p
      className={"fixed"}
    >
      {"Via variable: "}
      <strong>
        {lazyDoubled}
      </strong>
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p
      className={"note"}
    >
      {"lazyInt(() => expr) defers evaluation - Solid tracks it reactively"}
    </p>
  </Section.make>;
}

let FixedLazy = {
  make: ReactivityTest$FixedLazy
};

function ReactivityTest$ConditionalShow(props) {
  let match = SolidJs.createSignal(true);
  let setVisible = match[1];
  let visible = match[0];
  let match$1 = SolidJs.createSignal(0);
  let setCount = match$1[1];
  let count = match$1[0];
  return <Section.make
    title={"4. Conditional with Show (SHOULD work)"}
  >
    <button
      onClick={param => setVisible(prev => !prev)}
    >
      {visible() ? "Hide" : "Show"}
    </button>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <SolidJs.Show
      when={visible()}
      fallback={"Hidden"}
    >
      {param => <p>
        {"Count: "}
        <strong>
          {count()}
        </strong>
      </p>}
    </SolidJs.Show>
  </Section.make>;
}

let ConditionalShow = {
  make: ReactivityTest$ConditionalShow
};

function ReactivityTest$ListFor(props) {
  let match = SolidJs.createSignal([
    "A",
    "B",
    "C"
  ]);
  let setItems = match[1];
  let addItem = param => setItems(prev => prev.concat([String(prev.length)]));
  return <Section.make
    title={"5. List with For (SHOULD work)"}
  >
    <button
      onClick={addItem}
    >
      {"Add Item"}
    </button>
    <ul>
      <SolidJs.For
        each={match[0]()}
        fallback={"Empty"}
      >
        {(item, _i) => <li>
          {item}
        </li>}
      </SolidJs.For>
    </ul>
  </Section.make>;
}

let ListFor = {
  make: ReactivityTest$ListFor
};

function ReactivityTest$EffectTracking(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let match$1 = SolidJs.createSignal(["Initial"]);
  let setLog = match$1[1];
  SolidJs.createEffect(() => {
    let current = count();
    setLog(prev => prev.concat(["Effect ran: count = " + current.toString()]));
  });
  return <Section.make
    title={"6. Effect Tracking (SHOULD work)"}
  >
    <p>
      {"Count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <div
      className={"log-box"}
    >
      <SolidJs.For
        each={match$1[0]()}
        fallback={null}
      >
        {(entry, _i) => <div
          className={"log-entry"}
        >
          {entry}
        </div>}
      </SolidJs.For>
    </div>
  </Section.make>;
}

let EffectTracking = {
  make: ReactivityTest$EffectTracking
};

function ReactivityTest$ChildDisplay(props) {
  return <span
    className={"highlight"}
  >
    {"Received: "}
    {props.value}
  </span>;
}

let ChildDisplay = {
  make: ReactivityTest$ChildDisplay
};

function ReactivityTest$NestedProps(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  return <Section.make
    title={"7. Nested Component Props (SHOULD work)"}
  >
    <p>
      {"Parent count: "}
      <strong>
        {count()}
      </strong>
    </p>
    <p>
      {"Child: "}
      <ChildDisplay.make
        value={count()}
      />
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
    <p
      className={"note"}
    >
      {"Child should update when parent signal changes"}
    </p>
  </Section.make>;
}

let NestedProps = {
  make: ReactivityTest$NestedProps
};

function ReactivityTest$BatchUpdates(props) {
  let match = SolidJs.createSignal(0);
  let setA = match[1];
  let a = match[0];
  let match$1 = SolidJs.createSignal(0);
  let setB = match$1[1];
  let b = match$1[0];
  let renderCount = SolidJs.createSignal(0);
  let setRenderCount = renderCount[1];
  SolidJs.createEffect(() => {
    a() + b() | 0;
    setRenderCount(prev => prev + 1 | 0);
  });
  let incrementBoth = param => SolidJs.batch(() => {
    setA(prev => prev + 1 | 0);
    setB(prev => prev + 1 | 0);
  });
  let incrementSeparate = param => {
    setA(prev => prev + 1 | 0);
    setB(prev => prev + 1 | 0);
  };
  return <Section.make
    title={"8. Batch Updates"}
  >
    <p>
      {"A: "}
      {a()}
      {", B: "}
      {b()}
    </p>
    <p>
      {"Effect runs: "}
      {renderCount[0]()}
    </p>
    <button
      onClick={incrementBoth}
    >
      {"Batch Increment"}
    </button>
    <button
      onClick={incrementSeparate}
    >
      {"Separate Increment"}
    </button>
    <p
      className={"note"}
    >
      {"Batch should trigger effect once, separate twice"}
    </p>
  </Section.make>;
}

let BatchUpdates = {
  make: ReactivityTest$BatchUpdates
};

function ReactivityTest(props) {
  return <div
    className={"container"}
  >
    <h1>
      {"Solid.js Reactivity Test Suite"}
    </h1>
    <p
      className={"subtitle"}
    >
      {"Click buttons and observe which sections update correctly."}
    </p>
    <BasicSignal.make />
    <DerivedMemo.make />
    <BrokenEager.make />
    <FixedLazy.make />
    <ConditionalShow.make />
    <ListFor.make />
    <EffectTracking.make />
    <NestedProps.make />
    <BatchUpdates.make />
  </div>;
}

let make = ReactivityTest;

export {
  Section,
  BasicSignal,
  DerivedMemo,
  BrokenEager,
  FixedLazy,
  ConditionalShow,
  ListFor,
  EffectTracking,
  ChildDisplay,
  NestedProps,
  BatchUpdates,
  make,
}
/* solid-js Not a pure module */
