// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function ReactivityPatterns$CorrectSignalAccess(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  return <div>
    <h3>
      {"✅ Correct Signal Access"}
    </h3>
    <p>
      {"Count: "}
      {match[0]()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let CorrectSignalAccess = {
  make: ReactivityPatterns$CorrectSignalAccess
};

function ReactivityPatterns$CorrectDerivedState(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let doubled = SolidJs.createMemo(() => (count() << 1));
  let quadrupled = SolidJs.createMemo(() => (doubled() << 1));
  return <div>
    <h3>
      {"✅ Correct Derived State with Memos"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <p>
      {"Doubled: "}
      {doubled()}
    </p>
    <p>
      {"Quadrupled: "}
      {quadrupled()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let CorrectDerivedState = {
  make: ReactivityPatterns$CorrectDerivedState
};

function ReactivityPatterns$CorrectEffect(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  SolidJs.createEffect(() => {
    console.log("Count changed to: " + count().toString());
  });
  return <div>
    <h3>
      {"✅ Correct Effect Usage"}
    </h3>
    <p>
      {"Count: "}
      {count()}
      {" (check console)"}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let CorrectEffect = {
  make: ReactivityPatterns$CorrectEffect
};

function ReactivityPatterns$CorrectPropsUsage$Child(props) {
  let onIncrement = props.onIncrement;
  return <div>
    <p>
      {"Child count: "}
      {props.count()}
    </p>
    <button
      onClick={param => onIncrement()}
    >
      {"Increment from Child"}
    </button>
  </div>;
}

let Child = {
  make: ReactivityPatterns$CorrectPropsUsage$Child
};

function ReactivityPatterns$CorrectPropsUsage(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  return <div>
    <h3>
      {"✅ Correct Props Passing"}
    </h3>
    <Child.make
      count={match[0]}
      onIncrement={() => setCount(prev => prev + 1 | 0)}
    />
  </div>;
}

let CorrectPropsUsage = {
  Child: Child,
  make: ReactivityPatterns$CorrectPropsUsage
};

function ReactivityPatterns$CorrectArrayMapping(props) {
  let match = SolidJs.createSignal([
    {
      id: 1,
      text: "Learn ReScript",
      completed: false
    },
    {
      id: 2,
      text: "Learn Solid.js",
      completed: false
    }
  ]);
  let setTodos = match[1];
  return <div>
    <h3>
      {"✅ Correct Array Mapping"}
    </h3>
    <SolidJs.For
      each={match[0]()}
    >
      {(todo, _i) => <div>
        <input
          checked={todo.completed}
          type={"checkbox"}
          onChange={param => {
            let id = todo.id;
            setTodos(prevTodos => prevTodos.map(todo => {
              if (todo.id === id) {
                return {
                  id: todo.id,
                  text: todo.text,
                  completed: !todo.completed
                };
              } else {
                return todo;
              }
            }));
          }}
        />
        {todo.text}
      </div>}
    </SolidJs.For>
  </div>;
}

let CorrectArrayMapping = {
  make: ReactivityPatterns$CorrectArrayMapping
};

function ReactivityPatterns$CorrectUntrack(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let match$1 = SolidJs.createSignal(0);
  let setLastEvenCount = match$1[1];
  let lastEvenCount = match$1[0];
  SolidJs.createEffect(() => {
    let currentCount = count();
    if (currentCount % 2 !== 0) {
      return;
    }
    let prev = SolidJs.untrack(() => lastEvenCount());
    console.log("Previous even: " + prev.toString() + ", Current even: " + currentCount.toString());
    setLastEvenCount(param => currentCount);
  });
  return <div>
    <h3>
      {"✅ Correct Untrack Usage"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <p>
      {"Last Even Count: "}
      {lastEvenCount()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let CorrectUntrack = {
  make: ReactivityPatterns$CorrectUntrack
};

function ReactivityPatterns$CorrectBatch(props) {
  let match = SolidJs.createSignal("John");
  let setFirstName = match[1];
  let firstName = match[0];
  let match$1 = SolidJs.createSignal("Doe");
  let setLastName = match$1[1];
  let lastName = match$1[0];
  let fullName = SolidJs.createMemo(() => firstName() + " " + lastName());
  SolidJs.createEffect(() => {
    console.log("Full name changed to: " + fullName());
  });
  let updateName = () => SolidJs.batch(() => {
    setFirstName(param => "Jane");
    setLastName(param => "Smith");
  });
  return <div>
    <h3>
      {"✅ Correct Batch Usage"}
    </h3>
    <p>
      {"Full Name: "}
      {fullName()}
    </p>
    <button
      onClick={param => updateName()}
    >
      {"Change Name (batched)"}
    </button>
  </div>;
}

let CorrectBatch = {
  make: ReactivityPatterns$CorrectBatch
};

function ReactivityPatterns$CorrectCleanup(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  SolidJs.createEffect(() => {
    let interval = setInterval(() => setCount(prev => prev + 1 | 0), 1000);
    SolidJs.onCleanup(() => {
      clearInterval(interval);
    });
  });
  return <div>
    <h3>
      {"✅ Correct Cleanup in Effects"}
    </h3>
    <p>
      {"Auto-incrementing count: "}
      {match[0]()}
    </p>
  </div>;
}

let CorrectCleanup = {
  make: ReactivityPatterns$CorrectCleanup
};

function ReactivityPatterns(props) {
  return <div>
    <h1>
      {"✅ Correct Reactive Patterns"}
    </h1>
    <p>
      {"These examples demonstrate CORRECT usage of Solid.js reactivity"}
    </p>
    <hr />
    <CorrectSignalAccess.make />
    <hr />
    <CorrectDerivedState.make />
    <hr />
    <CorrectEffect.make />
    <hr />
    <ReactivityPatterns$CorrectPropsUsage />
    <hr />
    <CorrectArrayMapping.make />
    <hr />
    <CorrectUntrack.make />
    <hr />
    <CorrectBatch.make />
    <hr />
    <CorrectCleanup.make />
  </div>;
}

let make = ReactivityPatterns;

export {
  CorrectSignalAccess,
  CorrectDerivedState,
  CorrectEffect,
  CorrectPropsUsage,
  CorrectArrayMapping,
  CorrectUntrack,
  CorrectBatch,
  CorrectCleanup,
  make,
}
/* solid-js Not a pure module */
