// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function ReactivityAntiPatterns$DestructuringSignals(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let currentCount = count();
  return <div>
    <h3>
      {"❌ Destructuring Signals (BROKEN)"}
    </h3>
    <p>
      {"Count (stale): "}
      {currentCount}
    </p>
    <p>
      {"Count (correct): "}
      {count()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - First value won't update!"}
    </button>
  </div>;
}

let DestructuringSignals = {
  make: ReactivityAntiPatterns$DestructuringSignals
};

function ReactivityAntiPatterns$DerivingWithoutMemo(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let doubled = (count() << 1);
  let quadrupled = SolidJs.createMemo(() => (count() << 2));
  return <div>
    <h3>
      {"❌ Deriving Without Memo (INEFFICIENT)"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <p>
      {"Doubled (broken): "}
      {doubled}
    </p>
    <p>
      {"Quadrupled (correct): "}
      {quadrupled()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - Doubled won't update!"}
    </button>
  </div>;
}

let DerivingWithoutMemo = {
  make: ReactivityAntiPatterns$DerivingWithoutMemo
};

function ReactivityAntiPatterns$SignalInEventHandler(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let handleClick = param => {
    let current = count();
    console.log("Clicked at count: " + current.toString());
    setCount(param => current + 1 | 0);
  };
  let handleClickCorrect = param => {
    let current = count();
    console.log("Clicked at count (correct): " + current.toString());
    setCount(prev => prev + 1 | 0);
  };
  return <div>
    <h3>
      {"❌ Signal in Event Handler (BROKEN)"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <button
      onClick={handleClick}
    >
      {"Broken - Sets to 1 always"}
    </button>
    <button
      onClick={handleClickCorrect}
    >
      {"Correct - Increments properly"}
    </button>
  </div>;
}

let SignalInEventHandler = {
  make: ReactivityAntiPatterns$SignalInEventHandler
};

function ReactivityAntiPatterns$PassingValues$Child(props) {
  return <div>
    <p>
      {"Child count (stale): "}
      {props.count}
    </p>
  </div>;
}

let Child = {
  make: ReactivityAntiPatterns$PassingValues$Child
};

function ReactivityAntiPatterns$PassingValues$CorrectChild(props) {
  return <div>
    <p>
      {"Child count (reactive): "}
      {props.count()}
    </p>
  </div>;
}

let CorrectChild = {
  make: ReactivityAntiPatterns$PassingValues$CorrectChild
};

function ReactivityAntiPatterns$PassingValues(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  return <div>
    <h3>
      {"❌ Passing Values Instead of Accessors"}
    </h3>
    <Child.make
      count={count()}
    />
    <CorrectChild.make
      count={count}
    />
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - Only second updates!"}
    </button>
  </div>;
}

let PassingValues = {
  Child: Child,
  CorrectChild: CorrectChild,
  make: ReactivityAntiPatterns$PassingValues
};

function ReactivityAntiPatterns$ArrayMutations(props) {
  let match = SolidJs.createSignal([
    {
      id: 1,
      name: "Item 1"
    },
    {
      id: 2,
      name: "Item 2"
    }
  ]);
  let setItems = match[1];
  let items = match[0];
  let addItemBroken = () => {
    let currentItems = items();
    console.log("Array length: " + currentItems.length.toString());
  };
  let addItemCorrect = () => setItems(prev => prev.concat([{
      id: 3,
      name: "New Item"
    }]));
  return <div>
    <h3>
      {"❌ Array Mutations"}
    </h3>
    <SolidJs.For
      each={items()}
    >
      {(item, _i) => <div>
        {item.name}
      </div>}
    </SolidJs.For>
    <button
      onClick={param => addItemBroken()}
    >
      {"Add (broken - check console)"}
    </button>
    <button
      onClick={param => addItemCorrect()}
    >
      {"Add (correct)"}
    </button>
  </div>;
}

let ArrayMutations = {
  make: ReactivityAntiPatterns$ArrayMutations
};

function ReactivityAntiPatterns$EffectsInJSX(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  return <div>
    <h3>
      {"❌ Creating Effects in JSX"}
    </h3>
    {SolidJs.createEffect(() => {
      console.log("This runs too often: " + count().toString());
    }), null}
    <p>
      {"Count: "}
      {count()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let EffectsInJSX = {
  make: ReactivityAntiPatterns$EffectsInJSX
};

function ReactivityAntiPatterns$ConditionalSignals(props) {
  let match = props.useSignal ? SolidJs.createSignal(0) : [
      () => 0,
      param => {}
    ];
  let setCount = match[1];
  return <div>
    <h3>
      {"❌ Conditional Signal Creation"}
    </h3>
    <p>
      {"This can cause issues!"}
    </p>
    <p>
      {"Count: "}
      {match[0]()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment"}
    </button>
  </div>;
}

let ConditionalSignals = {
  make: ReactivityAntiPatterns$ConditionalSignals
};

function ReactivityAntiPatterns$NoUpdaterFunction(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let incrementTwiceBroken = param => {
    setCount(param => count() + 1 | 0);
    setCount(param => count() + 1 | 0);
  };
  let incrementTwiceCorrect = param => {
    setCount(prev => prev + 1 | 0);
    setCount(prev => prev + 1 | 0);
  };
  return <div>
    <h3>
      {"❌ Not Using Updater Functions"}
    </h3>
    <p>
      {"Count: "}
      {count()}
    </p>
    <button
      onClick={incrementTwiceBroken}
    >
      {"Increment Twice (might be broken)"}
    </button>
    <button
      onClick={incrementTwiceCorrect}
    >
      {"Increment Twice (correct)"}
    </button>
  </div>;
}

let NoUpdaterFunction = {
  make: ReactivityAntiPatterns$NoUpdaterFunction
};

function ReactivityAntiPatterns$ReadingOutsideContext(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  let count = match[0];
  let initialValue = count();
  SolidJs.createEffect(() => {
    console.log("Count: " + count().toString() + ", Initial: " + initialValue.toString());
  });
  return <div>
    <h3>
      {"❌ Reading Outside Context"}
    </h3>
    <p>
      {"Initial Value (stale): "}
      {initialValue}
    </p>
    <p>
      {"Current Count: "}
      {count()}
    </p>
    <button
      onClick={param => setCount(prev => prev + 1 | 0)}
    >
      {"Increment - Check console"}
    </button>
  </div>;
}

let ReadingOutsideContext = {
  make: ReactivityAntiPatterns$ReadingOutsideContext
};

function ReactivityAntiPatterns(props) {
  return <div>
    <h1>
      {"❌ Anti-Patterns That Break Reactivity"}
    </h1>
    <p>
      {"These examples demonstrate INCORRECT usage that breaks Solid.js reactivity"}
    </p>
    <p>
      <strong>
        {"⚠️ These are intentionally broken to illustrate what NOT to do!"}
      </strong>
    </p>
    <hr />
    <DestructuringSignals.make />
    <hr />
    <DerivingWithoutMemo.make />
    <hr />
    <SignalInEventHandler.make />
    <hr />
    <ReactivityAntiPatterns$PassingValues />
    <hr />
    <ArrayMutations.make />
    <hr />
    <EffectsInJSX.make />
    <hr />
    <ConditionalSignals.make
      useSignal={true}
    />
    <hr />
    <NoUpdaterFunction.make />
    <hr />
    <ReadingOutsideContext.make />
  </div>;
}

let make = ReactivityAntiPatterns;

export {
  DestructuringSignals,
  DerivingWithoutMemo,
  SignalInEventHandler,
  PassingValues,
  ArrayMutations,
  EffectsInJSX,
  ConditionalSignals,
  NoUpdaterFunction,
  ReadingOutsideContext,
  make,
}
/* solid-js Not a pure module */
