// Generated by ReScript, PLEASE EDIT WITH CARE

import * as SolidJs from "solid-js";
import * as H from "solid-js/h";

function ScopeIssues$IIFELiftingIssue(props) {
  let match = SolidJs.createSignal(0);
  let setOuter = match[1];
  console.log("IIFE executing at component creation!");
  let match$1 = SolidJs.createSignal(0);
  let setLocal = match$1[1];
  let iifResult = <button
    onClick={param => setLocal(prev => prev + 1 | 0)}
  >
    {"Local: "}
    {match$1[0]()}
  </button>;
  return <div>
    <h3>
      {"🔴 IIFE Lifting Issue"}
    </h3>
    <p>
      {"Outer: "}
      {match[0]()}
    </p>
    <p>
      {"IIFE result:"}
    </p>
    {iifResult}
    <button
      onClick={param => setOuter(prev => prev + 1 | 0)}
    >
      {"Inc Outer (IIFE doesn't recreate)"}
    </button>
    <p>
      <strong>
        {"❌ Check console - IIFE runs ONCE at component creation!"}
      </strong>
    </p>
  </div>;
}

let IIFELiftingIssue = {
  make: ScopeIssues$IIFELiftingIssue
};

function fetchData() {
  console.log("Fetching...");
  return new Promise((resolve, param) => {
    setTimeout(() => resolve("Data!"), 2000);
  });
}

function ScopeIssues$SuspenseIssue$Broken(props) {
  console.log("Component created - resource creating now!");
  let match = SolidJs.createResource(fetchData);
  let d = match[0]();
  return <div>
    <h4>
      {"❌ Broken"}
    </h4>
    <SolidJs.Suspense
      fallback={"Loading..."}
    >
      <div>
        {d !== undefined ? d : "No data"}
      </div>
    </SolidJs.Suspense>
    <p>
      <strong>
        {"Suspense fallback probably won't show!"}
      </strong>
    </p>
  </div>;
}

let Broken = {
  make: ScopeIssues$SuspenseIssue$Broken
};

function ScopeIssues$SuspenseIssue$DataComponent(props) {
  console.log("DataComponent created - resource inside Suspense!");
  let match = SolidJs.createResource(fetchData);
  let d = match[0]();
  if (d !== undefined) {
    return <div>
      {d}
    </div>;
  } else {
    return <div>
      {"Loading in component..."}
    </div>;
  }
}

let DataComponent = {
  make: ScopeIssues$SuspenseIssue$DataComponent
};

function ScopeIssues$SuspenseIssue$Fixed(props) {
  return <div>
    <h4>
      {"✅ Fixed: Separate component"}
    </h4>
    <SolidJs.Suspense
      fallback={"Loading..."}
    >
      <DataComponent.make />
    </SolidJs.Suspense>
  </div>;
}

let Fixed = {
  make: ScopeIssues$SuspenseIssue$Fixed
};

function ScopeIssues$SuspenseIssue(props) {
  return <div>
    <h3>
      {"🔴 Suspense Boundary"}
    </h3>
    <Broken.make />
    <hr />
    <Fixed.make />
  </div>;
}

let SuspenseIssue = {
  fetchData: fetchData,
  Suspense: undefined,
  Broken: Broken,
  DataComponent: DataComponent,
  Fixed: Fixed,
  make: ScopeIssues$SuspenseIssue
};

function ScopeIssues$NoLocalScopes(props) {
  return <div>
    <h3>
      {"🔴 No Local Scopes in JSX"}
    </h3>
    <p>
      {"In JS Solid, you can:"}
    </p>
    <pre>
      {"{(() => {\n  const [count, setCount] = createSignal(0);\n  return <button>{count()}</button>;\n})()}"}
    </pre>
    <p>
      <strong>
        {"❌ In ReScript, this runs at component creation!"}
      </strong>
    </p>
    <p>
      {"✅ Solution: Use separate components"}
    </p>
  </div>;
}

let NoLocalScopes = {
  make: ScopeIssues$NoLocalScopes
};

function ScopeIssues$LifecycleIssue(props) {
  let match = SolidJs.createSignal(0);
  let setCount = match[1];
  SolidJs.onMount(() => {
    console.log("Mounted!");
  });
  SolidJs.createEffect(() => {
    let interval = setInterval(() => setCount(prev => prev + 1 | 0), 1000);
    SolidJs.onCleanup(() => {
      console.log("Cleanup!");
      clearInterval(interval);
    });
  });
  return <div>
    <h3>
      {"🔴 Lifecycle Hooks"}
    </h3>
    <p>
      {"Count: "}
      {match[0]()}
    </p>
    <p>
      <strong>
        {"✅ onMount/onCleanup must be at component top level"}
      </strong>
    </p>
    <p>
      {"Check console for lifecycle logs"}
    </p>
  </div>;
}

let LifecycleIssue = {
  make: ScopeIssues$LifecycleIssue
};

function ScopeIssues(props) {
  return <div>
    <h1>
      {"🔴 CRITICAL: IIFE & Scope Issues"}
    </h1>
    <div
      style={{
        backgroundColor: "#fff5f5",
        border: "2px solid #fc8181",
        borderRadius: "8px",
        marginBottom: "20px",
        padding: "20px"
      }}
    >
      <h2>
        {"⚠️ KEY LIMITATION"}
      </h2>
      <p>
        <strong>
          {"In JavaScript Solid, you can use {(() => {})()  } for local scopes."}
        </strong>
      </p>
      <p>
        <strong>
          {"In ReScript, IIFEs and block expressions are LIFTED to component creation!"}
        </strong>
      </p>
      <h3>
        {"This breaks:"}
      </h3>
      <ul>
        <li>
          {"✘ Local signal scopes"}
        </li>
        <li>
          {"✘ Suspense boundaries (createResource outside)"}
        </li>
        <li>
          {"✘ ErrorBoundary (errors thrown outside)"}
        </li>
        <li>
          {"✘ Context providers"}
        </li>
        <li>
          {"✘ Lifecycle hooks"}
        </li>
      </ul>
      <h3>
        {"✅ Solution:"}
      </h3>
      <p>
        <strong>
          {"Use separate components instead of IIFEs/blocks!"}
        </strong>
      </p>
    </div>
    <hr />
    <IIFELiftingIssue.make />
    <hr />
    <ScopeIssues$SuspenseIssue />
    <hr />
    <NoLocalScopes.make />
    <hr />
    <LifecycleIssue.make />
    <hr />
    <div>
      <h2>
        {"📋 Summary"}
      </h2>
      <p>
        {"ReScript compilation model differences:"}
      </p>
      <ol>
        <li>
          {"Block expressions {} evaluated at component creation"}
        </li>
        <li>
          {"IIFEs (() => {})() executed at component creation"}
        </li>
        <li>
          {"Pattern matching lifted to component scope"}
        </li>
      </ol>
      <p>
        <strong>
          {"Always use separate components for scoping, not IIFEs!"}
        </strong>
      </p>
    </div>
  </div>;
}

let make = ScopeIssues;

export {
  IIFELiftingIssue,
  SuspenseIssue,
  NoLocalScopes,
  LifecycleIssue,
  make,
}
/* solid-js Not a pure module */
