// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Stdlib_Option from "@rescript/runtime/lib/es6/Stdlib_Option.js";

function jsxFragment(props) {
  return Stdlib_Option.getOr(props.children, null);
}

let Elements = {};

export {
  jsxFragment,
  Elements,
}
/* No side effect */
