// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Store from "solid-js/store";

let Setter = {};

function make(initialValue) {
  return Store.createStore(initialValue);
}

let StoreUtils = {
  make: make
};

export {
  Setter,
  StoreUtils,
}
/* solid-js/store Not a pure module */
